#ifndef QLAB_REMOTE_PROTOCOL_H
#define QLAB_REMOTE_PROTOCOL_H

#include <stdbool.h>
#include <stddef.h>

#define QLAB_REMOTE_PROTOCOL_VERSION 1
#define QLAB_REMOTE_HELPER_VERSION "1.0.0"
#define QLAB_REMOTE_MINIMUM_CODEX_VERSION "0.146.0"
#define QLAB_REMOTE_MAX_FRAME_BYTES (8U * 1024U * 1024U)
#define QLAB_REMOTE_MAX_ID_BYTES 128U
#define QLAB_REMOTE_IDENTITY_EXIT 78

typedef enum {
  MODE_BROWSE,
  MODE_REPOSITORY_HANDSHAKE,
  MODE_AGENT,
  MODE_SETUP_AUTH
} HelperMode;

typedef enum {
  PROTOCOL_INVALID_REQUEST,
  PROTOCOL_METHOD_NOT_ALLOWED,
  PROTOCOL_DUPLICATE_ID
} ProtocolErrorCode;

#endif
