---
categories:
- Quantum Information
date: '2026-01-16'
format:
  html:
    code-fold: true
keep-ipynb: true
lang: en
title: Local estimation of observables
---

## Review on Linear Property Estimation
Given an arbitrary operator $O$, what is the optimal efficiency for estimating its expected value $\mathrm{tr}(O\rho)$ under the constraint of **Local Measurement**?

#### **Case 1:** $O = A_1 \otimes \cdots \otimes A_N, [A_i, A_i^\dagger] = 0$.

This case corresponds to separable operators that are diagonalizable (i.e., normal) at each local position. This is a trivial scenario where one simply measures in the eigenbasis of each operator at every location.

- For example, if $A_i \in \{\mathbb{I},X,Y,Z\}$, it corresponds to estimating $\mathrm{tr}(P\rho)$.
- If $A_i \in \mathrm{SWAP}\cdot \{\mathbb{I},X,Y,Z\}$, it corresponds to estimating $\mathrm{tr}({P\rho^2})$.
Here, although $\mathrm{SWAP}_k\cdot P$ is a non-Hermitian operator, it can be diagonalized (it's easy to prove that $[SP,(SP)^\dagger] = SPPS^\dagger - PS^\dagger SP = 0$).

#### **Case 2:** $O = A_1 \otimes \cdots \otimes A_N, [A_i, A_i^\dagger] \neq 0$.

This case corresponds to separable operators that are not diagonalizable at some positions.
One can decompose it into Hermitian parts via the Cartesian decomposition $A_k := (A_k+A_k^\dagger)/2 + i(A_k - A_k^\dagger)/2$, but this leads to an exponential growth in the number of measurement bases due to the non-commutativity between $(A_k+A_k^\dagger)$ and $(A_k-A_k^\dagger)$!

  <span style="color:red;">
  - Can one find a practical example where $[A_i, A_i^\dagger] \neq 0$?
  - Is this measurement complexity inherently difficult?
  </span>

#### **Case 3:** $O =\sum_{P} \alpha_{P} P$.

- **Term-by-term estimation**.
- **Classical shadow-based approach**: For a single copy, perform local Clifford random measurements at each position. The sample complexity is $3^k$ for weight-$k$ Pauli observables and $4^k$ for arbitrary $k$-local operators.

  <span style="color:red;">
  Question: If two-replica Local measurement is allowed, does it outperform the overhead of $3^k/4^k$?
   </span>

  <span style="color:blue;">
  Answer: Yes! The sample complexity will drop from $3^k$ to $3^{k/2}$ at the cost of losing some phase information.
  </span>
  
- **Derandomized classical shadow-based approach**:
  - Adjust the local Clifford sampling distribution at each position, making it biased according to $O$, rather than uniform.
  - Adaptively select the next Pauli operator to measure in order to cover as many components of $P$ contained within $O$ as possible.
  - A perspective from channel co-diagonalization: find a channel $\Lambda$ such that $\Lambda(P_1),\cdots, \Lambda(P_n)$ are simultaneously diagonalized. Even if the $P_i$s do not commute!
  - This provides a lower bound on the efficiency of local estimation methods.

    <span style="color:red;">
    Question: If two-replica Local measurement is allowed, does there exist an even better derandomization scheme to estimate $\mathrm{tr}(O \rho)$?
    </span>

#### **Case 4:** $ O = \ket{\psi}\!\bra{\psi}$ or $O$ is a low-rank observable.

- When $\ket{\psi}$ is a stabilizer state, there exists a decomposition $O = \sum_{P \in S} \ket{\psi}\!\bra{\psi} P$.
- By analogy to the construction of entanglement witnesses, one can examine $O' = \ket{\psi}\!\bra{\psi} + \alpha \mathbb{I}$ such that operator $O'$ is separable.

## A Piece-by-Piece Generalization to Non-linear Case

Why is this generalization meaningful?

1. To enhance the efficiency of Visual Cooling.
2. To allow for the estimation of more complex non-linear quantities, such as Fisher information, by decomposing into Pauli operators.

How can it be done?

#### Direct Generalization of LCS
#### Non-linear Pauli Classical Shadow