---
categories:
- Readings
date: 2026-01-08
description: 关于如何算各种矩阵群的k-Fold平均
format:
  html:
    html-math-method: katex
    number-sections: true
    toc: true
lang: zh
title: The Weingarten calculus
---

## Weingarten calculus

Due to the fact that any operator $A$ can be decomposed into a linear combination of $k$-point SWAP operators, it can be decomposed on the basis $\{\mathbb{P}^{d}_{\pi}\}_{\pi \in S_k}$. However, this is not an orthonormal basis, so the decomposition coefficients involve a more complex calculation based on the coefficients $\mathrm{tr}(\mathbb{P}_{\pi}^{d}\cdot A)$.

::: {.callout-note icon="false"}
## Lemma (Weingarten calculus) {#lemma:Haar_ave}

For $U \in U(d)$ and $X \in (\mathbb{C}^d)^{\otimes t} \times (\mathbb{C}^d)^{\otimes t}$, the following identity holds:
$$
\Phi_t(X) := \int_{\text{Haar}} U^{\otimes t} X U^{\dagger \otimes t} \, dU =\sum_{\tau,\sigma \in S_t} \text{tr}(X\mathbb{P}^{d,\dagger}_{\tau}) \mathrm{Wg}(\tau\sigma^{-1} , d) \mathbb{P}^d_\sigma,
$$
The coefficients $\mathrm{Wg}(\tau \sigma^{-1}, d)$ are determined by the following relation:
$$
\sum_{\tau\in S_t} \mathrm{Wg}(\tau \sigma^{-1}, d) \text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} \mathbb{P}^{d}_{\rho})= \delta_{\sigma,\rho}.
$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

By definition, $\Phi_t(X)$ is the Haar average of $U^{\otimes t} X (U^\dagger)^{\otimes t}$ on the unitary group.
By variable substitution $U \to VU$, we can prove that for all $V \in U(d)$, we have $V^{\otimes t} \Phi_t(X) (V^\dagger)^{\otimes t} = \Phi_t(X)$.

By Schur-Weyl duality, any operator that commutes with all $V^{\otimes t}$ must lie in the space spanned by the permutation operators $\mathbb{P}^d_\rho$ ($\rho \in S_t$).
Therefore, we can write $\Phi_t(X) = \sum_{\rho \in S_t} c_\rho \, \mathbb{P}^d_\rho$.
On both sides, we multiply by $\mathbb{P}^{d,\dagger}_\tau$ and take the trace, we get $\text{RHS} = \sum_{\rho \in S_t} c_\rho \, \text{Tr}( \mathbb{P}^d_\rho \mathbb{P}^{d,\dagger}_{\tau})$.

Now calculate the LHS:
$$
\begin{aligned}
\text{LHS} = \text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} \Phi_t(X)) 
&= \text{Tr} \left( \mathbb{P}^{d,\dagger}_{\tau} \int_{\text{Haar}} U^{\otimes t} X (U^\dagger)^{\otimes t} \, dU \right) = \int_{\text{Haar}} \text{Tr} \left( \mathbb{P}^{d,\dagger}_{\tau} U^{\otimes t} X (U^\dagger)^{\otimes t} \right) dU \\
&= \int_{\text{Haar}} \text{Tr}(\mathbb{P}^d_{\tau} X) \, dU = \text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} X),
\end{aligned}
$$
Because the trace is invariant under unitary conjugation and Haar measure integration. Therefore, we get the linear equation $\sum_{\rho \in S_t} c_\rho \, \text{Tr}( \mathbb{P}^d_\rho \mathbb{P}^{d,\dagger}_{\tau})= \text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} X)$.
On both sides, we multiply by $\mathrm{Wg}(\sigma^{-1} \tau, d)$ and sum over $\tau \in S_t$, we get:
$$
\sum_{\rho \in S_t} c_\rho \sum_{\tau\in S_t}  \mathrm{Wg}(\sigma^{-1} \tau, d)\text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} \mathbb{P}^d_\rho ) =  \sum_{\tau\in S_t}\mathrm{Wg}(\sigma^{-1} \tau, d)\text{Tr}(\mathbb{P}^{d,\dagger}_{\tau} X) = \sum_{\rho \in S_t} c_\rho \delta_{\sigma,\rho} = c_{\sigma}.
$$
Here we use the fact that $G_{\rho \tau}(d) \mathrm{Wg}_{\tau ,\sigma}(d) := \text{Tr}( \mathbb{P}^d_\rho \mathbb{P}^{d,\dagger}_{\tau}) \mathrm{Wg}(\tau\sigma^{-1}, d) = \delta_{\rho,\sigma}$.
:::

---

## Properties of Weingarten coefficients

Now we show

::: {.callout-note icon="false"}
## Lemma (G is invertible) {#lemma:inver_cond_G}
The Gram matrix $G_{\tau,\sigma}:= \text{tr}(\mathbb{P}^d_{\tau\sigma^{-1}})=d^{c(\tau \sigma^{-1})}$ is invertible if and only if $t \leq d$. Here $c(\tau \sigma^{-1})$ counts the number of cycles in $\tau\cdot \sigma^{-1}$.
:::

In this case, the linear equation $\sum_{\pi \in S_t} G_{\pi,\rho} \, c_\pi = \text{Tr}(\mathbb{P}^{d,\dagger}_{\rho} X)$ has multiple solutions.
We define $\mathrm{Wg}_{\rho,\sigma}(d)$ as the **pseudo-inverse (pseudo-inverse)** of $G_{\pi,\rho}$, which still satisfies $\sum_{\rho} G_{\pi,\rho}\mathrm{Wg}_{\rho\sigma}(d) = \delta_{\pi,\sigma}$. This shows that it gives one solution for $c_{\sigma} =\sum_{\rho} \mathrm{Wg}_{\rho\sigma}(d) \text{Tr}(\mathbb{P}^{d,\dagger}_{\rho} X)$, but not the unique solution.

Next we give the analytic expression of $\mathrm{Wg}_{\sigma,\pi}$.

::: {.callout-note icon="false"}
## Lemma (Analytic expression of Weingarten coefficients)

Given $\pi,\sigma \in S_t$, the **Weingarten coefficients** have the following expression:
$$
\mathrm{Wg}(\sigma\pi^{-1},d):= \frac{1}{(t!)^2}\sum_{\substack{\lambda \vdash t, \ell_m(\lambda)\leq d}}\frac{\chi^{\lambda}(1)^2\chi^\lambda(\sigma\pi^{-1})}{\text{dim}_U(\lambda)}
$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)


For simplicity, we denote $\text{dim}_{S_t}(\lambda)$ as $\text{dim}\lambda$ and use $\text{dim}_{d}(\lambda):= \text{dim}_{S_t}(\lambda)\cdot \text{dim}_{U}(\lambda)$ to represent the dimension of the $\lambda$ type irreducible representation (irreps) embedded in the representation $\pi \to \mathbb{P}_{\pi}^d$.
By definition, $\mathrm{Wg}_{\sigma,\pi}(d)$ is the right pseudo-inverse of the symmetric matrix $G_{\tau,\sigma} =\text{Tr}(\mathbb{P}^d_{\tau} \mathbb{P}^{d,\dagger}_{\sigma})=d^{c(\tau \sigma^{-1})}$.

Consider the linear space spanned by the elements of $S_t$, which have the form $v = \sum_{\pi \in S_t} v_{\pi} \pi$. The element $A_G = \sum_{\pi \in S_t} d^{c(\pi)} \pi$ induces a linear transformation on these vectors, whose matrix representation is $(A_G)_{\tau,\sigma}= d^{c(\tau \sigma^{-1})}$, because:
$$
A_G \cdot v = \sum_{\sigma \in S_t} v_{\sigma} A_G \cdot \sigma = \sum_{\sigma \in S_t} v_{\sigma}\sum_{\pi \in S_t} d^{c(\pi)} \pi \cdot \sigma = \sum_{\sigma \in S_t} v_{\sigma}\sum_{\tau \in S_t} d^{c(\tau \sigma^{-1})} \tau = \sum_{\tau \in S_t}\left(\sum_{\sigma}(A_G)_{\tau,\sigma}v_\sigma\right) \tau.
$$
Therefore, it is enough to find the group inverse of $A_G$ (denoted as $A_{G^{-1}}$), and then represent it on the same basis, which gives $A_{G^{-1}} = \sum_{\pi\in S_t}f(\pi)\cdot\pi$，其矩阵表示为 $(A_{G^{-1}})_{\tau,\sigma}= f(\tau\sigma^{-1})$。
By the definition, we get the result:
$$
A_G A_{G^{-1}} = e \Rightarrow \sum_{\pi,\sigma}d^{c(\pi)}f(\sigma)\pi \sigma = e \Rightarrow \sum_{\sigma} f(\sigma) d^{c(r\sigma^{-1})} = \sum_{\sigma} f(\sigma) G_{r, \sigma}= \sum_{\sigma}  G_{r,\sigma} f(\sigma)=  \delta_{e,r}
$$
This means that $f(\sigma) = \mathrm{Wg}_{\sigma,e}(d)$ and $\mathrm{Wg}(\sigma \pi^{-1},d) = f(\sigma \pi^{-1})$.

Noted that $g A_G g^{-1} = A_G$ because the cyclic structure of $\pi$ is invariant under group conjugation, we conclude that $[A_G,g] = 0,\forall g \in S_t$. According to Schur's Lemma, all irreducible representations of $A_G$ must be proportional to the unit element. That is:
$$
\hat{A}_G(\lambda) = \sum_{\pi \in S_t}d^{c(\pi)} \hat{R}_{\lambda}(\pi) =  \eta_{\lambda} \cdot \mathbb{I}_{\text{dim}(\lambda)} \Rightarrow \eta_{\lambda} = \sum_{\pi \in S_t} d^{c(\pi)} \chi_{\lambda}(\pi)/\text{dim} \lambda.
$$
Based on Lemma \ref{lemma:projector_in_lambda}，we conclude that $\text{tr}(P_{\lambda}) = \left({\text{dim} \lambda}/{t!}\right) \sum_{\pi \in S_t} \chi_{\lambda}(\pi) d^{c(\pi)} = \text{dim}_d \lambda$。This gives the identity $\eta_{\lambda} = t!\cdot {\text{dim}_d \lambda}/{(\text{dim}\lambda)^2} = t!\cdot {\text{dim}_U \lambda}/{\text{dim}\lambda}$.

Noted that $\text{dim}_U \lambda= \prod_{(i,j) \in \lambda}(d+j-i)/h(i,j)$, according to Lemma \ref{lemma:irreps_GLd}. If the longest row of the Young tableaux $\lambda$ satisfies $\ell_m(\lambda)>d$, then the value is zero.
This shows the non-invertible property of $\hat{A}_{G}$, therefore $A_G$ is also non-invertible. We can find the right pseudo-inverse $\hat A_{G^{-1}}$ by setting $\eta_{\lambda}^{-1} = 0$ if $\eta_{\lambda} =0$.
This determines the irreducible representations of $A_{G^{-1}}$ as:
$$
\hat{A}_{G^{-1}}(\lambda)= \begin{cases}\left[(\text{dim}\lambda)/\left(t!\cdot \text{dim}_U \lambda\right)\right]\cdot \mathbb{I}_{\text{dim}(\lambda)} &\text{if~}\ell_m(\lambda)\leq d\\ 0&\text{if~}\ell_m(\lambda)>d\end{cases}
$$
Knowing the irreducible representations of $A_{G^{-1}}$, according to Lemma \ref{lemma:inv_groupFourier} we can determine the coefficients:
$$
\begin{aligned}
    f(\pi) &= \frac{1}{t!} \sum_{\lambda \vdash t} \text{dim}(\lambda) \text{tr}\left( \hat{A}_{G^{-1}}(\lambda) \hat R_\lambda(\pi) \right) = \frac{1}{t!} \sum_{\substack{\lambda \vdash t, \ell_m(\lambda)\leq d}} \text{dim}(\lambda) \text{tr}\left( \frac{\text{dim}(\lambda)}{t! \cdot \text{dim}_U(\lambda)}  \hat{R}_\lambda(\pi) \right) \\
    & = \frac{1}{(t!)^2} \sum_{\substack{\lambda \vdash t, \ell_m(\lambda)\leq d}}  \frac{(\text{dim}(\lambda))^2 \chi^\lambda(\pi)}{\text{dim}_U(\lambda)}.
\end{aligned}
$$
:::


### Examples

In the case of $t = 2, d\geq 2$, we get two types of permutations $e, (12)$, where $\text{dim}_U([1^2]) ={d(d-1)}/{2}, \text{dim}_U([2]) = {d(d+1)}/{2}$ and $\text{dim}([1^2]) = 1 =\text{dim}([2])$. Based on the character table of $S_2$, we list the Weingarten coefficients as follows:

::: {.columns}
::: {.column width="30%"}
**The character table of $S_2$**

| C.C. | $[1^2]$ | $[2]$ |
| :---: | :---: | :---: |
| **Size** | 1 | 1 |
| $\chi_{[2]}$ | 1 | 1 |
| $\chi_{[1^2]}$ | 1 | -1 |
:::

::: {.column width="70%"}
$$
\begin{aligned}
\mathrm{Wg}(e, d) &= \frac{1}{(2!)^2} \left[ \frac{(\chi_{[2]}(e))^2 \chi_{[2]}(e)}{\text{dim}_U([2])} + \frac{(\chi_{[1,1]}(e))^2 \chi_{[1,1]}(e)}{\text{dim}_U([1,1])} \right] \\
&= \frac{1}{d^2-1}, \\
\mathrm{Wg}((12), d) &= \frac{1}{(2!)^2} \left[ \frac{(\chi_{[2]}(e))^2 \chi_{[2]}((12))}{\text{dim}_U([2])} + \frac{(\chi_{[1,1]}(e))^2 \chi_{[1,1]}((12))}{\text{dim}_U([1,1])} \right] \\
&=(-\frac{1}{d})\cdot \frac{1}{d^2-1}.
\end{aligned}
$$
:::
:::

In the case of $t = 3, d\geq 3$, there are three conjugacy classes corresponding to the cyclic types $[1^3], [2,1]$ and $[3]$. The dimensions of the required irreducible representations (irreps) are:
$$
\begin{aligned}
    \dim_U([3]) &= \frac{d(d-1)(d-2)}{6}, \dim_S([3]) = 1 \\
    \dim_U([2,1]) &= \frac{d(d^2-1)}{3},  \dim_S([2,1]) = 2 \\
    \dim_U([1^3]) &= \frac{d(d+1)(d+2)}{6} , \dim_S([1^3]) = 1
\end{aligned}
$$

Based on the character table of $S_3$, we list the Weingarten coefficients as follows:

::: {.columns}
::: {.column width="30%"}
**The character table of $S_3$**

| C.C. | $[1^3]$ | $[2,1]$ | $[3]$ |
| :---: | :---: | :---: | :---: |
| **Size** | 1 | 3 | 2 |
| $\chi_{[1^3]}$ | 1 | 1 | 1 |
| $\chi_{[2,1]}$ | 2 | 0 | -1 |
| $\chi_{[3]}$ | 1 | -1 | 1 |
:::

::: {.column width="70%"}
$$
\begin{aligned}
\mathrm{Wg}(e, d) &= \frac{1}{(3!)^2} \left[ \frac{1^2 \cdot 1}{\dim_U([3])} + \frac{2^2 \cdot 2}{\dim_U([2,1])} + \frac{1^2 \cdot 1}{\dim_U([1^3])} \right] \\
&= \frac{d^2-2}{d(d^2-1)(d^2-4)}, \\[1em]
\mathrm{Wg}((12), d) &= \frac{1}{(3!)^2} \left[ \frac{1^2 \cdot (-1)}{\dim_U([3])} + \frac{2^2 \cdot 0}{\dim_U([2,1])} + \frac{1^2 \cdot 1}{\dim_U([1^3])} \right] \\
&= \frac{-1}{(d^2-1)(d^2-4)}, \\[1em]
\mathrm{Wg}((123), d) &= \frac{1}{(3!)^2} \left[ \frac{1^2 \cdot 1}{\dim_U([3])} + \frac{2^2 \cdot (-1)}{\dim_U([2,1])} + \frac{1^2 \cdot 1}{\dim_U([1^3])} \right] \\
&= \frac{2}{d(d^2-1)(d^2-4)}.
\end{aligned}
$$
:::
:::

In the case of $t = 3, d=2$, since $\dim_U([3])=0$, we need to find the pseudo-inverse. This eliminates the Young tableaux $\lambda = [3]$ and gives the following results:
$$
\mathrm{Wg}(e, d) = \frac{17}{144},\quad \mathrm{Wg}((12), d) =\frac{1}{144},\quad \mathrm{Wg}((123), d)=-\frac{7}{144}
$$

In the case of $X = \ket{\psi}\!\bra{\psi}^{\otimes t}$, we choose the result that can unify the cases of $k>d$ and $k<d$.

::: {.callout-note icon="false"}
## Lemma (Unitary orbit of $\ket{\psi}$) {#lemma:state_trajectory}

$$
\mathbb{E}_{\psi \sim \mathrm{Haar}(d)} \ket{\psi}\!\bra{\psi}^{\otimes t} =  \frac{\sum_{\pi \in S_t} S_t(d)}{(t+d-1)(t+d-2)\cdots(d-1) d},
$$
where $S_t(d) = \sum_{\pi \in S_t} \mathbb{P}^d_\pi$. If $t \leq d$, then this decomposition is unique.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)


According to Lemma \ref{lemma:Haar_ave}, we conclude that $\forall \rho \in S_t$:
$$
\sum_{\pi \in S_t}\text{Tr}(\mathbb{P}_{\rho^{-1}}^d \mathbb{P}_\pi^d) \, c_\pi = \text{Tr}(\mathbb{P}^d_{\rho^{-1}} X) =1
$$
We first assume that the operator $c_{\pi}$ is independent of $\pi$, which gives the solution for $c_\pi$ as follows:
$$
\text{Tr}\left(\sum_{\pi \in S_t} \mathbb{P}^d_{\rho^{-1}\pi} \right)c =  \text{Tr}\left(\sum_{\pi \in S_t} \mathbb{P}^d_{\pi} \right)c=1.
$$
$c_\pi = c$ is one of the solutions to the linear equation.
To prove that this solution is unique, we use the fact that $G_{\pi, \sigma} := \text{Tr}(\mathbb{P}_{\pi^{-1}}^d \mathbb{P}_\sigma^d)$ is an invertible matrix.
Noted that $(t!)^{-1}\sum_{\pi \in S_t} \mathbb{P}^d_{\pi}$ is the projector to the $t$-fold symmetric space, whose dimension is $C_{t+d-1}^t$ (i.e., the number of ways to put $t$ objects into $d$ bins). This gives the result:
$$
\text{Tr}\left(\sum_{\pi \in S_t} \mathbb{P}^d_{\pi} \right) = (t!)C_{t+d-1}^t = (t+d-1)(t+d-2)\cdots(d-1) d.
$$
:::

::: {.callout-note icon="false"}
## Lemma (n-fold Weingarten calculus) {#lemma:2-foldWein}

Given independent and identically distributed (i.i.d.) $V_i \sim \text{Haar}(d), i = 1,\cdots,n$, $X \in \text{Lin}(\mathcal{H}(d^{kn}))$, and define $B_{\mathbf{v}}:= \bigotimes_{i =1}^{n} \left(\mathbb{P}_{v_i}^{d}\right)$ where $\mathbf{v} = (v_1,\cdots,v_n) \in S_k^n$, the following identity holds:
$$
\Phi_k^{\otimes n}(X):= \mathbb{E}_{V_i \sim \text{Haar}(d)} \left(\bigotimes_{i=1}^n V_i^{\otimes k}\right) X \left(\bigotimes_{i=1}^n V_i^{\dagger\,\otimes k}\right) = \sum_{\mathbf u, \mathbf{v} \in \mathbb{F}_2^n} \text{Wg}^{n}(\mathbf{v}\mathbf{u}^{-1}, d)  \text{tr}\left( B_{\mathbf{u}} X\right)\cdot  B_{\mathbf{v}},
$$
The product Weingarten coefficients are determined by $\sum_{\mathbf{v}} \text{Wg}^{n}(\mathbf{v}\mathbf{u}^{-1}, d) \text{tr}\left(B_{\mathbf{u}}B_{\mathbf{r}}^\dagger\right) = \delta_{\mathbf{v},\mathbf{r}}$ and their analytic expression is $\mathrm{Wg}^{n}(\mathbf{v}\mathbf{u}^{-1}, d) = \prod_{i=1}^n\mathrm{Wg}({v}_i{u}_i^{-1}, d)$. Specifically:

For all $\mathbf u,\mathbf v \in S_2^n$:
$$
\mathrm{Wg}^{n}(\mathbf{v}\mathbf{u}^{-1}, d) = \left(\frac{1}{d^2 -1}\right)^n \cdot \left(-\frac{1}{d}\right)^{|\mathbf{v}\mathbf{u}^{-1}|},\text{~其中~}|\mathbf{v}\mathbf{u}^{-1}| = \#\{i|v_i \neq u_i\}
$$

For all $\mathbf u,\mathbf v \in S_3^n$:
$$
\mathrm{Wg}^{n}(\mathbf{v}\mathbf{u}^{-1}, d) = \left(\frac{d^2-2}{d(d^2 -1)(d^2-4)}\right)^n \cdot \left(\frac{-d}{d^2-2}\right)^{\#\{i|v_i u_i^{-1} \in [21]\}}\left( \frac{2}{d^2-2}\right)^{\#\{i|v_i u_i^{-1} \in [3]\}}
$$
:::

## Applications
::: {.callout-note icon="false"}
## Lemma (Multi-layer Haar average)

:::
Let $U_{AB}$ and $U_{BC}$ be two unitary operators supported on different systems, consider the unitary ensemble $\{V_{ABC}= U_{AB}U_{BC}\}_{U \sim \mathrm{Haar}}$.
We have:
$$
\begin{aligned}
\Phi_{\mathcal{E}^*}(X) &= \mathbb{E}_{U_{AB}} \left[ U_{AB}^{\otimes k} \left( \mathbb{E}_{U_{BC}} \left[ U_{BC}^{\otimes k} X U_{BC}^{\dagger \otimes k} \right] \right) U_{AB}^{\dagger \otimes k} \right]\\
&= \mathbb{E}_{U_{AB}} \left[ U_{AB}^{\otimes k} \left(\sum_{\sigma, \tau} \text{Wg}_{BC}(\sigma\tau^{-1}) \cdot \text{Tr}_{BC}\left( X (I_A \otimes \sigma_{BC}^{-1}) \right) \otimes \tau_{B} \otimes \tau_{C}\right) U_{AB}^{\dagger \otimes k} \right]\\
&= \sum_{\sigma, \tau} \text{Wg}_{BC}(\sigma\tau^{-1}) \cdot \mathbb{E}_{U_{AB}} \left[ U_{AB}^{\otimes k} \left(\text{Tr}_{BC}\left( X (I_A \otimes \sigma_{BC}^{-1}) \right) \otimes \tau_{B} \right) U_{AB}^{\dagger \otimes k} \right]\otimes \tau_{C}\\
&\hspace{-3em}\mathbb{E}_{U_{AB}} \left[ U_{AB}^{\otimes k} \left(\text{Tr}_{BC}\left( X (I_A \otimes \sigma_{BC}^{-1}) \right) \otimes \tau_{B} \right) U_{AB}^{\dagger \otimes k} \right]\\
&= \sum_{\tilde{\sigma}, \tilde{\tau}} \text{Wg}_{AB}(\tilde{\sigma}\tilde{\tau}^{-1}) \cdot \text{Tr}_{AB}\left[ \left(\text{Tr}_{BC}\left( X (I_A \otimes \sigma_{BC}^{-1}) \right) \otimes \tau_{B} \right)  \tilde{\sigma}_{AB}^{-1} \right] \cdot \tilde{\tau}_{AB}\\
&\hspace{-3em}\text{Tr}_{AB}\left[ \left(\text{Tr}_{BC}\left( X (I_A \otimes \sigma_{BC}^{-1}) \right) \otimes \tau_{B} \right)  \tilde{\sigma}_{AB}^{-1} \right]\\
&=
\end{aligned}
$$