---
title: "Estimate Tr[Oρ²] via local 2-replica protocol"
date: 2026-02-02
categories: [issue]
status: "Open"
css: styles.css
number: 3
---

::: {.issue-container}
::: {.issue-title-section}
# [🔓 Open]{.status-open} Estimate $\mathrm{Tr}[O\rho^2]$ via local 2-replica protocol [#3]{.issue-number}

::: {.issue-meta}
[theory]{.label .label-bug} [enhancement]{.label .label-enhancement}
:::
:::

::: {.post-body}
## Problem Statement

For a **fixed** observable $O = \sum_{\alpha_i} P_i$ as a linear combinaition of Pauli operators, design a local 2-replica protocol to estimate $\mathrm{Tr}[O\rho^2]$.

1. We already know how to estimate $\mathrm{Tr}[P\rho^2]$ for a single Pauli $P$ using [local 2-replica 3-design measurements](/theory/Topics/Shadow_tomography/3desgin_multi_local_shadow.qmd) that gives efficiency upper bound $(13/3)^(n - \mathrm{wt}(P)) (5/3)^{\mathrm{wt}(P)}$ for single Pauli $P$.

2. We also proposed a [entanglement fixed method](/theory/Topics/Shadow_tomography/multicopy.qmd) by scrambing Bell measurement with local Clfford gates. But still not gives a thorough understanding of the complexity.

3. All these results are still target on single Pauli $P$ case. The goal is to **generalize** this to arbitrary observables $O$ (not necessarily Pauli). to do this, I already review how this generalization is done in the $k=1$ case in estimating $\mathrm{Tr}[P\rho]$ in [Local estimation strategies](/theory/Posts/Estimation/index.qmd).

:::
:::


::: {.issue-post}
::: {.post-header}
::: {.post-author}
**Chance** documented on Feb 3, 2026
:::
:::

::: {.post-body}
To solve problem 3, we need a more detailed reproduction of all previous algorithm in this [section](/theory/Posts/Estimation/index.qmd#sec-derandomized-methods).
The most promising one is the derandomized algorithm in [Derandomized local shadows](/theory/Posts/Pauli_derandomization/index.qmd).
:::
:::

## Comments
<!-- COMMENTS-START -->
{{< include ../../comments/Multi-shadow/issues/issue3.md >}}
<!-- COMMENTS-END -->

