#!/usr/bin/env python3
"""Generate note indexes and Quarto sidebars for theory and experiment notes.

The generator is deliberately conservative around prose:
- missing topic indexes are created;
- existing indexes only receive or replace the marked notes table block;
- ``_metadata.yml`` files are updated with the generated sidebar id;
- only the generated sidebar block in ``_quarto.yml`` is rewritten.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
import os
from pathlib import Path
import re
import subprocess
from typing import Any, Iterable

try:
    import yaml
except ImportError:  # pragma: no cover - Quarto uses .venv where PyYAML exists.
    yaml = None


ROOT = Path(__file__).resolve().parents[1]
QUARTO_YML = ROOT / "_quarto.yml"
SKIP_NAV_ENV = "QUARTO_SKIP_NAV"

AUTO_SIDEBARS_BEGIN = "    # BEGIN AUTO NOTE SIDEBARS"
AUTO_SIDEBARS_END = "    # END AUTO NOTE SIDEBARS"
OLD_AUTO_SIDEBARS_BEGIN = "    # BEGIN AUTO THEORY SIDEBARS"
OLD_AUTO_SIDEBARS_END = "    # END AUTO THEORY SIDEBARS"

NOTES_TABLE_BEGIN = "<!-- BEGIN AUTO NOTES TABLE -->"
NOTES_TABLE_END = "<!-- END AUTO NOTES TABLE -->"
OLD_GENERATED_INDEX_MARKER = "<!-- AUTO-GENERATED BY scripts/update_theory_nav.py -->"

VALID_STATUSES = {"stable", "draft", "rough"}
DEFAULT_STATUS = "draft"
DEFAULT_DESCRIPTION = "TODO: add description"

IGNORED_DIR_NAMES = {
    ".ipynb_checkpoints",
    "__pycache__",
    "_freeze",
    "_site",
    "assets",
    "cache",
    "figures",
    "mediabag",
    "site_libs",
}

TITLE_OVERRIDES = {
    "theory/quantum_complexity/Boolean_ana": "Boolean Analysis",
    "theory/Condensed_matter": "Condensed Matter",
    "theory/Factoring": "Factoring and Hidden Subgroup Problems",
    "theory/Condensed_matter/Fermi-Hubbard": "Fermi-Hubbard Model",
    "theory/Fingerprint": "Quantum Fingerprinting",
    "theory/Ham_learning": "Hamiltonian Learning",
    "theory/LGT": "Lattice Gauge Theory",
    "theory/Magic": "Magic and Stabilizer Resources",
    "theory/Noisy_complexity": "Classical Simulation of Noisy Quantum Circuits",
    "theory/Nonlocal_Games_Survey": (
        "Scalable Quantum Non-Locality: Architectures, Noise Resilience, and Experimental Frontiers"
    ),
    "theory/OSF": "Generalized Stabilizer Formalism",
    "theory/Dynamics": "Perturbation and Floquet Theory",
    "theory/QEC": "Quantum Error Correction",
    "theory/learning_theo/Shadow_tomography": "Classical Shadow Tomography",
    "theory/Condensed_matter/TFIM": "Spin Liquids",
    "theory/TN_sim": "Tensor Network Simulation",
    "theory/learning_theo/Virtual_Distillation": "Virtual Distillation for Quantum Error Mitigation",
    "theory/compatibility": "Quantum Resource",
    "theory/drugs_design": (
        "Leveraging Analog Quantum Computing with Neutral Atoms for Solvent Configuration Prediction "
        "in Drug Discovery"
    ),
    "theory/learning_theo": "Learning Theory and Quantum Learning",
    "theory/learning_theo/Lowerbounds": "Lower Bounds Toolbox",
    "theory/learning_theo/weak_schur": "Weak Schur Tools",
    "theory/quantum_complexity": "Quantum Complexity",
    "theory/stab_simulation": "Stabilizer Simulation",
    "theory/quantum_complexity/supermacy": "IQP Circuit Supremacy",
    "theory/quantum_complexity/supermacy/IQPs": "IQP Circuits",
    "theory/quantum_complexity/supermacy/IQPs/simulations": "IQP Simulation Algorithms",
    "theory/Condensed_matter/topo_matter": "Topological Matter",
    "Experiments/posts/simulation_model": "Analog Rydberg Quantum Simulation",
    "Experiments/posts/rydberg_qc": "Rydberg Atoms for Fault-Tolerant QC",
}

SIDEBAR_ID_OVERRIDES = {
    "theory/Condensed_matter": "condensed_matter",
    "theory/Condensed_matter/Fermi-Hubbard": "fermi_hubbard",
    "theory/Condensed_matter/TFIM": "spin_liquid",
    "theory/Condensed_matter/topo_matter": "topo_matter",
    "theory/Dynamics": "perturbation",
    "theory/learning_theo": "learning_theory",
    "theory/learning_theo/Lowerbounds": "lowerbounds",
    "theory/learning_theo/Shadow_tomography": "shadow_tomography",
    "theory/learning_theo/Virtual_Distillation": "virtual_distillation",
    "theory/quantum_complexity/Boolean_ana": "boolean_ana",
    "theory/quantum_complexity/supermacy": "iqp",
    "theory/quantum_complexity/supermacy/IQPs": "theory_supermacy_iqps",
    "theory/quantum_complexity/supermacy/IQPs/simulations": (
        "theory_supermacy_iqps_simulations"
    ),
    "Experiments/posts/simulation_model": "simulation_model",
    "Experiments/posts/rydberg_qc": "rydberg_qc",
}


@dataclass(frozen=True)
class Section:
    name: str
    root: Path
    overview: Path
    overview_begin: str
    overview_end: str
    top_level_only: bool


SECTIONS = [
    Section(
        name="theory",
        root=ROOT / "theory",
        overview=ROOT / "theory" / "index.qmd",
        overview_begin="<!-- BEGIN AUTO THEORY TOPICS -->",
        overview_end="<!-- END AUTO THEORY TOPICS -->",
        top_level_only=True,
    ),
    Section(
        name="Experiments",
        root=ROOT / "Experiments",
        overview=ROOT / "Experiments" / "index.qmd",
        overview_begin="<!-- BEGIN AUTO EXPERIMENT TOPICS -->",
        overview_end="<!-- END AUTO EXPERIMENT TOPICS -->",
        top_level_only=False,
    ),
]


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8", errors="ignore") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def rel_to_section(path: Path, section: Section) -> str:
    return path.relative_to(section.root).as_posix()


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def nice_title(value: str) -> str:
    words = value.replace("_", " ").replace("-", " ").split()
    return " ".join(word.upper() if word.lower() in {"iqp", "slm", "cz"} else word.title() for word in words)


def yaml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def scalar_to_string(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (date, datetime)):
        return value.date().isoformat() if isinstance(value, datetime) else value.isoformat()
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return ", ".join(scalar_to_string(item) for item in value)
    return str(value).strip()


def split_frontmatter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"):
        return "", text
    match = re.match(r"(?s)^---\s*\n(.*?)\n---\s*(?:\n|$)(.*)$", text)
    if not match:
        return "", text
    return match.group(1), match.group(2)


def simple_frontmatter(raw: str) -> dict[str, Any]:
    data: dict[str, Any] = {}
    for line in raw.splitlines():
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.+?)\s*$", line)
        if match:
            data[match.group(1)] = match.group(2).strip().strip("\"'")
    return data


def frontmatter(path: Path) -> dict[str, Any]:
    raw, _ = split_frontmatter(path)
    if not raw:
        return {}
    if yaml is None:
        return simple_frontmatter(raw)
    try:
        data = yaml.safe_load(raw) or {}
    except Exception:
        return simple_frontmatter(raw)
    return data if isinstance(data, dict) else {}


def meta_string(path: Path, key: str) -> str:
    return scalar_to_string(frontmatter(path).get(key))


def qmd_title(path: Path) -> str:
    title = meta_string(path, "title")
    return title or nice_title(path.stem)


def qmd_order(path: Path) -> tuple[float, str, str]:
    raw = meta_string(path, "order")
    try:
        order = float(raw) if raw else float("inf")
    except ValueError:
        order = float("inf")
    return (order, qmd_title(path).lower(), path.as_posix().lower())


def is_ignored_dir(path: Path) -> bool:
    return (
        path.name.startswith(".")
        or path.name.startswith("_")
        or path.name.lower() in IGNORED_DIR_NAMES
        or path.name.endswith("_files")
    )


def has_ignored_part(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts
    except ValueError:
        return True
    return any(
        part.startswith(".")
        or part.startswith("_")
        or part.lower() in IGNORED_DIR_NAMES
        or part.endswith("_files")
        for part in parts
    )


def qmd_files(directory: Path) -> list[Path]:
    return sorted(directory.glob("*.qmd"), key=qmd_order)


def note_pages(directory: Path) -> list[Path]:
    return [path for path in qmd_files(directory) if path.name != "index.qmd"]


def all_qmds(directory: Path, root: Path) -> list[Path]:
    paths = [
        path
        for path in directory.rglob("*.qmd")
        if not has_ignored_part(path.parent, root)
    ]
    return sorted(paths, key=lambda path: (path.parent.as_posix().lower(), path.name != "index.qmd", *qmd_order(path)))


def topic_dirs(section: Section) -> list[Path]:
    dirs: list[Path] = []
    for path in section.root.rglob("*"):
        if not path.is_dir() or path == section.root or has_ignored_part(path, section.root):
            continue
        if qmd_files(path):
            dirs.append(path)
    return sorted(dirs, key=lambda path: (path.relative_to(section.root).parts, topic_title(path).lower()))


def overview_topic_dirs(section: Section, topics: Iterable[Path]) -> list[Path]:
    if not section.top_level_only:
        return sorted(topics, key=lambda path: topic_title(path).lower())
    return sorted(
        [path for path in topics if len(path.relative_to(section.root).parts) == 1],
        key=lambda path: topic_title(path).lower(),
    )


def topic_title(topic_dir: Path) -> str:
    relative = rel(topic_dir)
    if relative in TITLE_OVERRIDES:
        return TITLE_OVERRIDES[relative]
    index = topic_dir / "index.qmd"
    if index.exists():
        title = meta_string(index, "title")
        if title:
            return title
    return nice_title(topic_dir.name)


def existing_sidebar_id(topic_dir: Path) -> str:
    metadata = topic_dir / "_metadata.yml"
    if not metadata.exists():
        return ""
    for line in metadata.read_text(encoding="utf-8", errors="ignore").splitlines():
        match = re.match(r"^sidebar:\s*(\S+)\s*$", line)
        if match:
            return match.group(1).strip("\"'")
    return ""


def sidebar_id(topic_dir: Path) -> str:
    relative = rel(topic_dir)
    return existing_sidebar_id(topic_dir) or SIDEBAR_ID_OVERRIDES.get(relative) or slug(relative)


def normalize_status(value: str) -> str:
    status = value.strip().lower()
    return status if status in VALID_STATUSES else DEFAULT_STATUS


def git_last_commit_date(path: Path) -> str:
    try:
        completed = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel(path)],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return ""
    return completed.stdout.strip()


def note_status(path: Path) -> str:
    return normalize_status(meta_string(path, "status"))


def note_updated(path: Path) -> str:
    return meta_string(path, "updated") or meta_string(path, "date") or git_last_commit_date(path)


def note_description(path: Path) -> str:
    return meta_string(path, "description") or DEFAULT_DESCRIPTION


def topic_description(topic_dir: Path, title: str) -> str:
    index = topic_dir / "index.qmd"
    if index.exists():
        existing = meta_string(index, "description")
        if existing:
            return existing
    return f"Notes in the {title} topic directory."


def markdown_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ").strip()


def markdown_link_label(value: str) -> str:
    return markdown_cell(value).replace("[", r"\[").replace("]", r"\]")


def build_notes_table(topic_dir: Path) -> str:
    lines = [
        NOTES_TABLE_BEGIN,
        "",
        "| Note | Status | Updated | Description |",
        "|---|---|---|---|",
    ]
    for path in note_pages(topic_dir):
        href = path.relative_to(topic_dir).as_posix()
        lines.append(
            "| "
            f"[{markdown_link_label(qmd_title(path))}]({href})"
            f" | {markdown_cell(note_status(path))}"
            f" | {markdown_cell(note_updated(path))}"
            f" | {markdown_cell(note_description(path))} |"
        )
    lines.extend(["", NOTES_TABLE_END])
    return "\n".join(lines)


def replace_or_append_block(text: str, begin: str, end: str, block: str) -> str:
    pattern = re.compile(rf"(?ms){re.escape(begin)}.*?{re.escape(end)}")
    if pattern.search(text):
        return pattern.sub(lambda _match: block, text)
    return text.rstrip() + "\n\n" + block + "\n"


def generated_index_text(topic_dir: Path, title: str) -> str:
    description = topic_description(topic_dir, title)
    return "\n".join(
        [
            "---",
            "categories:",
            "- Index",
            "lang: en",
            f"title: {yaml_string(title)}",
            f"description: {yaml_string(description)}",
            "---",
            "",
            f"# {title}",
            "",
            build_notes_table(topic_dir),
            "",
        ]
    )


def ensure_topic_index(topic_dir: Path) -> None:
    title = topic_title(topic_dir)
    index = topic_dir / "index.qmd"
    if not index.exists():
        write_if_changed(index, generated_index_text(topic_dir, title))
        return

    text = index.read_text(encoding="utf-8", errors="ignore")
    if OLD_GENERATED_INDEX_MARKER in text and NOTES_TABLE_BEGIN not in text:
        write_if_changed(index, generated_index_text(topic_dir, title))
        return

    table = build_notes_table(topic_dir)
    write_if_changed(index, replace_or_append_block(text, NOTES_TABLE_BEGIN, NOTES_TABLE_END, table))


def set_sidebar_metadata(path: Path, sid: str) -> None:
    current = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""
    lines = current.splitlines()
    replaced = False
    for index, line in enumerate(lines):
        if re.match(r"^sidebar:\s*", line):
            lines[index] = f"sidebar: {sid}"
            replaced = True
            break
    if not replaced:
        lines.insert(0, f"sidebar: {sid}")
    write_if_changed(path, "\n".join(lines).rstrip() + "\n")


def section_title(directory: Path) -> str:
    return topic_title(directory) if (directory / "index.qmd").exists() else nice_title(directory.name)


def sidebar_subdirs(directory: Path, section: Section) -> list[Path]:
    subdirs = [
        path
        for path in directory.iterdir()
        if path.is_dir()
        and not has_ignored_part(path, section.root)
        and all_qmds(path, section.root)
    ]
    return sorted(subdirs, key=lambda path: section_title(path).lower())


def append_sidebar_contents(
    lines: list[str], directory: Path, section: Section, indent: str, group_direct_notes: bool
) -> None:
    index = directory / "index.qmd"
    if index.exists():
        lines.append(f"{indent}- {rel(index)}")

    direct_notes = note_pages(directory)
    if direct_notes and group_direct_notes:
        lines.append(f'{indent}- section: "Notes"')
        lines.append(f"{indent}  contents:")
        for path in direct_notes:
            lines.append(f"{indent}    - {rel(path)}")
    else:
        for path in direct_notes:
            lines.append(f"{indent}- {rel(path)}")

    for subdir in sidebar_subdirs(directory, section):
        lines.append(f"{indent}- section: {yaml_string(section_title(subdir))}")
        lines.append(f"{indent}  contents:")
        append_sidebar_contents(lines, subdir, section, indent + "    ", False)


def build_sidebar_block(topic_dir: Path, section: Section, sid: str, title: str) -> str:
    lines = [f"id: {sid}", f"title: {yaml_string(title)}", "contents:"]
    append_sidebar_contents(lines, topic_dir, section, "  ", True)
    return "\n".join(lines) + "\n"


def should_write_sidebar_file(topic_dir: Path, section: Section) -> bool:
    for parent in topic_dir.relative_to(section.root).parents:
        if parent == Path("."):
            continue
        if qmd_files(section.root / parent):
            return False
    return True


def build_overview_table(section: Section, topics: Iterable[Path]) -> str:
    lines = [
        section.overview_begin,
        "",
        "| Topic | Description |",
        "|---|---|",
    ]
    for topic_dir in topics:
        index = topic_dir / "index.qmd"
        if not index.exists():
            continue
        title = qmd_title(index)
        description = topic_description(topic_dir, title)
        href = f"{rel_to_section(index, section)}"
        lines.append(f"| [{markdown_link_label(title)}]({href}) | {markdown_cell(description)} |")
    lines.extend(["", section.overview_end])
    return "\n".join(lines)


def rewrite_overview(section: Section, topics: Iterable[Path]) -> None:
    text = section.overview.read_text(encoding="utf-8", errors="ignore")
    block = build_overview_table(section, topics)
    updated = replace_or_append_block(text, section.overview_begin, section.overview_end, block)
    write_if_changed(section.overview, updated)


def remove_marked_sidebar_blocks(sidebar_body: str) -> str:
    text = sidebar_body
    for begin, end in [
        (AUTO_SIDEBARS_BEGIN, AUTO_SIDEBARS_END),
        (OLD_AUTO_SIDEBARS_BEGIN, OLD_AUTO_SIDEBARS_END),
    ]:
        pattern = re.compile(rf"(?ms)^{re.escape(begin)}\n.*?^{re.escape(end)}\n?")
        text = pattern.sub("", text)
    return text


def split_sidebar_blocks(sidebar_body: str) -> list[str]:
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in sidebar_body.splitlines():
        if line.startswith("    - id:"):
            if current:
                blocks.append(current)
            current = [line]
        elif current:
            current.append(line)
    if current:
        blocks.append(current)
    return ["\n".join(block).rstrip() + "\n" for block in blocks]


def block_id(block: str) -> str | None:
    first = block.splitlines()[0] if block.splitlines() else ""
    match = re.match(r"\s*-\s*id:\s*(\S+)", first)
    return match.group(1) if match else None


def indent_sidebar_block(block: str) -> str:
    out: list[str] = []
    for index, line in enumerate(block.rstrip().splitlines()):
        out.append(("    - " if index == 0 else "      ") + line)
    return "\n".join(out) + "\n"


def rewrite_quarto_sidebar(blocks: list[str], generated_ids: set[str]) -> None:
    text = QUARTO_YML.read_text(encoding="utf-8", errors="ignore")

    start = text.find("\n  sidebar:\n")
    end = text.find("\nformat:", start)
    if start == -1 or end == -1:
        raise RuntimeError("Could not find website.sidebar block in _quarto.yml")

    sidebar_header = "\n  sidebar:\n"
    existing_body = text[start + len(sidebar_header) : end]
    existing_body = remove_marked_sidebar_blocks(existing_body)
    kept_blocks = [
        block for block in split_sidebar_blocks(existing_body) if block_id(block) not in generated_ids
    ]

    generated = (
        AUTO_SIDEBARS_BEGIN
        + "\n"
        + "".join(indent_sidebar_block(block) for block in blocks)
        + AUTO_SIDEBARS_END
        + "\n"
    )
    replacement = sidebar_header + generated + "".join(kept_blocks)
    text = text[:start] + replacement + text[end:]
    write_if_changed(QUARTO_YML, text)


def should_skip_generation() -> bool:
    skip_value = os.environ.get(SKIP_NAV_ENV, "").strip().lower()
    if skip_value in {"1", "true", "yes", "on"}:
        return True
    profiles = re.split(r"[ ,]+", os.environ.get("QUARTO_PROFILE", "").strip())
    return "fast" in profiles


def main() -> None:
    if should_skip_generation():
        return

    blocks: list[str] = []
    generated_ids: set[str] = set()

    for section in SECTIONS:
        topics = topic_dirs(section)
        for topic_dir in topics:
            ensure_topic_index(topic_dir)

        for topic_dir in topics:
            title = topic_title(topic_dir)
            sid = sidebar_id(topic_dir)
            block = build_sidebar_block(topic_dir, section, sid, title)
            if should_write_sidebar_file(topic_dir, section):
                set_sidebar_metadata(topic_dir / "_metadata.yml", sid)
                write_if_changed(topic_dir / "_sidebar.yml", block)
            blocks.append(block)
            generated_ids.add(sid)

        rewrite_overview(section, overview_topic_dirs(section, topics))

    blocks.sort(key=lambda block: (re.search(r'title:\s+"(.*?)"', block) or re.search(r"title:\s*(.*)", block)).group(1).lower())
    rewrite_quarto_sidebar(blocks, generated_ids)


if __name__ == "__main__":
    main()
