#!/usr/bin/env python3
"""Update theory topic indexes and Quarto sidebars.

This script is intentionally conservative:
- it scans only top-level directories under ``theory/``;
- it creates missing topic ``index.qmd`` pages, but does not overwrite
  hand-written indexes unless they contain the auto-generated marker;
- it updates ``_metadata.yml`` sidebar assignments for each topic;
- it rewrites only the auto-generated theory sidebar block in ``_quarto.yml``.
"""

from __future__ import annotations

from pathlib import Path
import re
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
THEORY_DIR = ROOT / "theory"
QUARTO_YML = ROOT / "_quarto.yml"
THEORY_INDEX = THEORY_DIR / "index.qmd"
SCRIPT_REF = ".venv/bin/python scripts/update_theory_nav.py"

AUTO_BEGIN = "    # BEGIN AUTO THEORY SIDEBARS"
AUTO_END = "    # END AUTO THEORY SIDEBARS"
TOPICS_BEGIN = "<!-- BEGIN AUTO THEORY TOPICS -->"
TOPICS_END = "<!-- END AUTO THEORY TOPICS -->"
INDEX_MARKER = "<!-- AUTO-GENERATED BY scripts/update_theory_nav.py -->"

IGNORE_TOP_LEVEL = {
    "Posts",
    "_site",
    "assets",
    "__pycache__",
}

TITLE_OVERRIDES = {
    "Boolean_ana": "Boolean Analysis",
    "Factoring": "Factoring and Hidden Subgroup Problems",
    "Fermi-Hubbard": "Fermi-Hubbard Model",
    "Fingerprint": "Quantum Fingerprinting",
    "Ham_learning": "Hamiltonian Learning",
    "LGT": "Lattice Gauge Theory",
    "Magic": "Magic and Stabilizer Resources",
    "Noisy_complexity": "Classical Simulation of Noisy Quantum Circuits",
    "Nonlocal_Games_Survey": "Scalable Quantum Non-Locality: Architectures, Noise Resilience, and Experimental Frontiers",
    "OSF": "Generalized Stabilizer Formalism",
    "Perturbation": "Perturbation and Floquet Theory",
    "QEC": "Quantum Error Correction",
    "Shadow_tomography": "Classical Shadow Tomography",
    "Spin_liquid": "Spin Liquids",
    "TN_sim": "Tensor Network Simulation",
    "Virtual_Distillation": "Virtual Distillation for Quantum Error Mitigation",
    "compatibility": "Quantum Resource",
    "drugs_design": "Leveraging Analog Quantum Computing with Neutral Atoms for Solvent Configuration Prediction in Drug Discovery",
    "learning_theo": "Learning Theory and Quantum Learning",
    "quantum_complexity": "Quantum Complexity",
    "stab_simulation": "Stabilizer Simulation",
    "supermacy": "IQP Circuit Supremacy",
    "topo_matter": "Topological Matter",
}

SIDEBAR_ID_OVERRIDES = {
    "learning_theo": "learning_theory",
    "supermacy": "iqp",
}

SPECIAL_NESTED_SIDEBARS = {
    "learning_theo/Lowerbounds": ("lowerbounds", "Lower Bounds Toolbox"),
}


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8", errors="ignore") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def nice_title(name: str) -> str:
    return TITLE_OVERRIDES.get(name, name.replace("_", " ").replace("-", " ").title())


def topic_title(topic_dir: Path) -> str:
    index = topic_dir / "index.qmd"
    if index.exists():
        title = frontmatter(index).get("title")
        if title:
            return title
    if topic_dir.name in TITLE_OVERRIDES:
        return TITLE_OVERRIDES[topic_dir.name]
    return nice_title(topic_dir.name)


def sidebar_id(topic_dir: Path) -> str:
    return SIDEBAR_ID_OVERRIDES.get(topic_dir.name, slug(topic_dir.name))


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    data: dict[str, str] = {}
    for line in parts[1].splitlines():
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.+?)\s*$", line)
        if match:
            data[match.group(1)] = match.group(2).strip().strip("\"'")
    return data


def qmd_title(path: Path) -> str:
    meta = frontmatter(path)
    if meta.get("title"):
        return meta["title"]
    return path.stem.replace("_", " ").replace("-", " ").title()


def qmd_order(path: Path) -> tuple[float, str, str]:
    meta = frontmatter(path)
    raw = meta.get("order")
    try:
        order = float(raw) if raw is not None else float("inf")
    except ValueError:
        order = float("inf")
    return (order, qmd_title(path).lower(), path.as_posix().lower())


def topic_dirs() -> list[Path]:
    dirs: list[Path] = []
    for path in THEORY_DIR.iterdir():
        if not path.is_dir():
            continue
        if path.name.startswith(".") or path.name in IGNORE_TOP_LEVEL:
            continue
        if any(path.rglob("*.qmd")):
            dirs.append(path)
    return sorted(dirs, key=lambda p: topic_title(p).lower())


def set_sidebar_metadata(path: Path, sid: str) -> None:
    current = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""
    lines = current.splitlines()
    replaced = False
    for index, line in enumerate(lines):
        if re.match(r"^sidebar:\s*", line):
            lines[index] = f"sidebar: {sid}"
            replaced = True
            break
    if not replaced:
        lines.insert(0, f"sidebar: {sid}")
    write_if_changed(path, "\n".join(lines).rstrip() + "\n")


def qmds_immediate(directory: Path) -> list[Path]:
    return sorted(
        [path for path in directory.glob("*.qmd") if path.name != "index.qmd"],
        key=qmd_order,
    )


def qmds_recursive(directory: Path) -> list[Path]:
    paths = [path for path in directory.rglob("*.qmd")]
    return sorted(paths, key=lambda p: (p.parent.as_posix().lower(), p.name != "index.qmd", *qmd_order(p)))


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def section_title(directory: Path) -> str:
    return nice_title(directory.name)


def yaml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def markdown_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def build_sidebar_block(base_dir: Path, sid: str, title: str) -> str:
    lines = [f"id: {sid}", f'title: "{title}"', "contents:"]
    index = base_dir / "index.qmd"
    if index.exists():
        lines.append(f"  - {rel(index)}")

    direct = qmds_immediate(base_dir)
    if direct:
        lines.append('  - section: "Pages"')
        lines.append("    contents:")
        for path in direct:
            lines.append(f"      - {rel(path)}")

    for subdir in sorted(
        [path for path in base_dir.iterdir() if path.is_dir() and not path.name.startswith(".")],
        key=lambda p: section_title(p).lower(),
    ):
        qmds = qmds_recursive(subdir)
        if not qmds:
            continue
        lines.append(f'  - section: "{section_title(subdir)}"')
        lines.append("    contents:")
        for path in qmds:
            lines.append(f"      - {rel(path)}")

    return "\n".join(lines) + "\n"


def build_nested_sidebar_block(relative_dir: str, sid: str, title: str) -> str | None:
    directory = THEORY_DIR / relative_dir
    if not directory.exists() or not any(directory.rglob("*.qmd")):
        return None
    set_sidebar_metadata(directory / "_metadata.yml", sid)
    return build_sidebar_block(directory, sid, title)


def topic_description(topic_dir: Path, title: str) -> str:
    index = topic_dir / "index.qmd"
    if index.exists():
        existing = frontmatter(index).get("description")
        if existing:
            return existing
    return ""


def write_generated_topic_index(topic_dir: Path, title: str) -> None:
    index = topic_dir / "index.qmd"
    if index.exists() and INDEX_MARKER not in index.read_text(encoding="utf-8", errors="ignore"):
        return

    pages = [path for path in qmds_recursive(topic_dir) if path != index]
    description = topic_description(topic_dir, title) or f"Notes in the {title} topic directory."
    lines = [
        "---",
        "categories:",
        "- Index",
        "lang: en",
        f"title: {title}",
        f"description: {yaml_string(description)}",
        "---",
        "",
        "[<- Back to Theory](../index.qmd)",
        "",
        f"# {title}",
        "",
        INDEX_MARKER,
        "",
        "## Pages",
        "",
    ]
    if pages:
        for path in pages:
            lines.append(f"- [{qmd_title(path)}]({path.relative_to(topic_dir).as_posix()})")
    else:
        lines.append("No child pages have been added yet.")
    write_if_changed(index, "\n".join(lines).rstrip() + "\n")


def build_theory_topics_table(topics: Iterable[Path]) -> str:
    lines = [
        TOPICS_BEGIN,
        "",
        "| Topic | Description |",
        "|---|---|",
    ]
    for topic_dir in topics:
        index = topic_dir / "index.qmd"
        if not index.exists():
            continue
        title = qmd_title(index)
        description = topic_description(topic_dir, title)
        href = f"{topic_dir.name}/index.qmd"
        lines.append(f"| [{markdown_cell(title)}]({href}) | {markdown_cell(description)} |")
    lines.extend(["", TOPICS_END])
    return "\n".join(lines)


def rewrite_theory_index(topics: Iterable[Path]) -> None:
    text = THEORY_INDEX.read_text(encoding="utf-8", errors="ignore")
    block = build_theory_topics_table(topics)
    pattern = re.compile(rf"(?ms){re.escape(TOPICS_BEGIN)}.*?{re.escape(TOPICS_END)}")
    if pattern.search(text):
        write_if_changed(THEORY_INDEX, pattern.sub(block, text))
        return

    write_if_changed(THEORY_INDEX, text.rstrip() + "\n\n" + block + "\n")


def ensure_project_pre_render(text: str) -> str:
    if SCRIPT_REF in text:
        return text
    lines = text.splitlines()
    try:
        project_start = next(index for index, line in enumerate(lines) if line == "project:")
        website_start = next(index for index, line in enumerate(lines) if line == "website:")
    except StopIteration:
        return text

    # Drop any existing pre-render block inside the project section.
    cleaned: list[str] = []
    index = project_start + 1
    while index < website_start:
        line = lines[index]
        if line.strip() == "pre-render:":
            index += 1
            while index < website_start and lines[index].startswith("    - "):
                index += 1
            if index < website_start and lines[index].strip() == "":
                index += 1
            continue
        cleaned.append(line)
        index += 1

    lines = lines[: project_start + 1] + cleaned + lines[website_start:]
    website_start = next(index for index, line in enumerate(lines) if line == "website:")
    insert_at = website_start
    lines[insert_at:insert_at] = [
        "  pre-render:",
        f"    - {SCRIPT_REF}",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def split_sidebar_blocks(sidebar_body: str) -> list[str]:
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in sidebar_body.splitlines():
        if line.startswith("    - id:") and current:
            blocks.append(current)
            current = [line]
        elif line.startswith("    - id:"):
            current = [line]
        elif current:
            current.append(line)
    if current:
        blocks.append(current)
    return ["\n".join(block).rstrip() + "\n" for block in blocks]


def block_id(block: str) -> str | None:
    first = block.splitlines()[0] if block.splitlines() else ""
    match = re.match(r"\s*-\s*id:\s*(\S+)", first)
    return match.group(1) if match else None


def indent_sidebar_block(block: str) -> str:
    out: list[str] = []
    for index, line in enumerate(block.rstrip().splitlines()):
        if index == 0:
            out.append("    - " + line)
        else:
            out.append("      " + line if line else line)
    return "\n".join(out) + "\n"


def rewrite_quarto_sidebar(blocks: list[str], generated_ids: set[str]) -> None:
    text = ensure_project_pre_render(QUARTO_YML.read_text(encoding="utf-8", errors="ignore"))
    generated = AUTO_BEGIN + "\n" + "".join(indent_sidebar_block(block) for block in blocks) + AUTO_END + "\n"

    marker_pattern = re.compile(
        rf"(?ms)^{re.escape(AUTO_BEGIN)}\n.*?^{re.escape(AUTO_END)}\n?"
    )
    if marker_pattern.search(text):
        text = marker_pattern.sub(generated, text)
        write_if_changed(QUARTO_YML, text)
        return

    start = text.find("\n  sidebar:\n")
    end = text.find("\nformat:", start)
    if start == -1 or end == -1:
        raise RuntimeError("Could not find website.sidebar block in _quarto.yml")

    sidebar_header = "\n  sidebar:\n"
    existing_body = text[start + len(sidebar_header):end]
    kept_blocks = [
        block for block in split_sidebar_blocks(existing_body)
        if (block_id(block) not in generated_ids)
    ]
    replacement = sidebar_header + generated + "".join(kept_blocks)
    text = text[:start] + replacement + text[end:]
    write_if_changed(QUARTO_YML, text)


def main() -> None:
    blocks: list[str] = []
    generated_ids: set[str] = set()
    topics = topic_dirs()

    for topic_dir in topics:
        title = topic_title(topic_dir)
        sid = sidebar_id(topic_dir)
        write_generated_topic_index(topic_dir, title)
        set_sidebar_metadata(topic_dir / "_metadata.yml", sid)
        block = build_sidebar_block(topic_dir, sid, title)
        write_if_changed(topic_dir / "_sidebar.yml", block)
        blocks.append(block)
        generated_ids.add(sid)

    for relative_dir, (sid, title) in SPECIAL_NESTED_SIDEBARS.items():
        block = build_nested_sidebar_block(relative_dir, sid, title)
        if block is None:
            continue
        write_if_changed(THEORY_DIR / relative_dir / "_sidebar.yml", block)
        blocks.append(block)
        generated_ids.add(sid)

    rewrite_theory_index(topics)
    rewrite_quarto_sidebar(blocks, generated_ids)


if __name__ == "__main__":
    main()
