---
categories:
- Posts
date: '2026-03-19'
execute:
  enabled: false
lang: en
title: Factoring
bibliography: refs.bib
---


### The direct implementation of Shor's algorithm
**Finding the period**: Find the period of $ f(x) = a^x \text{mod~} N $.

The direct implementation of Shor's algorithm for factoring is as follows:



Therefore algorithm's key is to efficiently find the period $ r $, which only requires the quantum period finding algorithm. The key of the period finding algorithm is to implement the unitary transformation $ U \ket{x} \ket{0} \to \ket{x} \ket{a^x \text{mod~} N} $.





For example, let $ N = 15, a = 7 $ discuss the implementation of the circuit $ f(x) =  7^x \text{~mod~} 15 $.

The input is encoded as a binary $ x = x_{m -1}2^{m-1} + \cdots+ x_0 $,

The output is encoded on $ 4 $ qubits $ \ket{y} := \ket{y_0y_1y_2y_3}\sim y=8y_3 + 4 y_2 +2y_1+y_0  $,

The unitary transformation $ U_f $ can be implemented on the four qubits $ \ket{y} \to \ket{ay \text{~mod~} N } $.

---

**Lemma: ** 

The mapping $ y \to ay \text{~mod~} N $ is a one-to-one mapping from the interval $ y \in [0,N-1] $ to itself.

---

> **Proof:**
>
> Injective:
>
> If $ ay \equiv ay' \pmod{N} $, then $ a(y - y') \equiv 0 \pmod{N} $. Since $ a $ and $ N $ are coprime, we have $ y - y' \equiv 0 \pmod{N} $, i.e. $ y \equiv y' \pmod{N} $, therefore the mapping is injective.
>
> Surjective: 
>
> For any $ b \in \mathbb{Z}_N $, we need to find $ y $ such that $ ay \equiv b \pmod{N} $.
>
> Since $ a $ and $ N $ are coprime, $ a $ has a multiplicative inverse $ a^{-1} $ modulo $ N $. The inverse can be found using the extended Euclidean algorithm. Multiplying both sides by $ a^{-1} $, we get $ y \equiv a^{-1}b \pmod{N} $, thus there exists a solution $ y \in \mathbb{Z}_N $. Therefore, the mapping is surjective.
>

**Lemma**(Fermat's little theorem): If $ N $ is a prime and $ a $ and $ N $ are coprime, then $ a^{N - 1} = 1~\text{mod~}N $

The function can be implemented using a combination of classical gates, and the classical implementation will help us find the specific form of the unitary transformation $ U_f $.

Specifically, for a fixed $ m $-bit input, the function is: $ f(x) =  7^x \text{~mod~} 15 = (7^{2^{m-1}})^{x_{m-1}}\cdots(7^{2^{0}})^{x_{0}}\text{~mod~} 15 $

Therefore, the classical reversible calculation of the function $ f(x) $ is done by:

:::tips
1. $ (y_1y_2y_3y_4) $ is initialized to $ (0001) $
2. For $ j  = 0,\cdots,m-1 $, perform the classical gate $ C_jO_j $, which implements the operation block $ O_j $ on $ (y_1y_2y_3y_4) $ when $ x_j = 1 $
3. Each $ O_j $ implements a **modulo multiplier**, which multiplies the 4-bit data by $ (7^{2^{j}}) $ and finds the remainder when divided by $ 15 $
4. The design of $ O_j $ requires designing a fast algorithm for calculating $ (\cdot) \times (7^{2^{j}}) \text{~mod~} 15 $ (about j polynomial), which can take the following fast modular exponentiation algorithm

:::

We can efficiently implement the quantum gate $ CU_j $ using $ C_jO_j $.



## Approximate Shor
The direct calculation method above requires at least $ n $ logical bits for factoring an n-bit large number, and the total number of logical bits including auxiliary bits is only more. Recently, an algorithm that can complete the decomposition with only $ n/2 $ logical bits has been proposed, which is introduced in this section.

**Definition(Discrete logarithm):**

Given a finite group $ C = \langle g \rangle $ generated by a generator $ g $ and an element $ x \in C $, find the smallest $ l \in \mathbb{Z}^+ $ such that $ g^l = x $.

If we want to use Shor's algorithm to solve the more general discrete logarithm problem, we need to implement the following unitary transformation:

$ \ket{\alpha}\ket{\beta}\ket{0} \to \ket{\alpha}\ket{\beta}\ket{x^{\alpha}g^{\beta}} $.





1. Select a number $ G $ that is coprime to $ N $, and let its order be $ R $, i.e. the smallest positive integer satisfying $ G^R ≡ 1 \text{~mod~} N $. $ R $ can be efficiently calculated.
2. Calculate $ f(N) = (N-1)/2 - 2^{n/2-1}\text{~mod~} N, A = G^{f(N)}\text{~mod~} N $, which can be proved to exist a number $ D = \tilde P + \tilde Q - 2^{n/2 - 1} \text{~mod~}R $ such that $ A = G^D\text{~mod~} N $.
3. $ N,A,G $ are known, therefore call the discrete logarithm algorithm to find $ D $.



**Lemma:** For $ N = P × Q $ ($ P, Q $ are different large primes), any integer $ G $ that is coprime to $ N $ and satisfies $ G^R ≡ 1 (\text{mod~} N) $ must divide $ \lambda(N) = \text{lcm}(P-1, Q-1) = 2\tilde{P} \tilde{Q} / \text{gcd}(\tilde{P}, \tilde{Q}) $, where $ \tilde P ={(P-1)}/{2},\tilde Q ={(Q-1)}/{2} $.

> Proof:  
>
> Consider the integers in $ [0,N-1] $ under the multiplication modulo $ N $ operation, take the elements with inverses, they form a group, now count the number of group elements.
>
> Since $ N = PQ $ is a prime factorization, all elements in the interval $ [0,N-1] $ that are divisible by $ P $ (denoted as $ x $) do not have inverses because $ x \cdot Q =0 \text{~mod~}N $.   
>
> Similarly, elements divisible by $ Q $ also do not have inverses. Other elements (denoted as $ a $) are necessarily coprime to $ N $, so the function $ f_a(y) =ay \text{~mod~} N $必定有逆$ f_{a^{-1}} $ on the interval $ [0,N-1] $.
>
> Count the number of elements in the interval $ [0,N-1] $ that are not divisible by $ P,Q $, which is $ (P-1)(Q-1) $.
>
> Since the order of a finite group element must be a factor of the group order, we have $ R~|~(P-1)(Q-1) $.
>
> In fact, we考察$ \min \{m| x^m = 1, \forall x \in [0,N-1] \} \Leftrightarrow m= \text{lcm}(P-1,Q-1) $，$ R|m $也必须成立
>
> Additionally, $ \text{lcm}(P-1,Q-1) = \frac{(P-1)(Q-1)}{\text{gcd}[P-1,Q-1]} = \frac{4\frac{(P-1)}{2}\frac{(Q-1)}{2}}{\text{gcd}[\frac{P-1}{2},\frac{Q-1}{2}] \cdot2} = \frac{2P'Q'}{\text{gcd}[P',Q']} $.



---

Theorem: 

