---
categories:
- Quantum Learning
date: 2026-01-20
description: Lower bounding proof
format:
  html:
    html-math-method: katex
    number-sections: true
    toc: true
lang: zh
title: Toolbox for proving lower bounds
bibliography: refs.bib
---

# Toolbox for proving lower bounds

The lower bound does not rely on a specific strategy. But it tells us
why we cannot do better. This impossibility always stems from the fact
that the lack of information.

In this chapter, we first discuss the necessary information to
distinguish between two distributions. Many algorithms for complex
problems have been proved to violate this lower bound, thus proving a
no-go theorem for reaching the lower bound.

## Le-Cam's bound

We first upper bound the ability to distinguish two classical
distributions $p$ and $q$, as shown in
Lemma [\[lemma:TV_bound\]](#lemma:TV_bound){reference-type="ref"
reference="lemma:TV_bound"} below.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:TV_bound label="lemma:TV_bound"} If two distributions $p,q$ on
set $S = \{1,\cdots,n\}$ has total variance distance (**TVD**)
$\|p - q\|_{\mathrm {TV}}:=\frac{1}{2}\sum_{i = 1}^n|p(i) - q(i)| \leq \varepsilon$,
then there is no single sample algorithm $\mathcal{A}: S \to \{p,q\}$
that $\varepsilon/2$ better than random guessing, in other words,
satisfied
$\text{Pr}_{x \sim p}[\mathcal{A}(x) = p] \geq 1/2 + \varepsilon/2$ and
$\text{Pr}_{x \sim q}[\mathcal{A}(x) = q] \geq 1/2 + \varepsilon/2$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* It is sufficient to show that for an arbitrary algorithm
$\mathcal{A}$, either
$\text{Pr}_{x \sim p}[\mathcal{A}(x) = q] \geq (1-\varepsilon)/2$ or
$\text{Pr}_{x \sim q}[\mathcal{A}(x) = p] \geq  (1-\varepsilon)/2.$
Notice that $$\begin{align}
        \text{Pr}_{x \sim p}[\mathcal{A}(x) = q] + \text{Pr}_{x \sim q}[\mathcal{A}(x) = p] & = 1 - \text{Pr}_{x \sim p}[\mathcal{A}(x) = p] +\text{Pr}_{x \sim q}[\mathcal{A}(x) = p]\\
        &\geq 1 - \sup_{U \subseteq S} \left |\text{Pr}_{x \sim p}[U] -\text{Pr}_{x \sim q}[U]\right |\\
        &= 1 - \|p - q\|_{\mathrm{TV}} \geq 1 - \varepsilon.
\end{align}$$ Then either
$\text{Pr}_{x \sim p}[\mathcal{A}(x) = q] \geq   (1-\varepsilon)/2$ or
$\text{Pr}_{x \sim q}[\mathcal{A}(x) = p] \geq  (1-\varepsilon)/2$,
which means that either
$\text{Pr}_{x \sim p}[\mathcal{A}(x) = p] \leq   (1+\varepsilon)/2$ or
$\text{Pr}_{x \sim q}[\mathcal{A}(x) = p] \leq  (1+\varepsilon)/2$. ◻
:::

A slight generalization of
Lemma [\[lemma:TV_bound\]](#lemma:TV_bound){reference-type="ref"
reference="lemma:TV_bound"} is to distinguish a unique distribution
$p_0$ and multiple distributions $p_1,\cdots,p_l$ for
$L =\{1,\cdots,l\}$, where $p_i$ are all distributions over set
$S=\{1,\cdots,n\}$. We prove a generalized no-go theorem below:

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:mult_TV_bound label="lemma:mult_TV_bound"} If there exists a
distribution $\mathcal{D}$ over $L$ such that
$\delta_{\mathcal{D}}:=\|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}} \leq \varepsilon$,
then there is no single-sampling algorithm that distinguishes $p_0$
between $p_1,\cdots,p_l$ such that it is $\varepsilon/2$ better than
random guessing.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* We first directly prove this result using
lemma [\[lemma:TV_bound\]](#lemma:TV_bound){reference-type="ref"
reference="lemma:TV_bound"}. If it exists, we can use it as an algorithm
that distinguishes the distribution
$q(i):=\mathbb{E}_{r\sim \mathcal{D}}[p_{r}(i)]$ with $p_0(i)$ and it is
$\varepsilon/2$ better than random guessing. This contradicts the fact
that
$\|p_0 - q\|_{\mathrm {TV}} =\|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}}  \leq \varepsilon$
according to
Lemma [\[lemma:TV_bound\]](#lemma:TV_bound){reference-type="ref"
reference="lemma:TV_bound"}. ◻
:::

In
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, we can try all kinds of distribution
$\mathcal{D}$ over $L$ and choose the hardest one
$\delta_{\mathrm{w}} = \min_{\mathcal{D}}\delta_{\mathcal{D}}$. This
reflects the *worst case information complexity* of this discrimination
problem.

### Problem ensemble and average case hardness.

In general, this problem is much harder than two-point discrimination,
as we are designing a unified algorithm that dealt with multiple
two-point discrimination $(p_0,p_1),\cdots,(p_0,p_L)$ at the same time.
One can relax this problem by ensuring that the distribution $p_i$ only
appears following a fixed distribution $\mathcal{D}$. This reduces the
problem to a two-point discrimination
$(p_0,\mathbb{E}_{r \sim \mathcal{D}}p_r)$. Then the value
$\delta_{\mathcal{D}}$ in
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"} is tight. We call it the *average case
information complexity* under *problem ensemble* $\mathcal{D}$.
Similarly, we can define multiple-to-multiple tasks that discriminate a
set of distribution $\mathcal{A}$ from the other set of distribution
$\mathcal{B}$, whose average case hardness is defined by
$\|\mathbb{E}_{r \sim \mathcal{D}(A)}p_{r} -\mathbb{E}_{r \sim \mathcal{D}(B)} q_{s}\|_{\mathrm{TVD}}$
for problem ensemble $\mathcal{D}(\mathcal A)$ and
$\mathcal{D}(\mathcal B)$.

### Replica tells ensemble from its average.

One confusing point is the discrimination of the distribution
$p_0 = \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]$ and a set of distribution
$\{p_{r}\}$ with problem ensemble ${r \sim \mathcal{D}}$. By
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, we cannot distinguish them with
probability greater than $1/2$ given one-sample. However, under
k-samples, this is equivalent to the discrimination of
$p_0(t_1)\cdots p_0(t_k)$ and a set of distribution
$\{p_{r}(t_1)\cdots p_{r}(t_k)\}$ with problem ensemble
${r \sim \mathcal{D}}$. We can check that
$$
\mathbb{E}_{r\sim \mathcal{D}} \left[p_{r}(t_1)\cdots p_{r}(t_k)\right] \neq p_0(t_1)\cdots p_0(t_k) \\
=  \left[\mathbb{E}_{r\sim \mathcal{D}}p_{r}(t_1)\right]\cdots \left[\mathbb{E}_{r\sim \mathcal{D}}p_{r}(t_k)\right],
$$
thus can be estimated with probability greater than $1/2$.

### Coarse graining.

Intuitively, distinguishing two fine-grained distributions is never more
difficult than distinguishing their coarse-grained versions. With
**TVD**, we quantify this intuition as
Lemma [\[lemma:TVD_corse\]](#lemma:TVD_corse){reference-type="ref"
reference="lemma:TVD_corse"}.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:TVD_corse label="lemma:TVD_corse"} Given two distribution
$\mathbf{p}:=\{p_1,\cdots,p_M\},\mathbf{q}:=\{q_1,\cdots,q_M\}$ and
their coarse graining
$\mathbf{P}:=\bigcup_{s}\{p_{1,s},\cdots,p_{M,s}\},\mathbf{Q}:=\bigcup_{s}\{q_{1,s},\cdots,q_{M,s}\}$
such that
$\sum_{s} p_{k,s} = p_k,\sum_{s} q_{k,s} = q_k, \forall k \in \{1,\cdots,M\}$.
Then
$\|\mathbf{P} - \mathbf{Q}\|_{\mathrm{tvd}} \geq \|\mathbf{p} - \mathbf{q}\|_{\mathrm{tvd}}$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Since $\|\cdot\|_{\mathrm{tvd}} = 2^{-1}\|\cdot\|_{1}$, we
conclude that
$\|\mathbf{P} - \mathbf{Q}\|_{1} = \sum_{k,s}\|p_{k,s} - q_{k,s}\|_{1} \geq  \sum_{k}\|\sum_{s}p_{k,s} - \sum_{s}q_{k,s}\|_{1} = \|\mathbf{p} - \mathbf{q}\|_{1}$ ◻
:::

The most general form of the
lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"} is Le Cam's bound. We prove this
theorem and show that
lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"} is a special case of the Le-Cam
theorem [\[theo:Le_Cam\]](#theo:Le_Cam){reference-type="ref"
reference="theo:Le_Cam"} for completeness.

::: {.callout-important icon="false"}
## Theorem

[]{#theo:Le_Cam label="theo:Le_Cam"} Given a measurable space
$x \in \mathcal{X}$ and a family of measures
$P \in \mathcal{P}, P: 2^\mathcal{X} \to [0,1]$. Let
$\hat \theta:\mathcal{X} \to \mathbb{R}^p$ be an arbitrary estimator of
the parameters of this family of distributions
$\theta: \mathcal{P} \to \mathbb{R}^p$. Let
$D[\cdot,\cdot]:\mathbb{R}^p \times \mathbb{R}^p \to \mathbb{R}_{\geq 0}$
be a pseudo-metric of the parameter space that is symmetric and
satisfies the triangular inequality $D(x,y)+D(y,z) \geq D(x,z)$. Take
two arbitrary subsets $\mathcal{P}_1, \mathcal{P}_2 \subset \mathcal{P}$
that satisfied
$\inf_{\substack{P_1 \in \mathcal{P}_1,P_2 \in  \mathcal{P_2}} } D\left[\theta(P_1), \theta(P_2)\right] \geq 2\delta,$
then the inequality is true: $$\begin{align}
        \sup_{P \in \mathcal{P}} \left[\int_{x \in \mathcal{X}} dP(x)\cdot D\left[\hat \theta(x),\theta(P)\right]\right] \\
        &\geq \delta\cdot \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } \left[1 - \frac{1}{2}\int_{x \in \mathcal{X}} [dP_1(x) - dP_2(x)]\right].
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* We first noted that $$\begin{align}
          2\sup_{P \in \mathcal{P}} \left[\int_{x \in \mathcal{X}} dP(x)\cdot D\left[\hat\theta(x),\theta(P)\right]\right] \\
          &\geq  \int_{x \in \mathcal{X}} dP_1(x)\cdot D\left[\hat\theta(x),\theta(P_1)\right] \\
          &\quad + \int_{x \in \mathcal{X}} dP_2(x)\cdot D\left[\hat\theta(x),\theta(P_2)\right].
\end{align}$$ Based on the triangular inequality, we have
$D\left[\hat\theta(x),\theta(P_1)\right]  + D\left[\hat\theta(x),\theta(P_2)\right] \geq D\left[\theta(P_1),\theta(P_2)\right]\geq 2\delta$.
Thus, for a fixed point $x$, the tuple
$(f_1/2\delta,f_2/2\delta), \text{where }\begin{cases}f_1(x) =D[ \hat \theta(x),\theta(P_1)], \\f_2(x) =D[ \hat \theta(x),\theta(P_2)],\end{cases}$
is in the convex set
$\mathcal{S} =\{(r_1,r_2)\in \mathbb{R}^2| r_1,r_2\geq 0,r_1+r_2 \geq  1\}$.
Then $\forall P_1 \in \mathcal{P}_1,\forall P_2 \in \mathcal{P}_2$, we
write the inequality $$\begin{align}
          2\sup_{P \in \mathcal{P}} \left[\int_{x \in \mathcal{X}} dP(x)\cdot D\left[\hat\theta(x),\theta(P)\right]\right] \\
          &\geq 2\delta\cdot \left[\int_{x \in \mathcal{X}} \inf_{[r_1(x),r_2(x)] \in \mathcal{S}} \left[dP_1(x)\cdot r_1(x) +  dP_2(x)\cdot r_2(x)\right]\right]\\
          &\geq   \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } 2\delta\cdot \\
          &\quad \left[\int_{x \in \mathcal{X}} \inf_{[r_1(x),r_2(x)] \in \mathcal{S}} \left[dP_1(x)\cdot r_1(x) +  dP_2(x)\cdot r_2(x)\right]\right].
\end{align}$$ The RHS satisfied the identity $$\begin{align}
         \text{RHS} &=2\delta \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } \\
         &\quad \left[\int_{x \in \mathcal{X}} \inf_{ \substack{r_1(x),r_2(x)\geq 0,\\r_1(x)+r_2(x) =  1}} \left[dP_1(x)\cdot r_1(x) +dP_2(x)\cdot r_2(x)\right]\right]\\
          &=2\delta \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } \\
          &\quad \left[1 +\int_{x \in \mathcal{X}} \inf_{ r_1(x)\in [0, 1]}\left[dP_1(x)\cdot r_1(x) -  dP_2(x)\cdot  r_1(x)\right]\right]\\
         &=2\delta \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } \\
         &\quad \left[1- \int_{\substack{x \in \mathcal{X}\\P_2(x) \geq P_1(x)}} dP_2(x) -  dP_1(x) \right]\\
         &=2\delta \sup_{\substack{P_1 \in \text{cov~}\mathcal{P}_1\\P_2 \in \text{cov~} \mathcal{P_2}} } \\
         &\quad \left[1- \frac{1}{2} \int_{\substack{x \in \mathcal{X}}} |dP_2(x) -  dP_1(x)| \right].
\end{align}$$ This completes the proof. ◻
:::

::: {.callout-important icon="false"}
## Lemma

The
lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"} is a special case of the Le-Cam
theorem [\[theo:Le_Cam\]](#theo:Le_Cam){reference-type="ref"
reference="theo:Le_Cam"}.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Take the special case that $\mathcal{X} = \{1,\cdots,n\}$,
$\mathcal{P}_0 =\{p_0(x)\}, \mathcal{P}_1 =\{p_1(x),\cdots,p_l(x)\}$ and
$\theta(p_i) :=\begin{cases}0&\text{if }i =0,\\1&\text{else}.\end{cases}$
The estimator and metric are taken as
$\hat \theta(\cdot): \mathcal{X}\to\{0,1\}$ and $$\begin{align}
    D(\cdot,\cdot): \{0,1\}^{2} \to \{0,1\}, \\
    (\theta_1,\theta_2) &\hookrightarrow \begin{cases}1&\text{if }(\theta_1,\theta_2)=(1,0),(0,1),\\ 0 &\text{else}.\end{cases}
\end{align}$$ It is easy to see that $D(\cdot,\cdot)$ is indeed
symmetric and satisfies the triangular inequality. This strategy
distinguished the $\mathcal{P}_0$ and $\mathcal{P}_1$ with success
probability $$\begin{align}
    p_{\text{succ}}  &=\min_{i=1,\cdots,l}\left\{ \text{Pr}_{x \sim p_0}[\hat \theta(x) =0 ],\text{Pr}_{x \sim p_i}[\hat \theta(x) =1 ]\right\} \\
    &= 1 - \max_{i = 1,\cdots,l}\left\{ \text{Pr}_{x \sim p_0}[\hat \theta(x) =1 ],\text{Pr}_{x \sim p_i}[\hat \theta(x) =0 ]\right\}\\
    &=1 - \max_{p \in \mathcal{P}} E_{x \sim p} D[\hat \theta(x),\theta(p)].
\end{align}$$ Based on
Lemma [\[theo:Le_Cam\]](#theo:Le_Cam){reference-type="ref"
reference="theo:Le_Cam"}, we conclude the inequality $$\begin{align}
    \max_{p \in \mathcal{P}} E_{x \sim p} D[\hat \theta(x),\theta(p)] \geq \delta\cdot [1 - \|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}} ].
\end{align}$$ Notice that
$\inf_{\substack{P_1 \in \mathcal{P}_1,P_2 \in  \mathcal{P_2}} } D\left[\theta(P_1), \theta(P_2)\right] \geq 1$,
we take $\delta = 1/2$, which combine to the final result
$$\begin{align}
    p_{\text{succ}} \leq 1 -\frac{1 - \|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}} }{2} = \frac{1 + \|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}} }{2} .
\end{align}$$ Then if
$\|p_0 - \mathbb{E}_{r\sim \mathcal{D}}[p_{r}]\|_{\mathrm {TV}} \leq \varepsilon$,
we conclude that $p_{\text{succ}}\leq (1+\varepsilon)/2$ and cannot
$\varepsilon/2$ better than random guessing. ◻
:::

## Restriction on POVMs

Now we specify different POVM restrain
$\mathcal{M} = \{\{F_s\}|\{F_s\} \text{~satisfied the restriction.}\}$.
In general, we can keep $c$ copies of identical state
$\rho^{\otimes c}$, and implement a $c$-replica measurement. Such a
strategy are specified by as set of POVM operators
$\{F_s \in \mathrm{Herm}(d^c)\}_{s \in \mathcal{S}}$, with
$s \in \mathcal{S}$ specified the measurement results and
$\forall s \in \mathcal{S}, F_s \geq 0, \sum_s {F_s} = \mathbb{I}(d)^{\otimes c}$.
We first show that we can always restrain the form of $\{F_{s}\}_{s}$ on
rank-1 operator set $\{w_{s}\ket{\psi_{s}}\!\bra{\psi_{s}}\}_{s}$
without loss of generality. This is because arbitrary POVMs can be
simulated by rank-1 POVMs through grouping the results.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:POVM_r1_reduction label="lemma:POVM_r1_reduction"} Any POVM
$\{F_s\}_s$ can be simulated through rank-1 POVM
$\{w_{sp}\cdot\ket{\psi_{sp}}\!\bra{\psi_{sp}}\}_{sp}$ by classical
post-grouping $\ket{\psi_{sp}}\!\bra{\psi_{sp}} \to F_s$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Do Cholesky decomposition. Trivial. ◻
:::

This equivalence means that given an arbitrary state $\rho$, the
classical distribution generated by
$\{w_{sp}\cdot\ket{\psi_{sp}}\!\bra{\psi_{sp}}\}_{sp}$ is a coarse
graining of that of $\{F_s\}_s$. Using
Lemma [\[lemma:TVD_corse\]](#lemma:TVD_corse){reference-type="ref"
reference="lemma:TVD_corse"}, we conclude that it is sufficient to
consider rank-1 POVMs only.

Based on different experiment restriction, $F_s$ might only supports on
a subset of space $\mathrm{Herm}(d^c)$. Here below we characterized some
typical restriction.

### Restriction on the memory

We first focus on the $k$-memory $c$-replica strategies. It is a
c-replica measurement but with finite quantum-storage, as formally
defined below.

::: {.callout-note icon="false"}
## Definition

[]{#def:crep_kmem_POVMs label="def:crep_kmem_POVMs"} A $(c,k)$ adaptive
strategy repeats $T$ rounds of sampling. Within each round, as shown in
the process
diagram [\[eq:procc_diag\]](#eq:procc_diag){reference-type="eqref"
reference="eq:procc_diag"}, it repeatedly adds new copies of n-qubits
$\rho$ to the k-qubits memory $\sigma^{(i)}$ and adaptively implements
$n+k \to k$ qubits POVMs $\{M_s^{u}\}$. $$\begin{align}
\label{eq:procc_diag}
        \left[\rho \xrightarrow{\{M_{s_1}\}} \sigma^{(1)} \xrightarrow{\text{Add } \rho}  \rho \otimes \sigma^{(1)}\xrightarrow{\{M_{s_1,s_2}\}} \sigma^{(2)} \xrightarrow{\text{Add } \rho} \cdots  \rho \otimes \sigma^{(c)}\xrightarrow{\{M_{s_1,\cdots,s_c}\}} R_r \right]_{\times T}
\end{align}$$
:::

At the end of each round in a $(c,k)$-adaptive strategy, we get the
result $s_1,s_2,\cdots,s_c$, corresponding to the POVM branch
$$
\begin{aligned}
&\{M_{s_1}:\mathrm{Lin}(\mathcal{H}(d^{n}),\mathcal{H}(d^{k_1})), \\
&\quad M_{s_1,s_2}:\mathrm{Lin}(\mathcal{H}(d^{n + k_1}),\mathcal{H}(d^{k_2})), \cdots, \\
&\quad M_{s_1,s_2,\cdots,s_c}:\mathrm{Lin}(\mathcal{H}(d^{n + k_{c-1}}), \mathbb{C})\}.
\end{aligned}
$$
Here the parameter satisifed
$k_1 = \min\{n,k\}, k_2 = \min\{n+k_1,k\},\cdots,k_{c-1} = \min\{n+k_{c-2},k\}$.
The POVM operator $\{F_{\mathbf{s}}\}$ belongs to the linear space
$\mathrm{Lin}(\mathcal{H}(d^{cn}))$. When $k = (c-1)\cdot n$, we have
$k_1 = n,k_2 = 2n,\cdots,k_{c-1} = (c-1)n$. This means that the last
POVM operator supports on the whole linear space
$M_{s_1,s_2,\cdots,s_c}:\mathrm{Lin}(\mathcal{H}(d^{cn}), \mathbb{C})$.
Thus, the round-POVM operators $\{F_s\}$ cover the whole space
$\mathrm{Lin}(\mathcal{H}(d^{cn}))$ and are equivalent to first storing
$c$-copies of $n$-qudit states followed by $c$-copies collective
measurements. If $k < (c-1)n$, $\{F_s\}$ is restricted which we denoted
as the set $\mathcal{M}_{c,n}^{k}$. We show that every element of
$\mathcal{M}_{c,n}^{k}$ can be realized by rank-1 POVMs within
$\mathcal{M}_{c,n}^{k}$ and post coarse-graining of the measurement
results. Thus, it is sufficient to lower bounding all the rank-1
$\mathcal{M}_{c,n}^{k}$ POVMs
$\mathcal{M}_{c,n}^k = \{F_{j}:= 2^{cn}w_j|L_j\rangle\!\langle L_j|\}_{j}$,
with $\sum_{j}F_j = \mathbb{I}(d^{cn})$.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:rank1_kmemoPOVM label="lemma:rank1_kmemoPOVM"}
$\{F_s\}_s \in \mathcal{M}_{c,n}^{k}$ has decomposition
$\{F_s:= d^{nc}\sum_{a_c}w_{s,a_c}|L_{s,a_c}\rangle\!\langle L_{s,a_c}|\}_s$,
where $\ket{L_{s,a_c}}$ is a normalized MPS vector on $c \cdot n$ qudits
with at most $d^{k_j}$ bond dimension.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* The operator $F_s$ can be constructed from those $M_s$
operators through the identity: $$\begin{align}
    \mathrm{tr}(\rho^{\otimes c} F_s) = \sum_{a_c \in [d^{n+k}]}\begin{quantikz}[row sep=0.1cm, column sep=0.1cm]
        \setwiretype{n}&&&\gate[2]{M_{s_1, s_2}}&\gate[1]{M_{s_1}\vphantom{M_{s_1}^\dagger}}\setwiretype{c}&\gate[1]{\rho}\setwiretype{q}&\gate[1]{M_{s_1}^\dagger}\gategroup[4,steps=6,style={dashed,rounded corners,inner sep=-1pt},label style={label position=below, yshift=0.65cm, xshift=-0.7cm}]{$\ket{L_{s,a_c}}$}&\gate[2]{M_{s_1, s_2}^\dagger}\setwiretype{c}\\
        \setwiretype{n}&&\gate[2]{\cdots}\setwiretype{n}&\setwiretype{c}&\setwiretype{q}&\gate[1]{\rho}&&&\gate[2]{\cdots}\setwiretype{c}\\
        \setwiretype{n}&\gate[2]{M_{s_1,\cdots,s_c}}&\setwiretype{c}&\setwiretype{q}&&\gate[1]{\cdot\!\!\cdot\!\!\cdot}&&&&\gate[2]{M_{s_1,\cdots,s_c}^\dagger}\setwiretype{c}\\
        \lstick{$a_c$|\!|\!\!\!}\setwiretype{c}&&\setwiretype{q}&&&\gate[1]{\rho}&&&&&\setwiretype{c}&\rstick{\!\!\!|\!|$a_c$}
    \end{quantikz} \label{eq:tensor_network_MPS}
\end{align}$$ Here we use single line to indicate the $d$-dimensional
bond and double line to indicate the $k_j$-dimensional bond. The
restriction of such $(c,k)$-POVM operators, which we denoted as the set
$\mathcal{M}_{c,n}^{k}$, is equivalent to state that
$\{F_s:= d^{nc}\sum_{a_c}w_{s,a_c}|L_{s,a_c}\rangle\!\langle L_{s,a_c}|\}_s$
with $\ket{L_{s,a_c}}$ a normalized MPS vector on $c \cdot n$ qudits
with $d^{k_j}$ bond dimension: $$\begin{align}
    &\ket{L_{s,a_c}} =\sum_{a_j\in [d^{k_j}]} \ket{L_{s,a_1}}\ket{L_{s,a_1,a_2}}\cdots \ket{L_{s,a_{c-2},a_{c-1}}}\ket{L_{s,a_{c-1},a_c}}, \text{~where~} \forall \ket{e} \in \mathcal{H}(d^n),\\
    &\langle e|{L_{s,a_1}}\rangle := \langle e|M_{s_1}^{\dagger}|a_1\rangle,\quad \langle e|{L_{s,a_{j-1},a_{j}}}\rangle := \langle e,a_{j-1}|M_{s_1,\cdots,s_j}^{\dagger}|a_{j}\rangle,\forall j>1.
\end{align}$$ The trace-preserving condition
$\sum_{s_j} M^{\dagger}_{s_1,\cdots,s_j}M_{s_1,\cdots,s_j} = \mathbb{I}(d^n)$
now transformed into $$\begin{align}
    \sum_{a_j,s_j} \langle e|{L_{s,a_{j-1},a_{j}}}\rangle \langle {L_{s,a_{j-1},a_{j}}}|f\rangle  &=  \sum_{a_j}\langle e,a_{j-1}|M_{s_1,\cdots,s_j}^{\dagger}|a_{j}\rangle\langle a_{j}|M_{s_1,\cdots,s_j}|f,a_{j-1}\rangle\\
    &=\sum_{s_j}\langle e,a_{j-1}|M_{s_1,\cdots,s_j}^{\dagger}M_{s_1,\cdots,s_j}|f,a_{j-1}\rangle = \delta_{e,f} \\
    &\hspace{-5em}\Rightarrow \forall j = 1,\cdots,c,\quad \sum_{a_j,s_j} |{L_{s,a_{j-1},a_{j}}}\rangle \langle {L_{s,a_{j-1},a_{j}}}|= \mathbb{I}(d^n).
\end{align}$$ Thus, $\mathcal{M}_{c,n}^k$ can be implemented through
rank-1 MPS-POVMs
$\mathcal{M}_{c,n}^k = \{F_{j}:= 2^{cn}w_j|L_j\rangle\!\langle L_j|\}_{j=(s,a_c)}$,
with $\sum_{j}F_j = \mathbb{I}(d^{cn})$, followed by classical
post-processing rule $j=(s,a_c) \to s$. ◻
:::

Given a pure quantum state $\ket{L}$ that supports on $c$ identical
quantum systems with subsystem $S \subset \{1,\cdots,c\}$. Define $P^S$
as the tensor product of Pauli operator $P$ on the subsystem $s$ if
$s \in S$ otherwise identity. We say the Pauli operator $P$ are
$\varepsilon$-correlated on the subsystem if and only if
$|\bra{L} P^{S} \ket{L}|^2 \geq \varepsilon$. For a $2^k$-bonded MPS
states $\ket{L}$, we show that the $\varepsilon$-correlated Pauli is
only taking no more than $\varepsilon^{-1}2^{-n + k}$ proportion within
all possible Pauli operators, as rigorously stated in
Lemma [\[lemma:MPS_Paulicorrelation\]](#lemma:MPS_Paulicorrelation){reference-type="ref"
reference="lemma:MPS_Paulicorrelation"}.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:MPS_Paulicorrelation label="lemma:MPS_Paulicorrelation"}
Define the average Pauli correlation on subsystem
$S \subset \{1,\cdots,c\}$ as
$\mathcal{P}(S):= 4^{-n}\sum_{P \in \mathcal{P}_n} |\bra{L} P^{\otimes S} \ket{L}|^2$.
Then if $\ket{L}$ is an MPS state with no more than $2^k$ bond
dimension, we have $\mathcal{P}(S) \leq 2^{-n + k}$. In the special case
$|S| = 1$, $\mathcal{P}(S) \leq 2^{-n}$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* In the simplest case $c = 2,d= 2$, a MPS state with $\leq 2^k$
bond dimension always has Schmidt decomposition
$\ket{L} = \sum_{a = 1}^{2^k} \sqrt{\lambda_a} \ket{\phi_a} \otimes \ket{\psi_a}$
with $\sum_a \lambda_a = 1$. Take
$P^{\{1,2\}} = P \otimes P,P^{\{1\}} = P \otimes \mathbb{I}_n$, then
$$\begin{align}
    \mathcal{P}(\{1,2\}) &=  2^{-2n}\sum_{P \in \mathcal{P}_n}  \left|\sum_{a,a'}\sqrt{\lambda_a\lambda_{a'}}\bra{\phi_a}P\ket{\phi_{a'}}\bra{\psi_a}P \ket{\psi_{a'}}\right|^2\notag\\
    &\leq 2^{-2n}\sum_{P \in \mathcal{P}_n} \left( \sum_{a,a'}\left|\sqrt{\lambda_a\lambda_{a'}}\bra{\phi_a}P\ket{\phi_{a'}}\right|^2\right)\cdot \left(\sum_{a,a'}\left|\bra{\psi_a}P \ket{\psi_{a'}}\right|^2\right) \notag\\
    &\leq 2^{-2n + k}\sum_{P \in \mathcal{P}_n}  \sum_{a,a'}\lambda_a\lambda_{a'}\left|\bra{\phi_a}P\ket{\phi_{a'}}\right|^2 = 2^{-n + k} \sum_{a,a'}\lambda_a\lambda_{a'}\bra{\phi_a\phi_{a'}}\sum_{P \in \mathcal{P}_n} 2^{-n}P \otimes P\ket{\phi_{a'}\phi_a}\notag\\
    &=2^{-n + k} \sum_{a,a'}\lambda_a\lambda_{a'}\bra{\phi_a\phi_{a'}}\ket{\phi_{a}\phi_{a'}} =2^{-n + k},\\
    \mathcal{P}(\{1\}) &= 2^{-2n}\sum_{P \in \mathcal{P}_n}  \left|\sum_{a,a'}\sqrt{\lambda_a\lambda_{a'}}\bra{\phi_a}P\ket{\phi_{a'}}\bra{\psi_a}\ket{\psi_{a'}}\right|^2 = 2^{-2n}\sum_{P \in \mathcal{P}_n}  \left|\sum_{a}{\lambda_a}\bra{\phi_a}P\ket{\phi_{a}}\right|^2 \notag\\
    &=2^{-n}  \sum_{a}{\lambda_a\lambda_{a'}}\bra{\phi_a\phi_{a'}}\sum_{P \in \mathcal{P}_n} 2^{-n}P \otimes P\ket{\phi_{a}\phi_{a'}}= 2^{-n}  \sum_{a}{\lambda_a\lambda_{a'}}\bra{\phi_a\phi_{a'}}\ket{\phi_{a'}\phi_{a}}\leq 2^{-n}.
\end{align}$$ This generalized to $c>2$ case by noticing that
$\ket{L} = \sum_{a = 1}^{2^k} \sqrt{\lambda_a} \ket{\phi_a} \otimes \ket{\psi_a}$
is satisfied for bipartition $\{1,\cdots,l\} \cup \{l+1,c\}$. Take $l$
being the least on in set $S$. For special case $|S| = 1$, it is
trivially the same as $c = 2$ case. For $|S| \geq 2$, the same procedure
followed: $$\begin{align}
    \mathcal{P}(S) &=  2^{-2n}\sum_{P \in \mathcal{P}_n}  \left|\sum_{a,a'}\sqrt{\lambda_a\lambda_{a'}}\bra{\phi_a}P^{\{l\}}\ket{\phi_{a'}}\bra{\psi_a}P^{S - \{l\}} \ket{\psi_{a'}}\right|^2\leq 2^{-2n + k}\sum_{P \in \mathcal{P}_n}  \sum_{a,a'}\lambda_a\lambda_{a'}\left|\bra{\phi_a}P^{\{l\}}\ket{\phi_{a'}}\right|^2 \notag \\
    &= 2^{-n + k} \sum_{a,a'}\lambda_a\lambda_{a'}\bra{\phi_a\phi_{a'}}\sum_{P \in \mathcal{P}_n} 2^{-n}P^{\{l\}} \otimes P^{\{l\}}\ket{\phi_{a'}\phi_a}\leq 2^{-n + k} \sum_{a,a'}\lambda_a\lambda_{a'}=2^{-n + k}.
\end{align}$$ ◻
:::

In the case of $c =2$, we also have the inequality below:

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:lowMPS_SWAPproduct label="lemma:lowMPS_SWAPproduct"}
$$\begin{align}
    \max_{\{F_s\}_s \in \mathcal{M}^{k}_{2,n}} \sum_{s} \frac{\left[\mathrm{tr}(F_s \mathrm{SWAP}^{\otimes n})\right]^2}{\mathrm{tr}(F_s)} \leq 2^{k+n}
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

### Restriction on the locality

### Restriction on the magic

## Tree representation of adaptive strategy

Given an implementable POVM set
$\mathcal{M} = \{\{F_s\}|\{F_s\} \text{~satisfied the restriction.}\}$,
we can implement those POVMs multiple times, carefully design their
order, and even implement them adaptively. Any description of such an
adaptive learning protocol are called a $\mathcal{M}$-restrained
adaptive strategy. It has the *Tree
representation* [@chen2021exponential]. Roughly speaking, the adaptive
structure will first induce a decision tree $\mathcal{T}$. Each
branching edges in $\mathcal{T}$, which we denoted as
$\{(u,v_1),\cdots,(u,v_{s_u})\}$, was labeled by one of the restrained
POVMs $\{F^{u}_{v_{i}}\}_{i = 1}^{s_u} \in \mathcal{M}$. Then any
c-copies of state $\rho \in \mathcal{H}(d^c)$ will induce a probability
distribution $p_{\rho,\mathcal{T}}(v)$ on each vertex $v$ of the
decision graph $\mathcal{T}$.

::: {.callout-note icon="false"}
## Definition

Consider an adaptive learning strategy with $T$-rounds of $c$-replica
POVMs restrained on $\mathcal{M}$. The tree representation of it is

- A T-level decision tree $\mathcal{T}$ with root node $r$.

- Edges between node $u$ and its child nodes $s_1,\cdots,s_{N_u}$
  represents a POVM $\{F^{u}_s\}_{s =1}^{N_u} \in \mathcal{M}$ with the
  measurement outcomes $\{1,\cdots,N_u\}$.

- Each node $u$ is assigned a probability $p_{\mathcal{T},\rho}(u)$
  based on the updating rule $p_{\rho}(u) = p_{\rho}(u|s)p_{\rho}(s)$,
  where $p_{\rho}(s|u) = \text{tr}(F^u_{s} \rho)$ and $p_{\rho}(r) = 1$.
:::

<figure id="fig:ill_learnstrat" data-latex-placement="htbp!">
<embed src="Figure/adaptive.pdf" style="width:80.0%" />
<figcaption>Illustrations of a <span
class="math inline">(<em>c</em> = 3, <em>k</em> &lt; <em>n</em>)</span>
adaptive learning strategy and its tree representation <span
class="math inline">𝒯</span>. Refer to <span class="citation"
data-cites="chen2024optimal"></span>.</figcaption>
</figure>

To prove that any $\mathcal{M}$-restrained adaptive strategy
$\mathcal{T}$ cannot distinguish the states $\rho$ from a set of state
$\mathcal{S}$ with $1/2 + \varepsilon$ successful rate, it is sufficient
to show that $\forall \mathcal{T}$, the distribution
$p_{\rho,\mathcal{T}}(l)$ and the distribution ensemble
$\{p_{\sigma,\mathcal{T}}(l)\}_{\sigma \in \mathcal{E}}$ cannot be
distinguished $\varepsilon/2$ better than random guessing. This recasts
the problem in a form that is solvable by applying
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}. Thus, the distinguishability between
$\rho$ and $\mathcal{S}$ is tightly lower-bounded by **TVD** as
$$\begin{align}
\label{eq:tvd}
    \delta_{\mathrm{tvd}} :=\max_{\mathcal{T}}\min_{\mathcal{E}}\|p_{\rho,\mathcal{T}}-\mathbb{E}_{\sigma \sim\mathcal{E}} p_{\sigma,\mathcal{T}}\|_{\mathrm{TV}},
\end{align}$$ where $\mathcal{E}$ is an arbitrary distribution on the
set $\mathcal{S}$. The analysis of $\delta_{\mathrm{tvd}}$ requires
brute-force calculation of leaves distribution
$p_{\rho,\mathcal{T}}(l),\mathbb{E}_{\sigma \sim\mathcal{E}} p_{\sigma,\mathcal{T}}(l)$
on a deep decision tree. We can eschew this by constructing upper-bounds
for **TVD** using the *Leaves Likelihood* $L(l)$ and the *Edges
Likelihood* $L(u,s)$ of the decision tree. $$\begin{align}
    L_{\sigma}(l) := \frac{p_{\sigma,\mathcal{T}}(l)}{p_{\rho,\mathcal{T}}(l)} ,\quad L_{\sigma}(u,s):= \frac{p_{\sigma,\mathcal{T}}(s|u)}{p_{\rho,\mathcal{T}}(s|u)}.
\end{align}$$

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:UB_TVD label="lemma:UB_TVD"} Given distribution $p^{(0)}(l)$
and distribution ensemble $p^{(a)}(l),a \sim \mathcal{E}$ with
$L_a(l):=p^{(a)}(l)/p^{(0)}(l)$, then for any $\beta \in (0,1)$, the
**TVD** satisfied $$\begin{align}
    \|p^{(0)}-\mathbb{E}_a p^{(a)}\|_{\mathrm{TV}} \leq 1 - \min_{l}\mathbb{E}_a L_a(l), \quad
    \|p^{(0)}-\mathbb{E}_a p^{(a)}\|_{\mathrm{TV}} \leq \text{Pr}_{a\sim \mathcal{E},l \sim p^{(0)}}[L_a(l) \leq \beta] + (1 - \beta)
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* By definition, we have $$\begin{align}
        \|p^{(0)}-\mathbb{E}_a p^{(a)}\|_{\mathrm{TV}} &:= \frac{1}{2}\sum_{l \in \text{leaf}} |p^{(0)}(l) - \mathbb{E}_a p^{(a)}(l)| = \sum_{l \in \text{leaf}} p^{(0)}(l)\cdot \max\{0, 1 -\mathbb{E}_a p^{(a)}(l)/p^{(0)}(l)\}\\
        &\leq \mathbb{E}_a \sum_{l \in \text{leaf}} p^{(0)}(l)\cdot \max\{0, 1 -p^{(a)}(l)/p^{(0)}(l)\}\\
        &=\left[\sum_{\substack{a,l \in \text{leaf}\\\text{~s.t.~}L_a(l)\leq \beta}}p^{(0)}(l)\cdot \max \{0,1 - L_a(l)\}+\sum_{\substack{a,l \in \text{leaf}\\\text{~s.t.~}L_a(l)>\beta}}p^{(0)}(l)\cdot \max \{0,1 - L_a(l)\}\right].
\end{align}$$ Here in the first line, we directly get the first
inequality because $$\begin{align}
        \sum_{l \in \text{leaf}} p^{(0)}(l)\cdot \max\{0, 1 -\mathbb{E}_a p^{(a)}(l)/p^{(0)}(l)\} \leq \sum_{l \in \text{leaf}} p^{(0)}(l)\cdot \left( 1 - \min_{l}\mathbb{E}_a L_a(l) \right) = 1 - \min_{l}\mathbb{E}_a L_a(l).
\end{align}$$ In the second line, we use the fact that
$\max \{0, 1- x\}$ is a convex function, thus
$f(\mathbb{E}_a x_a) \leq \mathbb{E}_a f(x_a)$. Because for any
$\beta \in (0,1)$, we have $\begin{cases}
        \max\{0, 1 - L_a(l)\} \leq 1 - \beta, &\text{for } l \text{ s.t. } L_a(l) > \beta,\\
        \max\{0, 1 - L_a(l)\} \leq 1, &\text{for } l \text{ s.t. } L_a(l) \leq \beta,
    \end{cases}$, we obtain $$\begin{align}
        \|p^{(0)}-\mathbb{E}_a p^{(a)}\|_{\mathrm{TV}}  &\leq \sum_{\substack{a,l \in \text{leaf}\\L_a(l)\leq \beta}} p^{(0)}(l) +  (1 - \beta) \sum_{\substack{a,l \in \text{leaf}\\L_a(l)> \beta}} p^{(0)}(l)\\
        &=  \text{Pr}_{a\sim \mathcal{E},l \sim p^{(0)}}[L_a(l) \leq \beta] +(1 - \beta)\cdot \text{Pr}_{a\sim \mathcal{E},l \sim p^{(0)}}[L_a(l) > \beta]\\
        &\leq \text{Pr}_{a\sim \mathcal{E},l \sim p^{(0)}}[L_a(l) \leq \beta] + (1 - \beta).
\end{align}$$ ◻
:::

Then we can simply prove that
$\forall l, \mathbb{E}_{\sigma\sim \mathcal{E}} L_{\sigma}(l) \geq 1 - \delta$.
Then use the first inequality in
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"}, we have
$\|p_{\rho,\mathcal{T}}-\mathbb{E}_{\sigma \sim\mathcal{E}} p_{\sigma,\mathcal{T}}\|_{\mathrm{TV}} \leq \delta$.
Or we can prove a fine-tuned upper bound for the probability
$\text{Pr}_{\sigma\sim \mathcal{E}, l \sim p_{\rho,\mathcal{T}}(l)}[L_{\sigma}(l) \leq \beta]$.
This is found by the proportion of Edges Likelihood $L_{\sigma}(u,s)$,
as illustrated by the inequality in the
Lemma [\[lemma:UB_Ltail\]](#lemma:UB_Ltail){reference-type="ref"
reference="lemma:UB_Ltail"}.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:UB_Ltail label="lemma:UB_Ltail"} If $\forall u$ satisfied
$\mathbb{E}_{a\sim \mathcal{E}}\mathbb{E}_{s \sim p^{(0)}(s|u)}[(L_{a}(u,s) - 1)^2] \leq \delta$,
then for every constant $c_1 \in (0,1/3), c_2 >0$, there exists a
constant $c_3>0$ such that $$\begin{align}
       \mathrm{Pr}_{a\sim \mathcal{E}, l \sim p^{(0)}}[L_a(l) \leq 1 - c_1] \leq c_2+ c_3\delta T.
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

Now we are set to give a lower bound on
Eq.[\[eq:tvd\]](#eq:tvd){reference-type="eqref" reference="eq:tvd"},
which immediately lower bounding the measurement times $T$ of the
adaptive strategy $\mathcal{T}$, as shown in
Theorem [\[theo:mart_distinguish_lb\]](#theo:mart_distinguish_lb){reference-type="ref"
reference="theo:mart_distinguish_lb"} blow:

::: {.callout-important icon="false"}
## Theorem

[]{#theo:mart_distinguish_lb label="theo:mart_distinguish_lb"} To
distinguish $\rho$ and a set of state $\mathcal{S}$ for a constant
success rate $1/2 + \varepsilon$, with restrained POVMs $\mathcal{M}$
and classical adaptive strategy, the adaptive measurement rounds $T$
must be lower bounded by chi-squared divergence
$T > c \cdot \delta_{\mathcal{M},\rho,\mathcal{S}}^{-1}$, where
$$\begin{align}
        \delta_{\mathcal{M},\rho,\mathcal{S}} = \min_{\mathcal{E} \text{~on~} \mathcal{S}} \mathbb{E}_{\sigma \sim \mathcal{E}} \max_{\{F_s\}_s \in \mathcal{M}}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s})} \left[\frac{\mathrm{tr}(\sigma F_{s})}{\mathrm{tr}(\rho F_{s})} - 1\right]^2.
\end{align}$$ Sometimes we use a loosing lower bound
$T > c \cdot \delta_{\mathcal{M},\rho,\mathcal{S} \sim \mathcal{E}}^{-1}$
where $$\begin{align}
     \delta_{\mathcal{M},\rho,\mathcal{S} \sim \mathcal{E}} := \max_{\{F_s\}_s \in \mathcal{M}}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s})} \mathbb{E}_{\sigma \sim \mathcal{E}} \left[\frac{\mathrm{tr}(\sigma F_{s})}{\mathrm{tr}(\rho F_{s})} - 1\right]^2.
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* We first defined the likelihood function below: $$\begin{align}
\label{eq:likelihood_func}
  \mathcal{F}(\mathcal{T},\mathcal{E},\rho) := \max_{u}\mathbb{E}_{\sigma \sim \mathcal{E}} \mathbb{E}_{s \sim p_{\rho,\mathcal{T}}(s|u)} \left[\frac{p_{\sigma,\mathcal{T}}(s|u)}{p_{\rho,\mathcal{T}}(s|u)} - 1\right]^2 = \mathbb{E}_{\sigma \sim \mathcal{E}} \max_{u}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s}^{u})} \left[\frac{\mathrm{tr}(\sigma F_{s}^{u})}{\mathrm{tr}(\rho F_{s}^{u})} - 1\right]^2
\end{align}$$ Combining
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"} and
Lemma [\[lemma:UB_Ltail\]](#lemma:UB_Ltail){reference-type="ref"
reference="lemma:UB_Ltail"}, this function upper-bounds the **TVD**
through inequality $$\begin{align}
    \forall \mathcal{T},\mathcal{E},c_1 \in (0,1/3),c_2>0,&~\|p_{\rho,\mathcal{T}} - \mathbb{E}_{\sigma \sim \mathcal{E}} p_{\sigma,\mathcal{T}}\|_{\mathrm{TV}} \leq c_2 + c_3 \cdot \mathcal{F}(\mathcal{T},\mathcal{E},\rho) \cdot T + c_1,\\
    \Rightarrow \forall c_1 \in (0,1/3),c_2>0,&~\delta_{\mathrm{tvd}} \leq c_2 + c_3 \cdot \max_{\mathcal{T}}\min_{\mathcal{E}}\mathcal{F}(\mathcal{T},\mathcal{E},\rho) \cdot T + c_1.
\end{align}$$ Using
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, the correct probability
$1/2 + \varepsilon$ to distinguish $p_{\rho, \mathcal{T}}$ from
$\{p_{\sigma,\mathcal{T}}\}_{\sigma \in \mathcal{E}}$ must satisfy
$$\begin{align}
    &1/2 + \varepsilon < 1/2 + \delta_{\mathrm{tvd}}/2 \leq 1/2+{(c_1+c_2)}/{2} + (1/2)c_3\cdot\max_{\mathcal{T}}\min_{\mathcal{E}}\mathcal{F}(\mathcal{T},\mathcal{E},\rho)T\\
    & \Rightarrow T > \frac{2 \varepsilon - c_1 -c_2}{c_3}\left[\max_{\mathcal{T}}\min_{\mathcal{E}}\mathcal{F}(\mathcal{T},\mathcal{E},\rho)\right]^{-1} \geq c \cdot \left[\min_{\mathcal{E}}\max_{\mathcal{T}}\mathcal{F}(\mathcal{T},\mathcal{E},\rho)\right]^{-1}.
\end{align}$$ Here in the last inequality we use the max-min inequality
$\max_{\mathcal{T}}\min_{\mathcal{E}}\mathcal{F} \leq \min_{\mathcal{E}}\max_{\mathcal{T}}\mathcal{F}$.
As long as $\varepsilon$ is a constant, we can always tune the value of
$c_1 \in (0,1/3),c_2>0$ such that the lower bound
$T > c\cdot \max_{\mathcal{T}}\min_{\mathcal{E}}\mathcal{F}^{-1}(\mathcal{T},\mathcal{E}, \rho)$
is meaningful (i.e., $c>0$). Plug in the definition of $\mathcal{F}$, we
get the equation
$T \geq c \cdot \delta_{\mathcal{M},\rho,\mathcal{S}}^{-1}$, where
$$\begin{align}
    \delta_{\mathcal{M},\rho,\mathcal{S}} = \min_{\mathcal{E}}\max_{\mathcal{T}}\mathcal{F}(\mathcal{T},\mathcal{E}, \rho) 
    &=\min_{\mathcal{E}} \mathbb{E}_{\sigma \sim \mathcal{E}} \max_{\mathcal{T}}\max_{u}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s}^{u})} \left[\frac{\mathrm{tr}(\sigma F_{s}^{u})}{\mathrm{tr}(\rho F_{s}^{u})} - 1\right]^2 \\
    &=\min_{\mathcal{E}} \mathbb{E}_{\sigma \sim \mathcal{E}} \max_{\{F_s\}_s \in \mathcal{M}}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s})} \left[\frac{\mathrm{tr}(\sigma F_{s})}{\mathrm{tr}(\rho F_{s})} - 1\right]^2.
\end{align}$$ Here in the last line, we consider all possible adaptive
strategy with POVM restriction $\{F_s^{u}\} \in \mathcal{M}, \forall u$,
thus the maximum can be unioned. Sometimes we ignore the minimization
over all possible ensemble $\mathcal{E}$ over the state set
$\mathcal{S}$ and give a loose lower bound for the measurement times. We
denoted this as: $$\begin{align}
    \delta_{\mathcal{M},\rho,\mathcal{S}} \leq \delta_{\mathcal{M},\rho,\mathcal{S} \sim \mathcal{E}} := \max_{\{F_s\}_s \in \mathcal{M}}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s})} \mathbb{E}_{\sigma \sim \mathcal{E}} \left[\frac{\mathrm{tr}(\sigma F_{s})}{\mathrm{tr}(\rho F_{s})} - 1\right]^2.
\end{align}$$ ◻
:::

Before dived into complex prove of distinguishability lower bound, it is
necessary to build an intuition about which ensemble is hard to
distinguished.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:hard_necess1 label="lemma:hard_necess1"} Given two state
ensemble $\mathcal{E}_1,\mathcal{E}_2$. If
$$
\|\mathbb{E}_{\rho \sim \mathcal{E}_1}[\rho^{\otimes k}] - \mathbb{E}_{\rho \sim \mathcal{E}_2}[\rho^{\otimes k}]\|_1 \\
:= \|\mu^{(k)}_1 - \mu^{(k)}_2\|_{1}\geq \varepsilon,
$$
then there exists strategy that distinguishes $\mathcal{E}_1$ and
$\mathcal{E}_2$ using $k$-replica measurement for $O(1/\varepsilon^2)$
times.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Define function $f(A):=\|A\|_1$. Since $f(A)$ is a closed and
convex function, we conclude that
$f(A) = \max_{O}\left[\mathrm{tr}(O\cdot A) - f^*(O)\right]$. The
conjugate function writes:
$f^{*}(A) = \begin{cases}0 &\text{if~}\|A\|_{\infty}<1\\ +\infty &\text{if else}. \end{cases}$,
thus we have $\|A\|_{1} = \max_{\|O\|_{\infty}<1}\mathrm{tr}(O\cdot A)$.
Thus, the condition $\|\mu^{(k)}_1 - \mu^{(k)}_2\|_{1}\geq \varepsilon$
is equivalent to the existence of $O, \|O\|_{\infty}<1$ such that
$\mathrm{tr}(O \mu^{(k)}_1) - \mathrm{tr}(O \mu^{(k)}_2) \geq \varepsilon$.
This means that we can measure operator $O$ on $k$-replica state
$\rho^{\otimes k}$ and construct a direct estimator $\hat{o}$ for
$\mathrm{tr}(O \mu^{(k)})$. If the estimator $\hat{o}$ has
$\leq \varepsilon/2$ additive error, then it solves the discrimination
problem. The condition $O, \|O\|_{\infty}<1$ means that
$-1<\mathrm{tr}(O \mu^{(k)}) < 1$. We then can use Hoeffding inequality
in Theorem [\[theo:Hoeff_inq\]](#theo:Hoeff_inq){reference-type="ref"
reference="theo:Hoeff_inq"} to bound the sampling complexity
$N < 2\varepsilon^{-2} \ln(2 \delta^{-1})$ to constructing $\hat{o}$
with $\leq \varepsilon/2$ additive error. ◻
:::

For more general task to distinguish set $S_1$ form $S_2$, it is
equivalent to build all possible distribution on $S_1,S_2$ and check the
hardness of these constructed ensemble on $S_1$ and $S_2$. However,
Lemma [\[lemma:hard_necess1\]](#lemma:hard_necess1){reference-type="ref"
reference="lemma:hard_necess1"} is only a necessary condition. Even if
two ensembles have similar rank-$k$ property, their might still exist
efficient $k$-replica measurement strategy. An example is $\mathbb{I}/d$
and $\{\ket{\mathbf{s}}\!\bra{\mathbf{s}}\}_{\mathbf{s}}$ with
$\mathbf{s}$ uniformly distributed on $\mathbb{F}_2^{n}$. This is
because although
$\mathbb{E}_{\rho \sim \mathcal{E}_1}[\rho^{\otimes k}] = \mathbb{E}_{\rho \sim \mathcal{E}_2}[\rho^{\otimes k}]$,
we still have
$$
\mathbb{E}_{\rho \sim \mathcal{E}_1}[\prod_{i = 1}^{T}\mathrm{tr}(O_i\rho^{\otimes k})] \\
\neq \mathbb{E}_{\rho \sim \mathcal{E}_2}[\prod_{i = 1}^{T}\mathrm{tr}(O_i\rho^{\otimes k})].
$$

With this intuition in mind, now we reviewed the information lower bound
to distinguish Haar random state ensembles. Perhaps the most simple one
are the maximum mixed state $\mathbb{I}(d)/d$ with operator mixed
ensemble.

## Operator mixed ensemble and its distinguishability

::: problem
[]{#prob:Gibbtest label="prob:Gibbtest"} Given access to either (i). A
set of state
${S}_{\mathcal{O}}:=\{(\mathbb{I}+ 3\varepsilon O_x)/d\}_{x \in \{1,\cdots,M\}}$
or (ii) $\rho = \mathbb{I}/2^n$, try to distinguish between these two
cases with an error of at most $1/2-\varepsilon$.
:::

This problem determines the lower bound of classical shadow of
$\{O_x\}_{x \in \{1,\cdots,M\}}$ and has a special case for
discrimination of $\mathbb{I}/d$ and Pauli mixed state
$\rho = (\mathbb{I}+ 3\varepsilon P)/2^n$ with $P \in \mathcal{P}_n$.

We first get intuition of this task based on
Lemma [\[lemma:hard_necess1\]](#lemma:hard_necess1){reference-type="ref"
reference="lemma:hard_necess1"}. If we choose distribution on
$\mathcal{O}$ supports on $Z_1$ operators only, we conclude that the
value $\|\mu_1^{(1)} - \mu_2^{(1)}\|_1$ are separately
$\|3\varepsilon Z_1/2^n\|_1 = \mathrm{tr}\left({3\varepsilon \mathbb{I}/2^n}\right) = 3\varepsilon$
and
$$
\|4^{-n}\sum_{P \in \mathcal{P}}3\varepsilon P/2^n\|_1 \\
= 3\varepsilon \left[\mathrm{tr}\left(\sqrt{AA^\dagger}\right) \right]^{n} \\
= 3\varepsilon(\sqrt{3}/2)^n \sim \mathcal{O}(2^{-n}).
$$
Here we use
$\mathrm{tr}\left(\sqrt{AA^\dagger}\right) = \sum_{\lambda(A)}|\lambda(A)|$
and $$\begin{align}
A = \frac{I+X+Y+Z}{4} =4^{-1} \begin{pmatrix}2&1- i\\1+i&0\end{pmatrix}, \quad \lambda(A) = {\frac{1 - \sqrt{3}}{4},\frac{1 + \sqrt{3}}{4}}.
\end{align}$$ This means that even though there exists easy distribution
$\mathrm{Pr}(P)=\delta(P - Z_1)$ on Pauli operators that can be
distinguished with $\mathbb{I}/d$ with single replica strategy, there
also has distribution $\mathrm{Pr}(P) = 4^{-n}$ that might be hard.
Based on this intuition, we set up hard distributions as uniform
distribution on signed operators $\{+1,-1\}\times \mathcal{O}$. This
ensures its average is exactly $\mathbb{I}/d$, thus being hard for
1-replica strategy.

### General operators

### single-copy strategy.

For shadow tomography of general operator set $\{O_1,\cdots,O_M\}$ where
$O_j$ is an arbitrary $n$-qubits operator, we build hard distribution by
rotating Pauli $Z$ operators with independent Haar random unitary:
$$\begin{align}
    O_{1},\cdots,O_{M/2} &= U_1Z_1U_1^{\dagger}, \cdots, U_{M/2}Z_{M/2}U_{M/2}^{\dagger},\\
    O_{M/2+1},\cdots,O_{M} &= -U_1Z_1U_1^{\dagger}, \cdots, -U_{M/2}Z_{M/2}U_{M/2}^{\dagger},
\end{align}$$ where $U_1,\cdots,U_{M/2}$ are independent Haar random
unitaries. The signature is to ensure its average is $\mathbb{I}/d$ such
that
Lemma [\[lemma:hard_necess1\]](#lemma:hard_necess1){reference-type="ref"
reference="lemma:hard_necess1"} cannot give effective single copy
strategy. According to
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, to distinguish (i) and (ii) with $2/3$
correction rate, which is $\delta= 1/6$ better that $1/2$, we must have
$1/3=2\delta \leq \|\mathbb{E}_{x} p_{\rho_x} - p_{2^{-n}\mathbb I}\|_{\mathrm{TV}}$,
where $x$ is an arbitrary distribution on $1,\cdots,M$. It is sufficient
to take the uniform distribution of $x$. Based on
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"},
$1/3\leq \|\mathbb{E}_{x} p_{\rho_x} - p_{2^{-n}\mathbb I}\|_{\mathrm{TV}} \leq 1 - \min_{l} \mathbb{E}_{x} L_{x}(l)$.
According to the rank-1 reduction in
Lemma [\[lemma:POVM_r1_reduction\]](#lemma:POVM_r1_reduction){reference-type="ref"
reference="lemma:POVM_r1_reduction"}, we calculate the leaves'
likelihood $\forall l$ as $$\begin{align}
\mathbb{E}_{x} L_{x}(l) &= \frac{\mathbb{E}_{x} p_{\rho_x}(l)}{p_{2^{-n}\mathbb I}(l)} = \mathbb{E}_{x} \prod_{t = 1}^T \frac{w_{s_t}^{u_t}\bra{\psi_{s_t}^{u_t}}\rho_x \ket{\psi_{s_t}^{u_t}}}{2^{-n}w_{s_t}^{u_t}}=\mathbb{E}_{x} \prod_{t = 1}^T \left(1+ 3\varepsilon\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}\right)\notag\\
&=\mathbb{E}_{x} \text{exp}\left[\sum_{t = 1}^T \ln\left(1+ 3\varepsilon\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}\right)\right]\geq \text{exp}\left[\sum_{t = 1}^T \mathbb{E}_{x} \ln\left(1+ 3\varepsilon\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}\right)\right]\notag\\
&=\text{exp}\left[\sum_{t = 1}^T M^{-1} \ln \left(\prod_{x = 1}^{M/2}\left(1+ 3\varepsilon\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}\right)\left(1- 3\varepsilon\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}\right)\right)\right]\notag\\
&=\text{exp}\left[\sum_{t = 1}^T M^{-1} \sum_{x = 1}^{M/2}\ln \left(1- 9\varepsilon^2\cdot \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}^2\right)\right] \notag\\
&\geq \text{exp}\left[-9\varepsilon^2\sum_{t = 1}^T \frac{2}{M}\sum_{x = 1}^{M/2} \bra{\psi_{s_t}^{u_t}} O_x \ket{\psi_{s_t}^{u_t}}^2\right] \geq \text{exp}\left[-9\varepsilon^2 T \sup_{\ket{\phi}}\frac{2}{M}\sum_{x = 1}^{M/2} \bra{\phi} O_x \ket{\phi}^2\right] \label{eq:sig_canc_TVlb}
\end{align}$$ Here we use $\ln(1 - x)\geq -2x, \forall x \in [0,0.796]$.
This condition is satisfied if and only if
$9\varepsilon^2<0.796, \varepsilon <0.29$. Thus for
$\beta =\text{exp}\left[-9\varepsilon^2 T \delta(O_1,\cdots,O_M)\right]$,
we have $\text{Pr}_{l \sim p^{(0)}}[L(l) \leq \beta] = 0$, which gives
the inequality use the fact that
$1 - x \leq e^{-x},\forall x \in \mathbb{R}$. $$\begin{align}
&1/3\leq 0 +(1 - \beta) = 1 - e^{-9\varepsilon^2 T \delta(O_1,\cdots,O_M)}  \leq 9\varepsilon^2 T \delta(O_1,\cdots,O_M) \notag\\
&\Rightarrow T \geq \Omega(\frac{1}{\varepsilon^2 \delta(O_1,\cdots,O_M)}), \text{~where~} \delta(O_1,\cdots,O_M):= \sup_{\ket{\phi}} \frac{2}{M}\sum_{i =1}^{M/2}\bra{\phi} O_i \ket{\phi}^2. \label{eq:LB_shadow_eq}
\end{align}$$ Now we calculate the value $\delta(O_1,\cdots,O_M)$. Noted
that the random variable
$\bra{\phi} O_i \ket{\phi},\{O_i\}_i \sim \mathcal{O}$ and
$\bra{\psi_i} Z_n \ket{\psi_i}, \ket{\psi_i} \sim \text{Haar}$ has the
same distribution. Thus, it is sufficient to discuss the property of
function $f(\ket{\psi}):= \bra{\psi} Z_n \ket{\psi}$ with Haar random
inputs.

::: {.callout-important icon="false"}
## Lemma

 []{#lemma:expon_cent_ineq label="lemma:expon_cent_ineq"} Given function
$f(\ket{\psi}):= \bra{\psi} Z_n \ket{\psi}$ with independent Haar random
inputs, we conclude that $$\begin{align}
        &\text{Pr}\left[\left|\frac{1}{R}\sum_{i =1}^{R} f(\ket{\psi_i})^2 - \mathbb{E}_{\ket{\psi} \sim \text{Haar}}\left[ f(\ket{\psi})^2\right]\right| \geq t\right] \leq 2 e^{-R \min(t^2/\lambda^2, t/\lambda)},\\
        & \text{where~} \lambda = 288\pi^3/2^n,\quad \mathbb{E}_{\ket{\psi} \sim \text{Haar}} [f(\ket{\psi_i})^2] = \frac{1}{2^n + 1}
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

Now given one state $\ket{\phi}$, we proved that with high probability
$\sum_{O \in \mathcal{O}} |\mathcal{O}|^{-1}\bra{\phi} O \ket{\phi}^2$
will not deviate from its expectation too much, according to the
Lemma [\[lemma:expon_cent_ineq\]](#lemma:expon_cent_ineq){reference-type="ref"
reference="lemma:expon_cent_ineq"}. Nevertheless, we hope to prove this
property for all states $\phi$, that is, to bound the deviation of
$\sup_{\ket{\phi}}\sum_{O \in \mathcal{O}} |\mathcal{O}|^{-1}\bra{\phi} O \ket{\phi}^2$.
To do this, to first defined an $\eta$-covering set $\mathcal{N}_{\eta}$
on the n-qubit pure states, as illustrated in
Lemma [\[lemma:covering_on_nqubit\]](#lemma:covering_on_nqubit){reference-type="ref"
reference="lemma:covering_on_nqubit"}.

::: {.callout-important icon="false"}
## Lemma

 []{#lemma:covering_on_nqubit label="lemma:covering_on_nqubit"} An
$\eta$-covering set $\mathcal{N}_{\eta}$ on the n-qubit pure states is a
finite set of n-qubit pure states such that
$$
\forall \ket{\phi} \in \mathcal{H}_n, \exists \ket{\psi} \in \mathcal{N}_{\eta}, \\
\text{s.t.~} \|\ket{\phi} - \ket{\psi}\|_2 \leq \eta.
$$
The cardinality of $\mathcal{N}_{\eta}$ is upper bounded by
$|\mathcal{N}_{\eta}| \leq (1 + 2/\eta)^{2^{n+1}}$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* The set of n-qubit pure states corresponds to the unit sphere
in the Hilbert space $\mathcal{H}(n) \cong \mathbb{C}^{2^n}$. This
complex space of dimension $2^n$ is equivalent to a real space of
dimension $D = 2 \cdot 2^n = 2^{n+1}$. The states are thus points on the
unit sphere $S^{D-1}$ in $\mathbb{R}^D$. Let
$\mathcal{N}_{\eta} = \{\ket{\psi_1}, \ket{\psi_2}, \dots, \ket{\psi_M}\}$
be a maximal set of n-qubit pure states such that the Euclidean distance
between any two distinct states in the set is greater than $\eta$. This
is known as an $\eta$-packing. We first argue that this set
$\mathcal{N}_{\eta}$ is also an $\eta$-covering net. If it were not,
then $\exists \ket{\phi} \in \mathcal{H}_n$ such that
$\forall \ket{\psi_i} \in \mathcal{N}_{\eta} ,\|\ket{\phi} - \ket{\psi_i}\|_2 > \eta$,
which contradicts the assumption that $\mathcal{N}_{\eta}$ is a maximal
set. Therefore, any maximal $\eta$-packing is an $\eta$-covering net.
The problem is now reduced to finding an upper bound on the size
$M = |\mathcal{N}_{\eta}|$ of such a packing. Consider a set of open
balls $\{B(\ket{\psi_i}, \eta/2)\}_{i=1}^M$ of radius $\eta/2$ centered
at each point of our set $\mathcal{N}_{\eta}$. Since for any $i \neq j$,
we have $\|\ket{\psi_i} - \ket{\psi_j}\|_2 > \eta$, the triangle
inequality implies that these balls are disjoint. All these disjoint
balls are contained within a larger ball of radius $1 + \eta/2$ centered
at the origin. This is because each $\ket{\psi_i}$ is on the unit sphere
(norm 1), and any point in the ball $B(\ket{\psi_i}, \eta/2)$ has a norm
of at most $\|\ket{\psi_i}\|_2 + \eta/2 = 1 + \eta/2$. The total volume
of these $M$ disjoint balls cannot exceed the volume of the larger
containing ball. Let $V_D(r)$ be the volume of a $D$-dimensional ball of
radius $r$. We have $\sum_{i=1}^M V_D(\eta/2) \le V_D(1 + \eta/2)$.
Since all the small balls have the same volume, this simplifies to
$M \cdot V_D(\eta/2) \le V_D(1 + \eta/2)$. The volume of a
$D$-dimensional ball of radius $r$ is given by $C_D r^D$ for some
constant $C_D$ that depends only on the dimension $D$. Thus, we can
write $M \cdot C_D (\eta/2)^D \le C_D (1 + \eta/2)^D$. Canceling the
constant $C_D$ and substituting back the dimension $D = 2^{n+1}$, we get
the upper bound on $M$ $$\begin{align}
    |\mathcal{N}_{\eta}| = M \le \frac{(1 + \eta/2)^D}{(\eta/2)^D} = \left(\frac{1 + \eta/2}{\eta/2}\right)^D = \left(1 + \frac{2}{\eta}\right)^D.
\end{align}$$ ◻
:::

Then the low-deviation condition that satisfied for arbitrary
$\ket{\phi} \in \mathcal{H}(n)$ also satisfied on set
$\mathcal{N}_{\eta}$, only with a $|\mathcal{N}_\eta|$ larger error
probability. After this, we show that the function
$g(\ket{\phi}):=\sum_{O \in \mathcal{O}} |\mathcal{O}|^{-1}\bra{\phi} O \ket{\phi}^2$
is Lipschitz continuous, which means that the difference of function
value is upper bounded by the variables difference. Combining the
Lipschitz continuity and the property of the $\eta$-covering, we show
upper bounds for the value
$\sup_{\ket{\phi}}\sum_{O \in \mathcal{O}} |\mathcal{O}|^{-1}\bra{\phi} O \ket{\phi}^2$,
as rigrously illustrated in
Lemma [\[lemma:point_to_uniform\]](#lemma:point_to_uniform){reference-type="ref"
reference="lemma:point_to_uniform"}.

::: {.callout-important icon="false"}
## Lemma

 []{#lemma:point_to_uniform label="lemma:point_to_uniform"} Given an
L-Lipschitz continuous function $f:V \to \mathbb{R}$ on metric space $V$
and an $\eta$-covering set $\mathcal{N}_{\eta}$ of $V$, if
$\forall x \in \mathcal{N}_{\eta}, |f(x) - c| < t$, then
$\forall x \in V, |f(x) - c| < t + L \eta$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* By definition, we know that
$\forall x \in V, \exists r_x \in \mathcal{N}_{\eta} \text{~s.t.~} |r_x - x| \leq \eta$.
Then we conclude $$\begin{align}
        \forall x \in V, |f(x) - c| &\leq |f(x) - f(r_x)| + |f(r_x) - c|\leq L\|x - r_x\| + t \leq L\eta + t.
\end{align}$$ ◻
:::

If we further

::: {.callout-important icon="false"}
## Theorem

Given a uniform distribution on $M$ Pauli observables
$\mathcal{A}:=\{P_1,\cdots,P_M\}$, any single-copy learning algorithm
that predict $\{\text{tr}(\rho P)\}_{P \sim \mathcal{A}}$ with
$\varepsilon$-additive error and $2/3$ success probability must use
$T \geq \Omega \left(\varepsilon^{-2} \min\{M/\log M, 2^n\}\right)$
samples.
:::

### Pauli mixed states

::: problem
[]{#prob:Pauli_mixed_test label="prob:Pauli_mixed_test"} Given a subset
$\mathcal{O} \subset \mathcal{P}(n)$, try to discriminate (i). A set of
state
${S}_{\mathcal{O}}:=\{\sigma_{P}:=(\mathbb{I}+ 3\varepsilon P)/d\}_{P \in \mathcal{O}}$
and (ii) $\rho = \mathbb{I}/2^n$ with confidence $1 - \delta$.
:::

### Single replica.

Similarly, we set up hard distributions as uniform distribution on
signed Pauli operators $\{+1,-1\}\times \mathcal{O}$, where
$\mathcal{O} \subset \{\mathbb{I},X,Y,Z\}$. Follow the same procedure of
Eq.[\[eq:sig_canc_TVlb\]](#eq:sig_canc_TVlb){reference-type="eqref"
reference="eq:sig_canc_TVlb"}, we then calculate its rank-1 POVM leaves
likelihood as: $$\begin{align}
    \mathbb{E}_{s,P} L_{s,P}(l)  \geq \exp\left[-18\varepsilon^2T \sup_{\ket{\phi}} \mathbb{E}_{P\in \mathrm{Uniform}(\mathcal{O})} \bra{\phi} P \ket{\phi}^2\right].
\end{align}$$ In the case of $\mathcal{O} = \mathcal{P}_n$, we use the
identity
$$
\mathbb{E}_{P\in \mathrm{Uniform}(\mathcal{P}_n)} \bra{\phi} P \ket{\phi}^2 \\
=\bra{\phi}\bra{\phi} 4^{-n}\sum_{P\in \mathcal{P}_n}P \otimes P\ket{\phi}\ket{\phi}
$$
and
$\sum_{P\in \mathcal{P}_n}P \otimes P = 2^{n}\mathrm{SWAP}^{\otimes n}$.
We conclude that
$\mathbb{E}_{s,P} L_{s,P}(l) \geq e^{-18\varepsilon^2 T 2^{-n}},\forall l$.
Use Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"}, we conclude that for all choice of
single-copy POVM,
$\|p_{\mathbb{I}/d} - \mathbb{E}_{s,P}p_{\rho_{s,P}}\|_{\mathrm{tvd}} \leq 1 - e^{-18\varepsilon^2 T 2^{-n}}$.
This means that to reach confidence $1/2 + \delta/2$, we have to set
$1 - e^{-18\varepsilon^2 T 2^{-n}} \geq \delta \Rightarrow T \geq 18^{-1}\times 2^n \varepsilon^{-2}\ln(1 - \delta)$.

According to
Theorem [\[theo:mart_distinguish_lb\]](#theo:mart_distinguish_lb){reference-type="ref"
reference="theo:mart_distinguish_lb"}, we can also calculate its
$\chi$-squared divergence given ensemble $\mathcal{D}_\mathcal{O}$ on
the subset of Pauli operators $\mathcal{O}$: $$\begin{align}
    \delta_{\mathcal{D}_\mathcal{O}} &:= \max_{\{F_s\}_s \in \mathcal{M}}\mathbb{E}_{s \sim \mathrm{tr}(\rho F_{s})} \mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \left[\frac{\mathrm{tr}(\sigma_P F_{s})}{\mathrm{tr}(\rho F_{s})} - 1\right]^2= \max_{F_s \succ 0 }\sum_{s}  \frac{\mathrm{tr}(F_{s})}{d}\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \left[\frac{\mathrm{tr}(\frac{\mathbb{I} + 3\varepsilon P}{d}F_{s})}{\mathrm{tr}(F_{s})/d} - 1\right]^2 \notag\\
    &= 9\varepsilon^2 \max_{F_s \succ 0 }\sum_{s}  \frac{\mathrm{tr}(F_{s})}{d}\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \left[\frac{\mathrm{tr}({P}F_{s})}{\mathrm{tr}(F_{s})}\right]^2 = {9\varepsilon^2} \max_{F_s \succ 0 }\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \sum_{s} \frac{\left[\mathrm{tr}({P}F_{s})\right]^2}{{d}\cdot \mathrm{tr}(F_{s})}.
\end{align}$$ Since $F_s$ includes all the rank-1 POVMs and each POVMs
with rank greater than 1 can be equivalently realized using rank-1 POVMs
with undecreasing discrimination efficiency, as shown in
Lemma [\[lemma:POVM_r1_reduction\]](#lemma:POVM_r1_reduction){reference-type="ref"
reference="lemma:POVM_r1_reduction"}. We can plug in
$F_s = 2^{n}w_s \ket{\psi_s}\!\bra{\psi_s}$ with $\{w_s\}$ a valid
distribution and conclude the same result: $$\begin{align}
    \max_{F_s \succ 0 }\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \sum_{s} \frac{\left[\mathrm{tr}({P}F_{s})\right]^2}{{d}\cdot \mathrm{tr}(F_{s})} &= \max_{\ket{\psi_s}}\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} \sum_{s}w_s{\left[\bra{\psi_s}{P}\ket{\psi_s}\right]^2} = \max_{\ket{\phi}}\mathbb{E}_{P \sim \mathcal{D}_\mathcal{O}} {\bra{\phi}{P}\ket{\phi}^2} 
    \\
    &\sim \Omega(2^{-n}) \text{~if~} \mathcal{O} = \mathcal{P}_n, \mathcal{D}_{\mathcal{O}} = \mathrm{Uniform}(\mathcal{O}).
\end{align}$$ Then based on
Lemma [\[theo:mart_distinguish_lb\]](#theo:mart_distinguish_lb){reference-type="ref"
reference="theo:mart_distinguish_lb"}, $T\geq 2^n$. Note that such a
martingale analysis do not directly applied to purity-identity test,
which has a constant $\chi$-squared divergence, as calculated below:
$$\begin{align}
    \delta_{\mathrm{Haar}} &= \max_{F_s \succ 0 }\sum_{s}  \frac{\mathrm{tr}(F_{s})}{d}\mathbb{E}_{\ket{\psi}\sim \mathrm{Haar}} \left[\frac{\mathrm{tr}(\ket{\psi}\!\bra{\psi}F_{s})}{\mathrm{tr}(F_{s})/d} - 1\right]^2=\max_{F_s \succ 0 }\sum_{s}  \mathbb{E}_{\ket{\psi}} \left[\frac{\mathrm{tr}(\ket{\psi}\!\bra{\psi}^{\otimes 2}F_{s}\otimes F_{s})}{\mathrm{tr}(F_{s})/d}\right]- 1\\
    &=\max_{\ket{\psi_s} }\sum_{s}   d^2w_s\mathbb{E}_{\ket{\psi}} \left[{\mathrm{tr}({\psi}^{\otimes 2} \psi_s^{\otimes 2})}\right]- 1 = \frac{2d^2}{d(d+1)} - 1 = \frac{d-1}{d+1} \sim \Omega(1).
\end{align}$$ This great difference between ensemble supports on
$\{(\mathbb{I}+ 3\varepsilon O)/2^n\}_{O \in \mathcal{O}}$ and Haar
random state supports on $\{\psi\}$ is because the probability of the
latter one is more concentrated. $$\begin{align*}
    p_{\mathrm{Haar}}(\psi_s) =\frac{\mathrm{tr}(\ket{\psi}\!\bra{\psi}\psi_{s})}{\mathrm{tr}(\mathbb{I}/d\cdot \psi_{s})}= d |\langle {\psi}|{\psi_s}\rangle|^2 \in[0,d], \, p_{\mathcal{P}}(\psi_s) =\frac{\mathrm{tr}(\frac{\mathbb{I} + 3\varepsilon P}{d}\psi_{s})}{\mathrm{tr}(\mathbb{I}/d\psi_{s})}=1 + 3\varepsilon\langle{\psi_s}|P|{\psi_s}\rangle \in [1- 3\varepsilon, 1+ 3\varepsilon].
\end{align*}$$

### Single replica with Clifford restriction.

### $c \geq 2$ replica with bounded quantum memory.

## Haar-assembled ensembles and its distinguishablity

### Properties of Haar-assembled ensembles

The lower bound of many problem are find by first reduce this problem to
distinguishing one specific state with a state ensemble. One useful
state ensembles are constructed from reducing Haar random state.

::: {.callout-note icon="false"}
## Definition

Given a $D = 2^{n + \log(1/\varepsilon)} = d\cdot \varepsilon^{-1}$
dimensional Haar random state $\ket{H} \sim \mathrm{Haar}(D)$. The
$2^n$-dimensional reduced Haar-induced (**RH**) state is defined as
$\mathcal{E}_{\varepsilon}:=\{\text{tr}_{>n} \ket{H}\!\bra{H}\}_{\ket{H} \sim \mathrm{Haar}(D)}$.
:::

Depending on the scale of reduced parts, the $RH$-ensemble has tunable
purity. We then show in
Lemma [\[lemma:purity_of_RH\]](#lemma:purity_of_RH){reference-type="ref"
reference="lemma:purity_of_RH"} that the random variable
$\mathrm{tr}(\rho^2), \rho \sim \mathcal{E}^{\mathrm{RH}}_{\varepsilon}$
is well concentrated and separate from maximum mixed state purity $1/d$.
This statement is useful to proving the reduction of
$\mathrm{tr}(\rho^2)$ problem.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:purity_of_RH label="lemma:purity_of_RH"} The $c$-copy average
of $\rho \in \mathcal{E}_{\varepsilon}$ writes: $$\begin{align}
        \mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} \rho^{\otimes c} = \frac{1}{D^{\uparrow c}}\sum_{\pi \in S_c} \varepsilon^{-c(\pi)}\mathbb{P}_{\pi}^{d}.
\end{align}$$ Furthermore, its purity average and variance writes:
$$\begin{align}
        \mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} \mathrm{tr}(\rho^2) = \frac{2^n\varepsilon + 1}{2^n + \varepsilon},\quad \mathrm{Var}_{\rho \sim \mathcal{E}_{\varepsilon}} [\mathrm{tr}(\rho^2)] = \frac{2(2^{2n} - 1)(1/\varepsilon^2-1)}{(2^n/\varepsilon + 1)^2 (2^n/\varepsilon+2)(2^n/\varepsilon+3)}.
\end{align}$$
:::

:::: proof
*Proof.* On going proof\... $$\begin{align}
        \mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}}\rho^{\otimes c}&=\mathbb{E}_{H \sim \mathrm{Haar}(D)}(\text{tr}_{>n} \ket{H}\!\bra{H})^{\otimes c} = \frac{1}{D^{\uparrow c}}\mathrm{tr}_{>n}(\sum_{\pi \in S_c} \mathbb{P}_{\pi}^{d} \otimes \mathbb{P}_{\pi}^{\varepsilon^{-1}})=\frac{1}{D^{\uparrow c}}\sum_{\pi \in S_c} \varepsilon^{-c(\pi)}\mathbb{P}_{\pi}^{d}.
\end{align}$$ Then the average of purity can be directly calculate as
$$\begin{align}
    \mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} \mathrm{tr}(\rho^2)
    &=\mathrm{tr}\left(\frac{\varepsilon^{-2} \mathbb{I}_{n}^{\otimes 2}+\varepsilon^{-1} \mathrm{SWAP}^{\otimes n}}{D(D+1)} \cdot \mathrm{SWAP}^{\otimes n}\right) = \frac{\varepsilon^{-2} 2^n + \varepsilon^{-1} 2^{2n}}{2^n\varepsilon^{-1}(2^n \varepsilon^{-1}+1)}= \frac{2^n\varepsilon + 1}{2^n + \varepsilon},\\
    \mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} [\mathrm{tr}(\rho^2)]^2&=\mathrm{tr}\left(\frac{ \sum_{\pi \in S_4}{\varepsilon^{-c(\pi)}\mathbb{P}_{\pi}^{d}}}{D(D+1)(D+2)(D+3)}\mathbb{P}_{(12)(34)}^{d}\right)=\frac{\sum_{\pi \in S_4}d^{c(\pi \cdot (12)(34))}(1/\varepsilon)^{c(\pi)}}{D(D+1)(D+2)(D+3)}.
\end{align}$$ Here $c(\pi)$ count the number of cycles for permutation
$\pi$. To calculate this value, we classify the $S_4$ group as shown in
Table [1.1](#tab:S4_terms){reference-type="ref"
reference="tab:S4_terms"}. Through denoting
$d_A = 2^n, d_B = 1 / \varepsilon$, $D = d_Ad_B$. We get the results
$$\begin{align}
        \mathrm{Var}_{\rho \sim \mathcal{E}_{\varepsilon}} [\mathrm{tr}(\rho^2)] &= \frac{d_A^2 d_B^4+2 d_A^3 d_B^3+5 d_A d_B^3+10 d_A^2 d_B^2+5 d_A^3 d_B+d_A^4 d_B^2}{(d_Ad_B)(d_Ad_B+1)(d_Ad_B+2)(d_Ad_B+3)} - \frac{(d_A + d_B)^2}{(d_Ad_B+1)^2}\notag\\
        &= \frac{2d_B\left[1 + d_A^3 - 2d_A -d_B +d_Ad_B\right]}{(d_Ad_B + 1)^2 (d_Ad_B+2)(d_Ad_B+3)} = \frac{2/\varepsilon\left[1 + 2^{3n} - 2^{2n+1} - 1/\varepsilon +2^n/\varepsilon\right]}{(2^n/\varepsilon + 1)^2 (2^n/\varepsilon+2)(2^n/\varepsilon+3)}
\end{align}$$

::: {#tab:S4_terms}
  **$\pi$**                                                         **number**   **$c(\pi)$**  **$\pi \cdot (12)(34)$**                                          **$c(\pi \cdot (12)(34))$**  **summation**
  ---------------------------------------------------------------- ------------ -------------- ---------------------------------------------------------------- ----------------------------- -----------------
  $e$                                                                   1             4        (12)(34)                                                                       2               $d_A^2 d_B^4$
  (12),(34),                                                         $C_4^2$          3        (34),(12)                                                                      3               $2 d_A^3 d_B^3$
  4-6 (13),(14),(23),(24)                                                                      (1432),(1342),(1243),(1342)                                                    1               $4 d_A d_B^3$
  $\substack{(123),(321),(124),(421),\\(134),(431),(234),(432)}$     $2C_4^3$         2        $\substack{(243),(143),(213),(421),\\(134),(431),(234),(432)}$                 2               $8 d_A^2 d_B^2$
  $\substack{(1234),(1243),(1324),\\(1342),(1423),(1432)}$            (4-1)!          1        \(13\)                                                                         3               $6 d_A^3 d_B$
  $\substack{(12)(34),}$                                                3             2        $e$                                                                            4               $d_A^4 d_B^2$
  4-6 $\substack{(13)(24),(14)(23)}$                                                           $(14)(23)$                                                                     2               $2 d_A^2 d_B^2$

  : Classification of $S_4$ to calculate
  $\sum_{\pi \in S_4}(d_A)^{c(\pi \cdot (12)(34))}(d_B)^{c(\pi)}$
:::

 ◻
::::

State ensembles can also be constructed from mixing independent Haar
random state.

::: {.callout-note icon="false"}
## Definition

[]{#def:MH_ensemble label="def:MH_ensemble"} Given a probability
$\{p_r\}_{r = 0}^{m}$, defined the multi-variant Haar ensemble (**MH**)
as the mix states
$\mathcal{E}^{\mathrm{MH}}_{\mathbf{p}}:=\{p_0 {\mathbb{I}(d)}/{d} + \sum_{j = 1}^{m} p_j \psi_j\}_{\psi_j \sim \mathrm{Haar}(d)}$.
:::

As a generalization of
Lemma [\[lemma:purity_of_RH\]](#lemma:purity_of_RH){reference-type="ref"
reference="lemma:purity_of_RH"}, we then try to conclude that for an
arbitrary k-replica operator $O$, it is possible to construct two
**MH**-ensemble
$\mathcal{E}^{\mathrm{MH}}_{\mathbf{p}},\mathcal{E}^{\mathrm{MH}}_{\mathbf{q}}$
such that
$\{\mathrm{tr}(O\rho^k)\}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{p}}}$
and
$\{\mathrm{tr}(O\rho^k)\}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{q}}}$
are well separated and both well concentrated. To prove this, we rewrite
the k-replica of **MH**-ensembles as $$\begin{align}
    \mathcal{E}^{\mathrm{MH},\otimes k}_{m} = \left\{\sum_{A_0 \cup \cdots \cup A_m = \{1,\cdots,k\}}\left(p_0^{|A_0|}\prod_{r = 1}^{m} p_r^{ |A_r|}\right)\cdot \psi^{\otimes A_1}_1 \otimes \cdots \otimes \psi^{\otimes A_m}_m \otimes \left(\frac{\mathbb{I}(d)}{d}\right)^{\otimes A_0}\right\}_{\psi_r \sim \mathrm{Haar}(d)},\label{eq:k_rep_MH}
\end{align}$$ where $A_0 \cup \cdots \cup A_m = \{1,\cdots,k\}$ go over
all $(m+1)$-partition of $k$ elements and $\psi_r^{A_r}$ means
distributing state $\psi_r$ at elements within $A_r$. If we use
$j = (A_1,\cdots,A_m,A_0)$ to denote a partition of $\{1,\cdots,k\}$ and
$p_j = p_0^{|A_0|}\prod_{r = 1}^{m} p_r^{ |A_r|}$ to denote the mixing
rate, and use unitary $U_j$ to sort the qudits in an order such that
$\psi_1,\psi_2,\cdots,\psi_m$ supports on
$\{1,\cdots,|A_1|\},\{|A_1|+1,\cdots,|A_1|+|A_2|\}, \cdots,\{|A_{m}|+1,\cdots,k\}$
respectively, we get the extended Haar-induced ensemble below.

::: {.callout-note icon="false"}
## Definition

[]{#def:EHI_ensemble label="def:EHI_ensemble"} Given $m$ Haar random
state $\{\psi_1,\cdots,\psi_m\}$, each with dimension $d_1,\cdots,d_m$,
multiplicity parameter
$\mathbf{a} \in (\mathbb{Z}_+)^{m} =(a_1,\cdots,a_m)$, and the
r-dimensional complement state $\tau$ such that
$\sum_{k=1}^m a_k\cdot d_k + r  = D$. A $D$-dimensional
$(\mathbf{a}^{(j)}, \tau^{(j)})$ extended Haar-induced (**EH**) ensemble
is an ensemble of $D$-dimensional mixed state that is specified by a
$\mathcal{U} := \{p_j,U_j\}_{j = 1}^J$ unitary mixing of D-dimensional
pure state
$\psi_1^{\otimes a_1} \otimes \cdots\otimes \psi_m^{\otimes a_m} \otimes \tau$,
written as $$\begin{align}
        \mathcal{E}_{\mathcal{U},\mathbf{a}, \tau} := \{\sum_{j= 1}^J p_j U_j \psi_1^{\otimes a^{(j)}_1} \otimes \cdots\otimes \psi_m^{\otimes a^{(j)}_m} \otimes \tau^{(j)} U_j^\dagger\}_{\psi_k \sim \mathrm{Haar}(d_k)}.
\end{align}$$
:::

Thus, it is sufficient to prove that
$\mathrm{tr}(O\sigma), \sigma \sim \mathcal{E}^{\mathrm{EH}}_{\mathbf{a}}$
is separated and concentrated. For the separated part, we prove the
lemma below

::: {.callout-important icon="false"}
## Lemma

Suppose
$\forall i= 1,\cdots,k, \sum_{r = 1}^m p_r^{i} = \sum_{r = 1}^m q_r^{i}$
and $p_0 = q_0$, the multi-variant Haar induced ensemble
$\mathcal{E}^{\mathrm{MH}}_{\mathbf{p}}$ and
$\mathcal{E}^{\mathrm{MH}}_{\mathbf{q}}$ satisfied $$\begin{align}
        &\forall i= 1,\cdots,k, \mathbb{E}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{p}}} \rho^i - \mathbb{E}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{q}}} \rho^i = 0\\
        &\mathbb{E}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{p}}} \rho^{k+1} - \mathbb{E}_{\rho \sim \mathcal{E}^{\mathrm{MH}}_{\mathbf{q}}} \rho^{k+1} = (\sum_{r=1}^m p_r^{k+1} - \sum_{r=1}^m q_r^{k+1}) \Delta_{k+1}\\
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Refer to
Eq. [\[eq:k_rep_MH\]](#eq:k_rep_MH){reference-type="eqref"
reference="eq:k_rep_MH"}, we conclude that ◻
:::

Then we show the lemma below for the bound of specific $O$

::: {.callout-important icon="false"}
## Lemma

Given $k+1$ qudit operator $O$, then $$\begin{align}
        \left|\sum_{\pi \in S_{k+1}^{\mathrm{circ}}} c_{\pi} (O) - \mathrm{tr}(O \Delta_{k+1})\right| \leq \frac{(k+1)^{2k}}{d}.
\end{align}$$
:::

For the second parts, we prove the following Lemma, as a generalization
of Levy's Lemma.

::: {.callout-important icon="false"}
## Lemma

$$\begin{align}
        \mathrm{Pr}_{\sigma \sim \mathcal{E}^{\mathrm{EH}}_{\mathcal{U},\mathbf{a}, \tau}}\left(\left|\mathrm{tr}(O \sigma) - \mu\right| > t\right) \leq 2 \sum_{r =1}^m e^{-\frac{d_r t^2}{18\pi^3m^2a_r^2\|O\|^2_{\infty}}}
\end{align}$$
:::

### Pure-Identity test[]{#subsec:Pure_id_test label="subsec:Pure_id_test"}

Perhaps the most simple one are the maximum mixed state
$\mathbb{I}(d)/d$ with all possible pure state $\ket{\psi}$.

::: problem
[]{#prob:2k_PItest label="prob:2k_PItest"} Design an algorithm using
restrained measurements that, given access to a device guaranteed to
prepare a state that is either (i)one of pure states $\ket{\psi}$ or
(ii) the maximally mixed state $d^{-1}\mathbb{I}$, can distinguish
between these two cases with an error of at most $1/2-\varepsilon$.
:::

Based on
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, in the following we relax the problem
with a problem ensemble $\ket{\psi} \sim \mathrm{Haar}(d)$. This
reduction is sufficient, while not fully characterize the hardness of
pure-identity test. To fully pinned down the hardness, ones should build
arbitrary ensemble on pure states and check the hardness. Thus,

### The 1-replica strategy.

We first consider the 1-replica restriction on measurements.

For a $T$-round 1-replica adaptive strategy
$M_s = F^{u_1}_{s_1} \otimes \cdots \otimes F^{u_T}_{s_T}$, we use
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"} and lower bounds its leaves' likelihood:
$$\begin{align}
    \mathbb{E}_{\psi} L_{\psi} = \mathbb{E}_{{\psi} \sim \mathrm{Haar}(d)}\frac{d^{T}\mathrm{tr}(M_s \ket{\psi}\!\bra{\psi}^{\otimes T})}{\mathrm{tr}(M_s)} = \frac{d^T}{d(d+1)\cdots(d+T-1)}  \frac{\mathrm{tr}\left(\sum_{\pi \in S_T}\mathbb{P}^d_{\pi} \cdot M_s\right)}{\mathrm{tr}\left( \bigotimes_{t = 1}^T\left[\mathbb{I}(d)\right]\cdot M_s\right)}.\label{eq:midres_1repPItest}
\end{align}$$ To do this, we upper bounds each term in the RHS of
Eq.[\[eq:midres_1repPItest\]](#eq:midres_1repPItest){reference-type="eqref"
reference="eq:midres_1repPItest"}. For the constant, we conclude that
$$\begin{align}
    \frac{d^T}{d(d+1)\cdots(d+T-1)}&=\left(1 \cdot (1+\frac{1}{d})\cdots(1+\frac{T-1}{d})\right)^{-1}\geq (1 + T/d)^{-T} \notag \\
    &=e^{-T\ln(1 + T/d)} \geq e^{-T^2/d}. \label{eq:lb_upfrac}
\end{align}$$ For the second term, we decomposed $M_s$ into its
eigenvector through defining
$F_{s_j}^{u_j} =\sum_{s}\lambda_{j,s}{v_{j,s}}$ with
$\lambda_{j,s_j}\geq 0$ and writes $$\begin{align}
    {\mathrm{tr}\left(\sum_{\pi \in S_T}\mathbb{P}^d_{\pi} \cdot M_s\right)} &= T!\cdot\sum_{s_1,\cdots,s_T}\lambda_{1,s_1}\cdots\lambda_{T,s_T} \mathrm{tr}\left(\Pi_{sym}{v_{1,s_1} \otimes\cdots\otimes v_{T,s_T}}\right)\\
    &\geq \sum_{s_1,\cdots,s_T}\lambda_{1,s_1}\cdots \lambda_{T,s_T}={\mathrm{tr}\left( \bigotimes_{t = 1}^T\left[\mathbb{I}(d)\right]\cdot M_s\right)}
\end{align}$$ Here in the second line we show the lemma below:

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:sym_prod_lb label="lemma:sym_prod_lb"} For $T$ numbers of
$d$-qudit pure states $\ket{\psi_1}, \cdots,\ket{\psi_T}$ and the
symmetrization projector
$\Pi_{\mathrm{sym},T} := (T!)^{-1}\sum_{\pi \in S_T} \mathbb{P}^{d}_{\pi}$,
we conclude that
$\text{tr}\left(\Pi_{\mathrm{sym},T}\bigotimes_{t = 1}^T \ket{\psi_t} \!\bra{\psi_t}\right) \geq (T!)^{-1}.$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

Thus, we conclude that
$max_{\{M_s = \otimes_{t=1}^{T}F_{s_t}^{u_t}\}_s}\|p_{\mathbb{I}} - p_{\psi}\|_{\mathrm{TV}} \leq 1 - \min_{\{M_s\}_s, s} \mathbb{E}_{\psi} L_{\psi}(s) \leq 1 - e^{-T^2/d} \leq T^2/d$
based on the first equation in
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"}. This means that to reach success rate
$1/2 + \varepsilon$, $T^2/d \geq 2\varepsilon$ must be satisfied, thus
gives $T \geq \mathcal{O}({\sqrt{d}})$.

### The 2-replica strategy with $k$-memory.

Now we consider a fine-tuned setting of the measurement restriction. We
consider $d = 2^n$ as $n$-qubits and allow 2-replica measurements but
restrained on the $\{M_s\}_s \subset \mathcal{M}_{2,n}^k$ as defined in
definition [\[def:crep_kmem_POVMs\]](#def:crep_kmem_POVMs){reference-type="ref"
reference="def:crep_kmem_POVMs"}. Similar to the 1-replica analysis, we
first write its Haar-average leaf likelihood $$\begin{align}
    \mathbb{E}_{\psi} L_{\psi} &= \mathbb{E}_{{\psi} \sim \mathrm{Haar}(d)}\frac{d^{2T}\mathrm{tr}(M_s \ket{\psi}\!\bra{\psi}^{\otimes 2T})}{\mathrm{tr}(M_s)} = \frac{d^{2T}}{d(d+1)\cdots(d+2T-1)}  \frac{\mathrm{tr}\left(\sum_{\pi \in S_{2T}}\mathbb{P}^d_{\pi} \cdot M_s\right)}{\mathrm{tr}\left( \bigotimes_{t = 1}^T\left[\mathbb{I}(d)\right]\cdot M_s\right)}\\
    &\geq e^{-4d^{-1}T^2}\cdot \frac{\mathrm{tr}\left(\sum_{\pi \in S_{2T}}\mathbb{P}^d_{\pi} \cdot M_s\right)}{\mathrm{tr}\left( S_2^{\otimes T}\cdot M_s\right)} \cdot\prod_{t = 1}^T \frac{\mathrm{tr}\left(\sum_{\pi \in S_2}\mathbb{P}^d_{\pi} \cdot F_{s_t}^{u_t}\right)}{\mathrm{tr}\left(F_{s_t}^{u_t}\right)}\\
    &\geq (1{-4d^{-1}T^2})\cdot \prod_{t = 1}^T \frac{\mathrm{tr}\left(\sum_{\pi \in S_2}\mathbb{P}^d_{\pi} \cdot F_{s_t}^{u_t}\right)}{\mathrm{tr}\left(F_{s_t}^{u_t}\right)}\geq (1{-4d^{-1}T^2})\left(\frac{2^{2n}}{2^n(2^n+1)}\right)^T \prod_{t = 1}^T \frac{\mathrm{tr}\left(\sum_{\pi \in S_2}\mathbb{P}^d_{\pi} \cdot F_{s_t}^{u_t}\right)}{\mathrm{tr}\left(F_{s_t}^{u_t}\right)} \label{eq:2rep_kmemo_leaflike}
\end{align}$$ Here in the second line we do the same calculation of
Eq.[\[eq:lb_upfrac\]](#eq:lb_upfrac){reference-type="eqref"
reference="eq:lb_upfrac"} and insert a value
$\mathrm{tr}\left( S_2^{\otimes T}\cdot M_s\right)$ in the denominator.
The third line is bounded by
Lemma [\[lemma:sepa_S_smaller\]](#lemma:sepa_S_smaller){reference-type="ref"
reference="lemma:sepa_S_smaller"} below, as a generalization of
Lemma [\[lemma:sym_prod_lb\]](#lemma:sym_prod_lb){reference-type="ref"
reference="lemma:sym_prod_lb"}.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:sepa_S_smaller label="lemma:sepa_S_smaller"} Given a
semi-positive operator $F = F_A \otimes F_B$ that separable on set of
qudits $A$ and qudits $B$. Denote
$S_a = \sum_{\pi \in S_{|A|}} \mathbb{P}_{\pi}^{d}$ and similar for
$S_B,S_{A+B}$. Then
$\mathrm{tr}\left({S_A \otimes S_B F}\right) \leq \mathrm{tr}\left({S_{A+B}F}\right)$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

For the second inequality in
Eq. [\[eq:2rep_kmemo_leaflike\]](#eq:2rep_kmemo_leaflike){reference-type="eqref"
reference="eq:2rep_kmemo_leaflike"}, we noted that if we use
$M_s = \otimes_{t = 1}^T F_{s_t}^{u_t}$ to discriminate
$\rho = \mathbb{I}(d^2)/d^2$ and
$\sigma = [2^n(2^n+1)]^{-1}(\mathbb{I}_n^{\otimes 2} + \mathrm{SWAP}^{\otimes n})$
in the 2-replica space $\mathcal{H}(d^2)$, the likelihood function
satisfied: $$\begin{align}
    L'(s) =\left(\frac{2^{2n}}{2^n(2^n+1)}\right)^T \prod_{t = 1}^T \frac{\mathrm{tr}\left(\sum_{\pi \in S_2}\mathbb{P}^d_{\pi} \cdot F_{s_t}^{u_t}\right)}{\mathrm{tr}\left(F_{s_t}^{u_t}\right)}.
\end{align}$$ It is thus sufficient to show a upper bound for $L'$.
Refer to
Lemma [\[lemma:UB_Ltail\]](#lemma:UB_Ltail){reference-type="ref"
reference="lemma:UB_Ltail"}, we consider the chi-squared divergence with
$\rho$ and $\sigma$. $$\begin{align}
    \delta_{\mathcal{M},\rho,\sigma}&=\max_{\{F_s\}_s \in \mathcal{M}^{k}_{2,n}}\sum_{s}\frac{\mathrm{tr}(F_{s})}{4^n}\left[\frac{2^{n}\mathrm{tr}\left[(\mathbb{I}_n^{\otimes 2} + \mathrm{SWAP}^{\otimes n})F_{s}\right]}{(2^n+1)\mathrm{tr}(F_{s})} - 1\right]^2 \notag\\
    &=\max_{\{F_s\}_s \in \mathcal{M}^{k}_{2,n}}\sum_{s} \frac{\mathrm{tr}(F_s)}{4^n}(2^n+1)^{-2}\left[2^n \frac{\mathrm{tr}(\mathrm{SWAP}^{\otimes n} F_s)}{\mathrm{tr}(F_s)} - 1\right]^2\notag\\
    &=\max_{\{F_s\}_s \in \mathcal{M}^{k}_{2,n}}\frac{1}{4^n}(2^n+1)^{-2}\left[4^n \sum_{s} \frac{[\mathrm{tr}(\mathrm{SWAP}^{\otimes n} F_s)]^2}{\mathrm{tr}(F_s)} - 2 \times 2^n {\mathrm{tr}\left(\mathrm{SWAP}^{\otimes n}\sum_{s}F_s\right)} + \mathrm{tr}\left(\sum_{s}F_s\right)\right]\notag\\
    &=\frac{1}{(2^n+1)^{2}}\left[\max_{\{F_s\}_s \in \mathcal{M}^{k}_{2,n}} \sum_{s} \frac{[\mathrm{tr}(\mathrm{SWAP}^{\otimes n} F_s)]^2}{\mathrm{tr}(F_s)} - 1\right].
\end{align}$$ Here in the last line, we use
$\sum_{s} F_s = \mathbb{I}_{2n}$ and
$\text{tr}(\mathrm{SWAP}^{\otimes n}) = 2^n$. If Bell measurements
$F_{\mathbf{s}} = \Phi_{\mathbf{s}}$ is allowed, we can verify that
$\sum_{\mathbf{s}}[\mathrm{tr}(\mathrm{SWAP}^{\otimes n} \Phi_{\mathbf{s}})]^2/{\mathrm{tr}(\Phi_{\mathbf{s}})} = 4^n$.
However, the $k$-memeory restriction on $F_s$ prevent this measurement
and imposed a upper bound on the MPS-rank of projected basis, as
depicted in
Lemma [\[lemma:lowMPS_SWAPproduct\]](#lemma:lowMPS_SWAPproduct){reference-type="ref"
reference="lemma:lowMPS_SWAPproduct"}. This lower bounds the maximum
value as $\delta_{\mathcal{M},\rho,\sigma}  \leq 2^{k-n} - 2^{-2n}$.
Based on
Lemma [\[lemma:UB_Ltail\]](#lemma:UB_Ltail){reference-type="ref"
reference="lemma:UB_Ltail"}, we conclude that
$\mathrm{Pr}_{l \sim p_{\mathbb{I}, \mathcal{T}}}(L'(l) \geq 1 - c_1) \geq 1 - c_2 - c_3\cdot (2^{k-n} - 2^{-2n})T$.
Then plug into
Eq.[\[eq:2rep_kmemo_leaflike\]](#eq:2rep_kmemo_leaflike){reference-type="eqref"
reference="eq:2rep_kmemo_leaflike"} to replace $L'$ by
$\mathbb{\psi}L_{\psi}$, we conclude that
$\forall c_1\in (0,1/3), c_2 > 0, \exists c_3>0$ such that
$\mathrm{Pr}_{l \sim p_{\mathbb{I}, \mathcal{T}}}\left[\mathbb{E}_{\psi} L_{\psi}(l) \leq (1{-4d^{-1}T^2})(1 - c_1)\right] \leq c_2 + c_3\cdot (2^{k-n} - 2^{-2n})T.$
Finally, using the second identity in
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"} for $a$ being a unique element with
$p^{(a)} = \mathbb{E}_{\psi} p_{\psi, \mathcal{T}}$, we must have
$$\begin{align}
    2\varepsilon \leq \|p_{\mathbb{I}, \mathcal{T}} - \mathbb{E}_{\psi} p_{\psi, \mathcal{T}}\|_{\mathrm{TV}} 
    &\leq c_2 + c_3\cdot (2^{k-n} - 2^{-2n})T + 1 - (1{-4\times 2^{-n}T^2})(1 - c_1)
\end{align}$$ Without lose of generality, we set $\varepsilon = 1/6$,
i.e., to be $1/6$ better than random guessing. We have
$0.2 +  2\gamma T ( -2^{-2n} + 2^{k - n})+3.6\times 2^{-n} T^2 > 1/3$,
where we take $c_1= c_2 = 0.1,c_3 = \gamma>0$. This gives the inequality
$$\begin{align}
\label{eq:T_ineq}
    T^2 + \frac{\gamma(-2^{-n} + 2^k)}{1.8} T - \frac{2^n}{54} >0.
\end{align}$$ We conclude that there exist constants $a_1,a_2$ that
satisfy
$0<a_1 < a_2 \leq (1/2)\cdot [\sqrt{(\gamma /1.8)^2 + 1/9} - \gamma/1.8]$,
such that $T > \min\{a_12^{n/2}, a_22^{n-k}\}$ must be satisfied
otherwise $$\begin{align}
    LHS \leq a_1^2 2^n + \frac{\gamma }{1.8}(a_2 2^n) - \frac{2^n}{54}\leq (a_1^2 + \gamma \frac{a_2}{1.8}-1/54)2^n<(a_2^2 +  \frac{\gamma}{1.8}a_2-1/54)2^n < 0,
\end{align}$$ which is contradictory with
Eq. [\[eq:T_ineq\]](#eq:T_ineq){reference-type="eqref"
reference="eq:T_ineq"}. This proves the lower bound
$T \geq \Omega(\min\{2^{n/2}, 2^{n-k}\})$ for the 2-copy k-memory
adaptive strategy that solve the purity-identity test problem with $2/3$
correct rate.

### **MH**-ensemble test.

Now we consider a general case where we supposed to distinguish an
arbitrary element within **MH** ensemble from its average.

::: problem
[]{#prob:MHtest label="prob:MHtest"} Design an algorithm that
distinguishes between two cases below using restrained measurements at
error rate less than $1/2-\varepsilon$. (i)One of state within
$\mathcal{E}_{p} := \{p_0 {\mathbb{I}(d)}/{d} + \sum_{j = 1}^{m} p_j \psi_j\}$
or (ii) One of state within
$\mathcal{E}_{q}:=\{q_0 {\mathbb{I}(d)}/{d} + \sum_{j = 1}^{m} q_j \psi_j\}$
:::

It is easy to check that pure-identity test in
Problem [\[prob:2k_PItest\]](#prob:2k_PItest){reference-type="ref"
reference="prob:2k_PItest"} is a special case of
Problem [\[prob:MHtest\]](#prob:MHtest){reference-type="ref"
reference="prob:MHtest"}, with $p_1 = 1, p_m = 0,\forall m \neq 1$ and
$q_0 = 1, q_m = 0,\forall m \neq 0$. However, this problem might be too
hard, as $\mathcal{E}_{p} \cap \mathcal{E}_{q}\neq \emptyset$ if there
exist a distribution $\lambda$ such that
$\lambda \succ \{p_j/(1 - p_0)\}_j$ and
$\lambda \succ \{q_j/(1-q_0)\}_j$. We thus relax this problem by setting
the problem ensemble as
$\psi_{j} \sim \mathrm{Haar}(d), \forall j=1,\cdots,m$. To further fix
this testing problem, we also imposed the rank-$k$ condition:
$$\begin{align}
    \mathbb{E}_{\psi_j\sim \mathrm{Haar}(d)} \left(p_0 {\mathbb{I}(d)}/{d} + \sum_{j = 1}^{m} p_j \psi_j\right)^{\otimes k} = \mathbb{E}_{\psi_j\sim \mathrm{Haar}(d)} \left(q_0 {\mathbb{I}(d)}/{d} + \sum_{j = 1}^{m} q_j \psi_j\right)^{\otimes k}
\end{align}$$

### The $k$-replica strategy.

We directly discuss its lower bound under the $k$-replica measurement
restrictions.

### **EH**-ensemble test.

::: problem
[]{#prob:EAtest label="prob:EAtest"} Design an algorithm using
restrained measurements to distinguish between two cases below with an
error no more than $1/2-\varepsilon$.(i)one of the states
$\rho \in  \mathcal{E}_{\mathcal{U},\mathbf{a},\tau}$ or (ii) the
average mixed state
$\mathbb{E}_{\rho \sim \mathcal{E}_{\mathcal{U},\mathbf{a},\tau} }\rho$.
:::

Suppose we adapt the adaptive strategy $\mathcal{T}$ with corresponding
measurement $M_s = F^{u_1}_{s_1}\otimes \cdots \otimes F^{u_T}_{s_T}$,
the measurement results give two distribution: $$\begin{align}
    p_0(s) = \mathrm{tr}\left[ M_s \sum_{\mathbf{j} \in [J]^T}\left(\prod_{t = 1}^T p_{j_t}\right) \bigotimes_{t=1}^{T} \mathbb{E}{\sigma_{j_t}}\right],\quad
    p_{\psi_1,\cdots,\psi_m}(s) = \mathrm{tr}\left[ M_s \sum_{\mathbf{j} \in [J]^T}\left(\prod_{t = 1}^T p_{j_t}\right) \bigotimes_{t=1}^{T} {\sigma_{j_t}}\right],
\end{align}$$ where we use abbreviation
$\sigma_{j_t} = U_{j_t} \psi_{1}^{\otimes a_{1}^{(j_t)}} \otimes \cdots \otimes \psi_{m}^{\otimes a_{m}^{(j_t)}} \otimes \tau^{(j_t)} U_{j_t}^\dagger$
and
$\mathbb{E}\sigma_{j_t} = \mathbb{E}_{\psi_j \sim \mathrm{Haar}(d_j)} U_{j_t} \psi_{1}^{\otimes a_{1}^{(j_t)}} \otimes \cdots \otimes \psi_{m}^{\otimes a_{m}^{(j_t)}} \otimes \tau^{(j_t)} U_{j_t}^\dagger$.
Lower bounding the
problem [\[prob:EAtest\]](#prob:EAtest){reference-type="ref"
reference="prob:EAtest"} require the analysis of the similarity between
the distribution $p_{0}$ and $\{p_{\psi_1,\cdots,\psi_m}\}_{\psi_j}$.
Based on
Lemma [\[lemma:mult_TV_bound\]](#lemma:mult_TV_bound){reference-type="ref"
reference="lemma:mult_TV_bound"}, we choose
$\psi_k \sim \mathrm{Haar}(d_k)$. Then we remove the effects of mixing
probability $p_j$ in the **EH**-ensemble through the inequality
$$\begin{align}
    \|p_{0} - \mathbb{E}p_{\psi_1,\cdots,\psi_m}\|_{\mathrm{TV}} \leq \sum_{j_1,\cdots,j_T \in [J]}\left(\prod_{t = 1}^T p_{j_t}\right) \|q_{0,\mathbf{j}} -  \mathbb{E}q_{\psi_1,\cdots,\psi_m,\mathbf{j}}\|_{\mathrm{TV}}.
\end{align}$$ It is sufficient to find an upper bound of
$\|q_{0,\mathbf{j}} -  \mathbb{E} q_{\psi_1,\cdots,\psi_m,\mathbf{j}}\|_{\mathrm{TV}}$
for an arbitrary fixed choice of $\mathbf{j}$. The probability
$q_{0,\mathbf{j}} = \mathrm{tr}\left[ M_s \bigotimes_{t=1}^{T} \mathbb{E}{\sigma_{j_t}}\right]$
and
$q_{\psi_1,\cdots,\psi_m,\mathbf{j}} = \mathrm{tr}\left[ M_s \bigotimes_{t=1}^{T} {\sigma_{j_t}}\right]$
are the measurement results distribution with testing strategy
$\{M_s\}_s$ for two different input states. Defining
$V = U_{j_1}\otimes \cdots \otimes U_{j_T}$, an $m \times T$ matrix
$\mathbf{A}$ with
$A_{k,t} := a_{k}^{(j_t)}, {A}_{r,:} = a_{r}^{(j_1)} +\cdots+ a_{r}^{(j_T)}$,
and $\zeta = \bigotimes_{t = 1}^T \tau^{(j_t)}$, this reduces the
**EH**-ensemble to a two-state discrimination problem.

::: problem
[]{#prob:reduced_EAtest label="prob:reduced_EAtest"} Design an algorithm
using restrained single-replica measurements that can distinguish
between these two states below with an error of at most
$1/2-\varepsilon$: (i)
$\rho_{\mathbf{j}} =V \left[\mathbb{E} \psi_1^{\otimes A_{1,:}} \otimes \cdots\otimes \psi_m^{\otimes A_{m,:}} \otimes \xi \right] V^\dagger$
or (ii)
$\sigma_{\mathbf{j}} = V \left[\bigotimes_{t = 1}^T \left(\mathbb{E} \psi_{1}^{\otimes A_{1,t}} \otimes \cdots \otimes \psi_{m}^{\otimes A_{m,t}} \right) \otimes \xi \right] V^\dagger$.
:::

by the virtue of the first inequality in
Lemma [\[lemma:UB_TVD\]](#lemma:UB_TVD){reference-type="ref"
reference="lemma:UB_TVD"} and it is sufficient to show an upper bound
for their likelihood $$\begin{align}
    \|q_{0,\mathbf{j}} -  \mathbb{E} q_{\psi_1,\cdots,\psi_m,\mathbf{j}}\|_{\mathrm{TV}} &\leq 1- \min_{s}\frac{\mathrm{tr}(M_s \rho_{\mathbf{j}})}{\mathrm{tr}(M_s \sigma_{\mathbf{j}})} = 1 - \min_{s}\frac{\mathrm{tr}(M'_s \mathbb{E} \psi_1^{\otimes A_{1,:}} \otimes \cdots\otimes \psi_m^{\otimes A_{m,:}} )}{\mathrm{tr}(M'_s \bigotimes_{t = 1}^T \left[\mathbb{E} \psi_{1}^{\otimes A_{1,t}} \otimes \cdots \otimes \psi_{m}^{\otimes A_{m,t}} \right])}\\
    &=1 - \frac{\prod_{t = 1}^T \left[d_1^{\uparrow A_{1,t}}\cdots d_m^{\uparrow A_{m,t}}\right]}{d_1^{\uparrow A_{1,:}}\cdots d_m^{\uparrow A_{m,:}}}\max_{s}\frac{\mathrm{tr}(M'_s  S^{A_{1,:}} \otimes \cdots\otimes S^{A_{m,:}} )}{\mathrm{tr}(M'_s \bigotimes_{t = 1}^T \left[ S^{A_{1,t}} \otimes \cdots \otimes S^{A_{m,t}} \right])},\label{eq:midres_EHI}
\end{align}$$ where we use $S^{A}$ to denote the centralizer of
permutations $S_{A} = \sum_{\pi \in S_{A}} \mathbb{P}_{\pi}^{d}$ that
supports on the qudits counted by $A$. We then show the lower bound of
the LHS in Eq. [\[eq:midres_EHI\]](#eq:midres_EHI){reference-type="ref"
reference="eq:midres_EHI"} through two lemmas below.

::: {.callout-important icon="false"}
## Lemma

Given $A = \cup_{k = 1}^{m} \cup_{t = 1}^T A_{k,t}$ as a partition of
qudits set $A$. Ensure that the qudits in subset $\cup_{t} A_{k,t}$ have
the same dimension $d_k$, such that both $A_{k,t}$ and
$\cup_{t} A_{k,t}$ forms the identical qudits set. Denotes
$S^{A_{k,t}},S^{A_{k,:}}$ as the representation of permutation group
$S_{|A_{k,t}|}, S_{A_{k,:}}$ on these identical qudits sets. Then for
arbitrary operator $M$ that is the product form under the separation
$\left(\cup_{k = 1}^{m}A_{k,1}\right) \cup \cdots \cup \left(\cup_{k = 1}^{m}A_{k,T}\right)$,
we have: $$\begin{align}
    {\mathrm{tr}(M  S^{A_{1,:}} \otimes \cdots\otimes S^{A_{m,:}} )} \leq {\mathrm{tr}(M \bigotimes_{t = 1}^T \left[ S^{A_{1,t}} \otimes \cdots \otimes S^{A_{m,t}} \right])}.
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

::: {.callout-important icon="false"}
## Lemma

Given a length-T vector $(v_1,\cdots,v_T)$ with $v_i \in \mathbb{Z}_+$,
the inequality below is satisfied: $$\begin{align}
        \frac{d^{\uparrow y_1} \cdots d^{\uparrow y_T}}{ d^{\uparrow y_1 + \cdots + y_T} } \geq e^{-d^{-1} \left(\sum_{t = 1}^T y_t\right)^2}.
\end{align}$$
:::

### **RH**-ensemble test

::: problem
[]{#prob:RHtest label="prob:RHtest"} Design an algorithm using
restrained measurements to distinguish between two cases below with
success rate $1/2+\delta$.(i)the maximum mixed state $\mathbb{I}/d$ or
(ii) states set with problem ensemble $\mathcal{E}_{\varepsilon}$.
:::

### Subspace **RH**-ensemble test

::: problem
Given **RH** ensemble
$\mathcal{E}_{1 - R\delta}, \mathcal{E}_{L\delta}$, as defined in
Problem [\[prob:RHtest\]](#prob:RHtest){reference-type="ref"
reference="prob:RHtest"}, with $R = (2^{n-1} + 1)/(2^{n-1} - 1 +\delta)$
and $L = (1 - 4^{-n+1} - 2^{-n+1} \delta)^{-1}$, try to design an
algorithm that $\forall C \in \mathcal{C}$, discriminates two
subspace-**RH** ensembles below: $$\begin{align}
        &\mathcal{E}_{(1,0),C} := \left\{\sigma_{(1,0),C}:= C \left[\frac{1}{2} \ket{0}\!\bra{0} \otimes \psi + \frac{1}{2} \ket{1}\!\bra{1} \otimes (\mathbb{I}/2^{n-1}) \right] C^{\dagger}\right\}_{\psi \sim \mathrm{Haar}_{n-1}},\\
        &\mathcal{E}_{(1 - R\delta,U\delta),C} := \left\{ \sigma_{(1 - R\delta,L\delta),C} :=C \left[\frac{1}{2} \ket{0}\!\bra{0} \otimes \rho_{1 - R\delta} + \frac{1}{2} \ket{1}\!\bra{1} \otimes \rho_{L\delta} \right] C^{\dagger}\right\}_{\rho_{\varepsilon} \sim \mathcal{E}_{\varepsilon}}.
\end{align}$$
:::

This construction ensures that the average purity of
$\mathcal{E}_{(1,0)}$ and $\mathcal{E}_{(1 - R\delta,L\delta)}$ equals
each others, as manifest below: $$\begin{align}
    &\mathbb{E}_{\rho \sim \mathcal{E}_{(1,0),C}} \mathrm{tr}\left(\rho^{2}\right) = 1/4 +  (1/4) \cdot (1/2^{n-1}) =  \frac{1}{4}\left(1+\frac{1}{2^{n-1}}\right), \\
    &\mathbb{E}_{\rho \sim \mathcal{E}_{(1 - R\delta,U\delta),C}} \mathrm{tr}\left(\rho^{2}\right) = \frac{1}{4}\frac{2^{n-1}(1 - R\delta) + 1}{2^{n-1} + 1 - R\delta} + \frac{1}{4}\frac{2^{n-1} L\delta + 1}{2^{n-1} + L\delta} = \frac{1}{4}(1 - \delta) + \frac{1}{4}(\frac{1}{2^{n-1}} + \delta) = \frac{1}{4}\left(1+\frac{1}{2^{n-1}}\right).
\end{align}$$ We now build uniform distribution on all $n$-qubit
Clifford gates $\mathcal{D}$. Since Clifford gate forms a 2-design, we
can directly write the average based on the value of average purity
$$\begin{align}
    &\rho_0 := \mathbb{E}_{\rho \sim \mathcal{E}_{(1,0),C\sim \mathcal{D}}} \rho^{\otimes 2}=\mathbb{E}_{\rho \sim \mathcal{E}_{(1 - R\delta,U\delta),C\sim \mathcal{D}}} \rho^{\otimes 2} = a\cdot \mathbb{I}_{2n}/2^{2n} + b\cdot \mathrm{SWAP}^{\otimes n}/2^{n}, \\
    & a + b = 1, \quad 2^{-n} a + 2^{n} b = \text{Avg. Purity} = 4^{-1}(1 + 2^{-n+1}).
\end{align}$$ Solve the equation for $a$ and $b$, we get the result:
$$\begin{align}
    \rho_0 = (1 - \mu)  \frac{\mathbb{I}_n^{\otimes 2}}{2^{2n}} + \mu \frac{\mathbb{I}_n^{\otimes 2} + \mathrm{SWAP}^{\otimes n}}{2^n(2^{n} + 1)}, \text{~where~} \mu = 4^{-1} \frac{2^n -2}{2^n - 1}.
\end{align}$$ This prevents the
Lemma [\[lemma:hard_necess1\]](#lemma:hard_necess1){reference-type="ref"
reference="lemma:hard_necess1"} giving an efficient 2-replica strategy
that discriminates $\mathcal{E}_{(1,0),C}$ and
$\mathcal{E}_{(1 - R\delta,U\delta),C}$. However, given a fixed
$C \in \mathcal{C}$, the average of $\mathrm{tr}(P \rho^2)$ for
$P = C^\dagger Z_1 C$ has a constant gap $\delta/2$: $$\begin{align}
    &\mathbb{E}_{\rho \sim \mathcal{E}_{(1,0),C}} \mathrm{tr}\left(P\rho^{2}\right) = 1/4 -  (1/4) \cdot (1/2^{n-1}) = \frac{1}{4}\left(1- \frac{1}{2^{n-1}}\right) ,\\
    &\mathbb{E}_{\rho \sim \mathcal{E}_{(1 - R\delta,U\delta),C}} \mathrm{tr}\left(P\rho^{2}\right)  = \frac{1}{4}(1 - \delta) - \frac{1}{4}(\frac{1}{2^{n-1}} + \delta) = \frac{1}{4}\left(1- \frac{1}{2^{n-1}}\right) - \frac{\delta}{2}.
\end{align}$$ This means that if one can use strategy $\mathcal{A}$ to
estimate
$\mathrm{tr}(P \rho^2), \forall P \in \{C^\dagger Z_1 C\}_{C \in \mathcal{C}}$
within additive error $\delta/4$, he can use $\mathcal{A}$ to
discriminate $\mathcal{E}_{(1,0),C}$ and
$\mathcal{E}_{(1 - R\delta,U\delta),C}$, as rigorously proved below:

::: {.callout-important icon="false"}
## Lemma

An algorithm that estimates
$\mathrm{tr}(P \rho^2), \forall P \in \{C Z_1 C^\dagger\}_{C \in \mathcal{C}}$
can be used to distinguish $\mathcal{E}_{(1,0),C}$ from
$\mathcal{E}_{(1 - R\delta,U\delta),C}$ for arbitrary distribution on
$\mathcal{C}$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

Now we prove that two-replica strategy that discriminate
$\sigma_{(1,0),C}^{\otimes 2}$ from
$\sigma_{(1 - R\delta,L\delta),C}^{\otimes 2}$ require $\Omega(2^{n})$
rounds. Given a $T$-round $2$-replica measurement strategy
$M_s = \bigotimes_{t = 1}^{T} F_{s_t}^{u_t}$, where $\{F_{s}^{u}\}_{s}$
is a POVM on space $\mathcal{H}(d^2)$. Now the **TVD** under this
measurement takes the value: $$\begin{align}
    \delta_{\mathrm{tvd}} = \left|\mathrm{tr}\left(M_s  \mathbb{E}_{C}C^{\otimes 2T}\mathbb{E}_{\psi}\left(\sigma_{(1,0),I}^{\otimes 2T} - \sigma_{(1 - R\delta,L\delta),I}^{\otimes 2T}\right)(C^\dagger)^{\otimes 2T}\right)\right|,
\end{align}$$ where the Haar average takes the value: $$\begin{align}
    \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2T} &= \left[\frac{1}{2}\ket{0}\!\bra{0} \otimes \psi  + \frac{1}{2}\ket{1}\!\bra{1} \otimes 2^{-n+1}\mathbb{I}_{n-1}\right]^{\otimes 2T} = \sum_{\mathbf{a} \in \mathbb{F}_2^{2T}} \frac{2^{-2T}\ket{\bar{\mathbf{a}}}\!\bra{\bar{\mathbf{a}}} }{d^{\uparrow |\mathbf{a}|} d^{2T - |\mathbf{a}|}}\otimes\sum_{\pi \in S_{2T}^{\mathbf{a}}} \mathbb{P}_{\pi}^{d},\\
    \mathbb{E}_{\psi}\sigma_{(1 - R\delta,L\delta),I}^{\otimes 2T} &= \left[\frac{1}{2}\ket{0}\!\bra{0} \otimes \rho_{1 - R\delta} + \frac{1}{2}\ket{1}\!\bra{1} \otimes 2^{-n+1}\rho_{L\delta}\right]^{\otimes 2T} \\
    &= \sum_{\mathbf{a} \in \mathbb{F}_2^{2T}} {2^{-2T}\ket{\bar{\mathbf{a}}}\!\bra{\bar{\mathbf{a}}}} \otimes \frac{\sum_{\pi \in S_{2T}^{\mathbf{a}}, \sigma \in S_{2T}^{\bar{\mathbf{a}}}} \mathbb{P}_{\pi \sigma}^{d} (1 - R \delta)^{-c(\pi)} (L\delta)^{-c(\sigma)}}{[d/(1 - R\delta)]^{\uparrow |\mathbf{a}|} [d/L\delta]^{\uparrow |\bar{\mathbf{a}}|}},
\end{align}$$ where $d = 2^{n-1}$ and $S_{2T}^{\mathbf{a}}$ denoting the
permutation contained in position $\{i|a_i = 1\}$. If we defined the
operator
$\mathbb{S}^{\mathbf{a}} = \sum_{\pi \in S_{2T}^{\mathbf{a}}} \mathbb{P}_{\pi}^{d}$
and $D = 2d = 2^n$, we conclude that $$\begin{align}
    \Phi_{\mathrm{U},2T}\left[ \ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}}\otimes\mathbb{S}^{\mathbf{a}}\right] = \sum_{\rho \sigma \in S_{2T}} \mathrm{Wg}_{\rho\sigma}^{D} \mathrm{tr}\left[\ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}}\otimes\mathbb{S}^{\mathbf{a}} \cdot \mathrm{SWAP}_{\sigma} \otimes \mathbb{P}_{\sigma}^{d}\right] \mathbb{P}_{\rho}^{D}.
\end{align}$$ The trace term can be explicitly calcluated as
$$\begin{align}
    &\mathrm{tr}\left[\ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}}\otimes\mathbb{S}^{\mathbf{a}} \cdot \mathrm{SWAP}_{\sigma} \otimes \mathbb{P}_{\sigma}^{d}\right]= \delta_{\mathbf{a}, \sigma{\mathbf{a}}} \sum_{\pi \in S_{2T}^{\mathbf{a}}} \mathrm{tr}\left(\mathbb{P}_{\pi \sigma}^{d}\right) = \delta_{\sigma, \beta \gamma} \sum_{\pi \in S_{2T}^{{\mathbf{a}}}} d^{c(\pi\gamma)} = \delta_{\sigma, \beta \gamma} \frac{d^{\uparrow |\mathbf{a}|}}{d^{|{\mathbf{a}}|}}d^{c(\gamma)}.
\end{align}$$ Here in the second equality we use the fact that
$\mathbf{a} = \sigma(\mathbf{a})$ if and only if
$\sigma = \beta \cdot \gamma$ for $\beta\in S_{2T}^{\mathbf{a}}$ and
$\gamma \in S_{2T}^{\bar{\mathbf{a}}}$. In the last equality, we use the
identity $$\begin{align}
   \forall \gamma \in S_{2T}^{\bar{\mathbf{a}}}, \sum_{\pi\in S_{2T}^{\mathbf{a}}} d^{c(\pi\gamma )} =  \frac{d^{\uparrow |\mathbf{a}|}}{d^{|{\mathbf{a}}|}}d^{c(\gamma)}
\end{align}$$ Noted that the unitary average of
$\sum_{\mathbf{a}}2^{-2T}\ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}} \otimes \rho_{\mathbf{a}}$
and
$\sum_{\mathbf{a}}2^{-2T}\ket{\bar{\mathbf{a}}}\!\bra{\bar{\mathbf{a}}}\otimes \rho_{\mathbf{a}}$
are identical since $\ket{\mathbf{a}}$ can be transformed into
$\ket{\bar{\mathbf{a}}}$ through $2T$-fold unitary $X^{2T}$ and Haar
random unitary is shift invariant. Thus, the average state $\rho_0$ is
the linear combination of permutation operators: $$\begin{align}
    &\Phi_{\mathrm{U},2T}\left[ \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2T} \right] = \Phi_{\mathrm{U},2T}\left[ \mathbb{E}_{\psi}\sigma_{(0,1),I}^{\otimes 2T} \right] :=\rho_0 =  \Phi_{\mathrm{U},2T}\left[ \sum_{\mathbf{a} \in \mathbb{F}_2^{2T}}\frac{ \ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}}\otimes\mathbb{S}^{\mathbf{a}}}{2^{2T}d^{\uparrow |\mathbf{a}|} d^{2T - |\mathbf{a}|}}\right]\\
    & = \sum_{\mathbf{a} \in \mathbb{F}_2^{2T}}\sum_{\sigma,\rho \in S_{2T}}\frac{\mathrm{Wg}_{\rho \sigma}^{D}\cdot \delta_{\sigma,\beta\gamma}\frac{d^{\uparrow |\mathbf{a}|}}{d^{|{\mathbf{a}}|}}d^{c(\gamma)}}{2^{2T}d^{\uparrow |\mathbf{a}|} d^{2T - |\mathbf{a}|}} \mathbb{P}_{\rho}^{D} 
    =\sum_{\mathbf{a} \in \mathbb{F}_2^{2T}}\sum_{\rho \in S_{2T}}\sum_{\beta \in S_{2T}^{{\mathbf{a}}},\gamma\in S_{2T}^{\bar{\mathbf{a}}}}\frac{\mathrm{Wg}_{\rho(\beta\gamma)}^{D}\cdot d^{c(\gamma)}}{2^{2T} d^{2T}} \mathbb{P}_{\rho}^{D}
\end{align}$$ Similarly, we calculate $$\begin{align}
    &\mathrm{tr}\left[\left(\ket{\bar{\mathbf{a}}}\!\bra{\bar{\mathbf{a}}}\otimes \frac{\sum_{\pi \in S_{2T}^{\mathbf{a}}, \nu \in S_{2T}^{\bar{\mathbf{a}}}} \mathbb{P}_{\pi \nu}^{d} (1 - R \delta)^{-c(\pi)} (L\delta)^{-c(\nu)}}{[d/(1 - R\delta)]^{\uparrow |\mathbf{a}|} [d/L\delta]^{\uparrow |\bar{\mathbf{a}}|}}\right)\cdot \mathrm{SWAP}_{\sigma} \otimes \mathbb{P}_{\sigma}^{d}\right]\\
    &= \delta_{\sigma, \beta\gamma}\sum_{\pi \in S_{2T}^{\mathbf{a}}, \nu \in S_{2T}^{\bar{\mathbf{a}}}}\frac{ d^{c(\pi \nu)} (1 - R \delta)^{-c(\pi \beta^{-1})} (L\delta)^{-c(\nu\gamma^{-1})}}{[d/(1 - R\delta)]^{\uparrow |\mathbf{a}|} [d/L\delta]^{\uparrow |\bar{\mathbf{a}}|}}.
\end{align}$$ When $\delta = 0$, this expression reduced to
$\delta_{\sigma,\beta\gamma}d^{-2T} d^{c(\gamma)}$. We thus Taylor
expands this expression in terms of $\delta$. $$\begin{align}
    &\Phi_{\mathrm{U},2T}\left[ \mathbb{E}_{\psi}\sigma_{(1-R\delta,L\delta),I}^{\otimes 2T} \right]  = \sum_{\mathbf{a} \in \mathbb{F}_2^{2T}}\sum_{\rho \in S_{2T}}\sum_{\beta \in S_{2T}^{{\mathbf{a}}},\gamma\in S_{2T}^{\bar{\mathbf{a}}}}\mathrm{Wg}_{\rho(\beta\gamma)}^{D}\cdot \frac{ d^{c(\pi \nu)} (1 - R \delta)^{-c(\pi \beta^{-1})} (L\delta)^{-c(\nu\gamma^{-1})}}{2^{2T}[d/(1 - R\delta)]^{\uparrow |\mathbf{a}|} [d/L\delta]^{\uparrow |\bar{\mathbf{a}}|}} \mathbb{P}_{\rho}^{D}
\end{align}$$ The difference of two average can then be reform into the
discrimination between $\mathbb{I}_{n}^{\otimes 2T}/d^{2T}$ from the
mixed state $$\begin{align}
    \Phi_{\mathrm{U},2T}\left[ \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2T} \right] -\Phi_{\mathrm{U},2T}\left[ \mathbb{E}_{\psi}\sigma_{(1-R\delta,L\delta),I}^{\otimes 2T} \right] =  \mathbb{I}_{n}^{\otimes 2T}/D^{2T} + \left[\sum_{\rho \in S_{2T}} \lambda_{\rho} \mathbb{P}_{\rho}^{D} \right]
\end{align}$$ This **TVD** is bounded by the leaves likelihood for
$M_s = \otimes_{t =1}^{T} F_{s_t}^{u_t}$ as $$\begin{align}
    L(s) = \frac{D^{2T}\mathrm{tr}\left(M_s\left[\sum_{\rho \in S_{2T}} \lambda_{\rho} \mathbb{P}_{\rho}^{D} \right]\right)}{\mathrm{tr}\left(M_s\right)} 
    \geq  D^{2T} \prod_{t = 1}^{2T} \frac{\mathrm{tr}\left(F_{s_t}^{u_t}\left[\sum_{\rho \in S_{2}} \lambda'_{\rho} \mathbb{P}_{\rho}^{D} \right]\right)}{\mathrm{tr}\left(F_{s_t}^{u_t}\right)}
\end{align}$$ This further reduced the problem to the discrimination
between $\mathbb{I}(D)^{\otimes 2}/D^2$ and
$\sum_{\rho \in S_{2}} \lambda'_{\rho} \mathbb{P}_{\rho}^{D}$ Based on
Lemma [\[theo:mart_distinguish_lb\]](#theo:mart_distinguish_lb){reference-type="ref"
reference="theo:mart_distinguish_lb"}, we calculate its chi-square
divergence first: $$\begin{align}
    \delta_{\mathcal{D}} &= \max_{\{F_s\}_s \in \mathcal{M}} \sum_{s} \mathrm{tr}\left(\rho_0 F_s\right) \mathbb{E}_{\substack{C \sim \mathcal{D},\psi}} \left[\frac{\mathrm{tr}\left(\sigma_{(1,0),C}^{\otimes 2} F_s\right)}{\mathrm{tr}\left(\rho_0 F_s\right)} - 1\right]^2 = \max_{\{F_s\}_s \in \mathcal{M}} \sum_{s}  \mathbb{E}_{\substack{C \sim \mathcal{D}, \psi}}\frac{\left\{\mathrm{tr} \left[\left(\sigma_{(1,0),C}^{\otimes 2} - \rho_0\right) F_s\right]\right\}^2}{\mathrm{tr}\left(\rho_0F_s\right)} \notag \\
     &\leq (1 - \mu)^{-1}\max_{\{F_s\}_s \in \mathcal{M}}  \mathbb{E}_{\substack{C \sim \mathcal{D},\psi}}\sum_{s} \frac{2^{2n}\left\{\mathrm{tr} \left[\left(\sigma_{(1,0),C}^{\otimes 2} - \rho_0\right) F_s\right]\right\}^2}{\mathrm{tr}\left(F_s\right)}\\
     &=(1 - \mu)^{-1}\max_{\{F_s\}_s \in \mathcal{M}}  \sum_{s} \frac{2^{2n}\mathrm{tr} \left[\mathbb{E}_{\substack{C \sim \mathcal{D}}} C^{\otimes 4}\left(\mathbb{E}_{\psi}\left(\sigma_{(1,0),I}^{\otimes 2} - \rho_0\right)^{\otimes 2} \right)(C^\dagger)^{\otimes 4}F_s^{\otimes 2}\right]}{\mathrm{tr}\left(F_s\right)}\\
     &=(1 - \mu)^{-1}\max_{\ket{\psi_s}}  \sum_{s} {(2^{2n})^2 w_s\mathrm{tr} \left[\mathbb{E}_{\substack{C \sim \mathcal{D}}} C^{\otimes 4}\left(\mathbb{E}_{\psi}\left(\sigma_{(1,0),I}^{\otimes 2} - \rho_0\right)^{\otimes 2} \right)(C^\dagger)^{\otimes 4}\psi_s^{\otimes 2}\right]}.
\end{align}$$ Here in the third equality we use the fact that
$C^{\otimes 2} \rho_0 (C^{\dagger})^{\otimes 2} = \rho_0$ and
$\sigma_{(1,0),C} = C^{\otimes 2} \sigma_{(1,0),I} (C^{\dagger})^{\otimes 2}$.
In the last equality, we plug in
$F_s = 2^{2n} w_s \ket{\psi_s}\!\bra{\psi_s}$ we calculate the critical
term $$\begin{align}
    \mathbb{E}_{\psi}\left(\sigma_{(1,0),I}^{\otimes 2} - \rho_0\right)^{\otimes 2}  =  \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4} - \left(\mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2}\right) \otimes \rho_0 - \rho_0 \otimes \left(\mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2}\right) +\rho_0^{\otimes 2}.
\end{align}$$ Again use the fact that
$C^{\otimes 2} \rho_0 (C^{\dagger})^{\otimes 2} = \rho_0$, the 4-fold
Clifford average of the last three terms reduced to 2-fold Clifford and
canceled respectively. Since Clifford forms a 3-design, it can be safely
replaced by 2-fold unitary average. Since
$\mathbb{E}_{C \sim \mathcal{D}} C^{\otimes 2}\mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 2} (C^\dagger)^{\otimes 2} = \rho_0$,
we have: $$\begin{align}
    \mathbb{E}_{C \sim \mathcal{D}}C^{\otimes 4}\mathbb{E}_{\psi}&\left(\sigma_{(1,0),I}^{\otimes 2} - \rho_0\right)^{\otimes 2}(C^\dagger)^{\otimes 4}  = \mathbb{E}_{C \sim \mathcal{D}} C^{\otimes 4} \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4}(C^\dagger)^{\otimes 4}  -\rho_0^{\otimes 2}\\
    &=\Phi_{\mathrm{Cl},4}\left( \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4}\right) -\Phi_{\mathrm{U},4}\left(  \mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4}\right) +\Phi_{\mathrm{U},4}\left(\sigma_{(1,0),I}^{\otimes 4}\right) -\Phi_{\mathrm{U},2}\left(\sigma_{(1,0),I}^{\otimes 2}\right)^{\otimes 2}
\end{align}$$ where the 4-fold Clifford average of
$\mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4}$ is the only left term to
be further calculated. For the second difference, we notice that
$\Phi_{\mathrm{U},4}\left(\mathbb{E}_{\psi}\sigma_{(1,0),I}^{\otimes 4}\right) = \Phi_{\mathrm{U},4}\left(\sigma_{(1,0),I}^{\otimes 4}\right)$,
and $$\begin{align}
    &\Phi_{\mathrm{U},4}\left(\sigma_{(1,0),I}^{\otimes 4}\right) = \sum_{u,v \in S_4}\mathrm{Wg}(uv,d) \mathrm{tr}\left(\mathbb{P}_{v}^{d} \sigma_{(1,0),I}^{\otimes 4}\right) \mathbb{P}_{u}^{d}\\
    &=
\end{align}$$ Noted that the $\Phi_{\mathrm{Cl},2T}$ shall be decomposed
into commutants of $2T$-fold Clifford, which are generated by
$\Omega_4 = \sum_{P \in \mathcal{P}_{n}} P^{\otimes 4}$,
$\Omega_6 = \sum_{P \in \mathcal{P}_{n}}P^{\otimes 6}$,
$\Omega_{2T} = \sum_{P \in \mathcal{P}_{n}}P^{\otimes 2T}$ if $T \mod 2$
and all the permutations on $2T$ copies of $n$-qubit state. Notice that
$\mathrm{tr}\left[\left(\ket{{\mathbf{a}}}\!\bra{{\mathbf{a}}}  - \ket{\bar{\mathbf{a}}}\!\bra{\bar{\mathbf{a}}} \right) \Omega\cdot \mathrm{SWAP}_{\pi}\right] = 0, \forall \pi \in S_{2T}$
and $\Omega$ generated by $\{\Omega_4,\Omega_6,\Omega_{2T}\}$ that
supports on different parts of $2T$-qubits.

We the conclude the theorem below:

::: {.callout-important icon="false"}
## Lemma

Given an operator $X$ on $k$-replica
:::

also means that
$\mathbb{E}_{\rho \sim \mathcal{E}_{(1,0)}} \rho^{\otimes 2}$ To show
the hardness in the 2-replica strategy, we first check the difference of
their $2$-replica average. $$\begin{align}
    \mathbb{E}_{\rho \sim \mathcal{E}_{(2\varepsilon,0)}} \rho^{\otimes 2} &=  C^{\otimes 2} \mathbb{E}_{\rho_{2\varepsilon} \sim \mathcal{E}_{2 \varepsilon}} \left[\frac{1}{2} \ket{0}\!\bra{0} \otimes \rho_{2 \varepsilon} + \frac{1}{2}\ket{1}\!\bra{1} \otimes \mathbb{I}_{n-1}/2^{n-1}\right]^{\otimes 2}(C^\dagger)^{\otimes 2}\\
    &= \frac{1}{4}C^{\otimes 2}  \ket{00}\!\bra{00} \otimes \left[\frac{\mathbb{I}_{2n-2} + 2\varepsilon\mathrm{SWAP}^{\otimes (n-1)}}{d(d+ 2\varepsilon)} - \left(\frac{\mathbb{I}_{n-1}}{d}\right)^{\otimes 2}\right](C^\dagger)^{\otimes 2} + \left(\frac{\mathbb{I}_{n}}{2^n}\right)^{\otimes 2}\\
    &= \frac{2\varepsilon }{4} C^{\otimes 2} \ket{00}\!\bra{00} \otimes \frac{d\mathrm{SWAP}^{\otimes (n-1)} - \mathbb{I}_{2n-2}}{d^2(d+2\varepsilon)}(C^\dagger)^{\otimes 2}+ \left(\frac{\mathbb{I}_{n}}{2^n}\right)^{\otimes 2},\text{~where~} d = 2^{n-1}.\\
    \mathbb{E}_{\rho \sim \mathcal{E}_{(\varepsilon,\varepsilon)}} \rho^{\otimes 2} &= C^{\otimes 2} \left[\left(\frac{\mathbb{I}}{2}\right)^{\otimes 2} \otimes \frac{\mathbb{I}_{2n-2} + \varepsilon\mathrm{SWAP}^{\otimes (n-1)}}{d(d+ \varepsilon)}\right](C^\dagger)^{\otimes 2}\\
    &=\varepsilon C^{\otimes 2} \frac{\mathbb{I}_2 \otimes \mathrm{SWAP}^{\otimes n-1}}{4d(d+\varepsilon)}(C^\dagger)^{\otimes 2}+\frac{\mathbb{I}_{2n}}{2^n(2^n + 2\varepsilon)}.
\end{align}$$ Here we use the fact that
$\mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} \rho = \mathbb{I}_{n-1}/d$
and
$\mathbb{E}_{\rho \sim \mathcal{E}_{\varepsilon}} \rho^{\otimes 2} = \left[\mathbb{I}_{2n-2} + \varepsilon\mathrm{SWAP}^{\otimes (n-1)}\right]/[d(d+ \varepsilon)]$.
Then their difference
$\Delta_2(C) := \mathbb{E}_{\rho \sim \mathcal{E}_{(2\varepsilon,0)}} \rho^{\otimes 2} - \mathbb{E}_{\rho \sim \mathcal{E}_{(\varepsilon,\varepsilon)}} \rho^{\otimes 2}$
writes: $$\begin{align}
    \Delta_2(C) : = \frac{2 \varepsilon}{2^{2n}(2^n + 2 \varepsilon)}\mathbb{I}_{2n} + \varepsilon C^{\otimes 2} \left[\frac{\ket{00}\!\bra{00}}{2} \otimes \frac{\mathrm{SWAP}^{\otimes (n-1)} - d^{-1}\mathbb{I}_{2n-2}}{d(d+ 2\varepsilon)} - \frac{\mathbb{I}_2 \otimes \mathrm{SWAP}^{\otimes n-1}}{4d(d+\varepsilon)}\right](C^\dagger)^{\otimes 2}.
\end{align}$$ This operator has constant 1-norm, thus implies a
2-replica discrimination strategy below:

::: {.callout-important icon="false"}
## Lemma

An algorithm that estimates
$\mathrm{tr}(P \rho^2), \forall P \in \{C Z_1 C^\dagger\}_{C \in \mathcal{C}}$
can be used to distinguish $\mathcal{E}_{(2\varepsilon, 0)}$ from
$\mathcal{E}_{(\varepsilon, \varepsilon)}$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* As shown by
Lemma [\[lemma:purity_of_RH\]](#lemma:purity_of_RH){reference-type="ref"
reference="lemma:purity_of_RH"}, the value of
$\mathrm{tr}(P \rho^2) = \mathrm{tr}\left((P\otimes \mathbb{I}) \cdot  \mathrm{SWAP}^{\otimes n} \cdot \rho^{\otimes 2}\right)$
can be calculated as
$\mathbb{E}_{\rho \in \mathcal{E}_{(\varepsilon, \varepsilon)}}\mathrm{tr}(P \rho^2) = 0$
and $$\begin{align}
        &\mathbb{E}_{\rho \in \mathcal{E}_{(2\varepsilon, 0)}}\mathrm{tr}(P \rho^2) = \frac{\mathbb{E}_{\rho \in \mathcal{E}_{2\varepsilon}}\mathrm{tr}(P \rho^2) - \mathbb{E}_{\rho \in \mathcal{E}_{0}}\mathrm{tr}(P \rho^2)}{4} = \frac{1}{4}\left[\frac{2^{n} \varepsilon + 1}{2^{n-1} + 2 \varepsilon} - \frac{1}{2^{n-1}}\right] = \frac{2^{2n} - 4}{2^{n+1}(2^n + 4\varepsilon)} \varepsilon.
\end{align}$$ ◻
:::

However, if we build uniform distribution on all possible Pauli
operators, which in turn induces uniform distribution on all $n$-qubit
Clifford gates $\mathcal{D}$, the operator
$\mathbb{E}_{C \sim \mathcal{D}} \Delta_2$ has exponentially small
one-norm, as calculated below: $$\begin{align}
    &\mathbb{E}_{C \sim \mathcal{D}} \Delta_2(C) = a \mathrm{SWAP}^{\otimes n} + b \mathbb{I}_{2n}, \text{~with~}\begin{cases}
        2^n a + 2^{2n}b = 0.\\
        2^{2n} a + 2^{n}b = \frac{\varepsilon}{2} \cdot \frac{d + 3\varepsilon - \varepsilon d^2}{d(d+\varepsilon)(d + 2 \varepsilon)} .
    \end{cases}
\end{align}$$ Thus, we have $a+b,|a-b| \sim \mathcal{O}(2^{-3n})$, and
$\|\mathbb{E}_{C \sim \mathcal{D}} \Delta_2(C)\|_{1} = \mathcal{O}(2^{-n})$.

$$\begin{align}
    \delta_{\mathcal{D}} = \max_{\{F_s\}_s \in \mathcal{M}} \sum_{s} \mathrm{tr}\left(\sigma_{(\varepsilon,\varepsilon),C}^{\otimes 2} F_s\right) \mathbb{E}_{C \sim \mathcal{D}} \left[\frac{\mathrm{tr}\left(\sigma_{(2\varepsilon,0),C}^{\otimes 2} F_s\right)}{\mathrm{tr}\left(\sigma_{(\varepsilon,\varepsilon),C}^{\otimes 2} F_s\right)} - 1\right]^2
\end{align}$$

## Symmetric strategies {#subsec:sym_strate}

If there is no restriction on the memory-number and the replica number,
we can lower-bound the strategy through the symmetric of the property.
We first define general testing strategy rigorously.

::: {.callout-note icon="false"}
## Definition

A property $\mathcal{P} \subset \mathcal{S}(\mathcal{H})$ is a set of
quantum states. A two-outcome POVM $\{E,\mathbb{I} - E\}$ on k-copies of
n-qubit states tests the property $\mathcal{P}$ iff for certain
$1>\varepsilon_B \geq \varepsilon_A >0$ and $\delta = \Theta(1)$,
$$\begin{align}
         d_{\text{tr}}(\rho, \mathcal{P})  \leq \varepsilon_A \Rightarrow \text{tr}(E \rho^{\otimes k}) \geq 1/2 +\delta,\\
       d_{\text{tr}}(\rho, \mathcal{P})  \geq \varepsilon_B \Rightarrow \text{tr}(E \rho^{\otimes k}) \leq 1/2 - \delta.
\end{align}$$
:::

Now suppose the testing property $\mathcal{P}$, which is a set of state
within $n$-qubit space, is invariant under unitary operation $U(G)$ ,
which is a subgroup of $U(2)^{\otimes n}$. Namely, $$\begin{align}
    \forall \sigma \in \mathcal{P},\forall V \in U(G), V\sigma V^\dagger \in \mathcal{P}.
\end{align}$$ Then we are prepared to show that it is enough to consider
the symmetric version of the strategy rather than an arbitrary POVM
within $n$-qubit space, as stated by
Lemma [\[lemma:symmtric_M\]](#lemma:symmtric_M){reference-type="ref"
reference="lemma:symmtric_M"} below

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:symmtric_M label="lemma:symmtric_M"} Given a $k$-replica
strategy $\{E, \mathbb{I } - E\}$ for the $U(G)$-symmetric property
$\mathcal{P}$ on $n$-qubits, the symmetric strategy
$\{\Phi(E), \mathbb{I } - \Phi(E)\}$ with
$\Phi(E) := |U(G)|^{-1}\sum_{V \in U(G)} V^{\dagger,\otimes k}EV^{\otimes k}$
and
$\Phi_k(E) := |S_k|^{-1}\sum_{\pi\in S_k} \text{SWAP}_\pi E\cdot\text{SWAP}_\pi$
has non-decreasing efficiency.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* Because the unitary invariant property of $\mathcal{P}$ and the
non-decreasing property of trace distance under unitary transformation
$d_{\text{tr}}(\cdot,\cdot) = d_{\text{tr}}(U\cdot U^\dagger,U\cdot U^\dagger)$,
we conclude that $$\begin{align}
       d_{\text{tr}}(\rho, \mathcal{P})  \leq  \varepsilon_A &\Rightarrow \forall U \in U(G),  d_{\text{tr}}(U\rho U^\dagger, \mathcal{P}) \leq  \varepsilon_A \\
       &\Rightarrow  \forall U \in U(G),\text{tr}( EU^{\otimes k}\rho^{\otimes k} U^{\dagger,\otimes k}) \geq 1/2 + \Theta(1),\\
       &\Leftrightarrow  \forall U \in U(G),|U(G)|^{-1}\sum_{V \in U(G)}\text{tr}(U^{\dagger,\otimes k} EU^{\otimes k}\rho^{\otimes k} ) \geq 1/2 + \Theta(1),\\
       &\Leftrightarrow  \forall U \in U(G),\text{tr}(\bar E\rho^{\otimes k} ) \geq 1/2 + \Theta(1)
\end{align}$$ Similarly, we can prove that
$d_{\text{tr}}(\rho, \mathcal{P})  \geq \varepsilon_B \Rightarrow \text{tr}(\bar E \rho^{\otimes k}) \leq 1/2 - \Theta(1).$
The same procedure is applied for
$\bar{E} := |S_k|^{-1}\sum_{\pi\in S_k} \text{SWAP}_\pi E\cdot\text{SWAP}_\pi$.
Thus, we prove that the symmetric strategy
$\{\bar{E}, \mathbb{I } - \bar{E}\}$ will have at least the same testing
efficiency. ◻
:::

Then we discuss the symmetry for the estimation problem.

::: {.callout-note icon="false"}
## Definition

A quantitative property of states is a map $f: \rho \to \mathbb{R}$ with
$\rho \in \mathcal{S}(\mathcal{H})$ . Given a POVM $\{M_m\}_{m \in R}$
on $k$-replica space, an $k$-replica estimator of $f$ is an observable
$O \in \text{End}(\mathcal{H}^{\otimes k})$ such that
$\text{tr}(O \rho^{\otimes k}) = f(\rho)$. An estimator $O$ is efficient
$k$-replica strategy iff
$\text{Var}_{\rho^{\otimes k}}(O)\leq \text{Var}_{\rho^{\otimes k}}(O')$
for all $O \in \text{End}(\mathcal{H}^{\otimes k})$.
:::

We say a quantitative property $f$ is invariant under unitary operation
$U(G)$ iff $f(U\cdot U^\dagger) = f(\cdot), \forall U \in U(G)$. The we
gives the symmetric strategy for estimate problem.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:symmetric_O label="lemma:symmetric_O"} If $O$ is a $k$-replica
estimator for property $f$. Then the symmetrized estimators
$$\begin{align}
        \Phi(O):=  |U(G)|^{-1}\sum_{V \in U(G)} V^{\dagger,\otimes k}OV^{\otimes k},\Phi_{k}(O):= |S_k|^{-1}\sum_{\pi\in S_k} \mathbb{P}_\pi^{d,\dagger} \cdot O\cdot \mathbb{P}_\pi^{d},
\end{align}$$ always satisfied
$\text{Var}_{\rho^{\otimes k}}(\Phi(O))\leq \text{Var}_{\rho^{\otimes k}}(O),\text{Var}_{\rho^{\otimes k}}(\Phi_k(O))\leq \text{Var}_{\rho^{\otimes k}}(O)$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* We will show a more general statement for arbitrary channel
that is unital ($\Phi(\mathbb{I}) = \mathbb{I}$), positive
($\forall \rho \succeq 0, \Phi(\rho) \succeq 0$), and satisfied
$\forall O \in \text{Herm}(\mathcal{H}), \text{tr}(\rho \Phi(O)) = \text{tr}(\rho O)$.
By definition,
$\text{Var}_{\rho}(\Phi(O)) = \text{tr}(\rho \Phi(O)^2) - \text{tr}^2(\rho \Phi(O))  = [\text{tr}(\rho \Phi(O)^2) - \text{tr}(\rho O^2)]+ \text{Var}_{\rho}(O)$.
According to
Theorem [\[theo:KS_ineq\]](#theo:KS_ineq){reference-type="ref"
reference="theo:KS_ineq"}, $\Phi(O^2)-\Phi(O)^2\succeq 0$, which shows
that
$\text{tr}(\rho \Phi(O)^2)<\text{tr}(\rho \Phi(O^2)) = \text{tr}(\rho O^2)$.
This directly gives the result
$\text{Var}_{\rho}(\Phi(O)) \leq \text{Var}_{\rho}(O)$. ◻
:::

Thanks to the
Lemma [\[lemma:symmtric_M\]](#lemma:symmtric_M){reference-type="ref"
reference="lemma:symmtric_M"} and
Lemma [\[lemma:symmetric_O\]](#lemma:symmetric_O){reference-type="ref"
reference="lemma:symmetric_O"} , if we find the lower bound of the
sample complexity of all the symmetric POVM and operators, any
strategy's sample complexity is lower bounded by this value.

### The unitary case $U(G) = U(2^n)$

The simplest case are properties that is invariant under a unitary
transformation. The
lemma [\[lemma:symmtric_M\]](#lemma:symmtric_M){reference-type="ref"
reference="lemma:symmtric_M"} is useful because any spectrum testing
strategy $\{M,\mathbb{I} - M\}$ now can be restated as weak Schur
sampling followed by classical post-processing [@montanaro2013survey],
as stated by the theorem below.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:symmtric_M_unitary label="lemma:symmtric_M_unitary"} Given a
testing strategy $\{M, \mathbb{I } - M\}$ for unitary invariant property
$\mathcal{P}$ such that: $$\begin{align}
        \tr(M \rho^{\otimes k}) &\geq 1 - \delta,\forall \rho \in \mathcal{P};\\
         \tr(M \rho^{\otimes k}) &\leq 1 - f(\varepsilon),\forall \rho ~\varepsilon \text{-far from~} \mathcal{P}.
\end{align}$$ Another strategy $\bar{M}$ such that
$[\bar M,U^{\otimes k}] =0$ and $[\bar M,\text{SWAP}_\pi]=0$ can be
constructed with non-decreasing efficiency.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.*
$M_s =|S_k|^{-1} \sum_{\pi \in S^k}\mathbb{P}_{\pi}^{2^n}\cdot  M \cdot\mathbb{P}_{\pi}^{2^n}$
have unchanged efficiency because
$\mathbb{P}_{\pi}^{2^n}\cdot  \rho^{\otimes k} \cdot\mathbb{P}_{\pi}^{2^n} = \rho^{\otimes k}$.
Combined with
lemma [\[lemma:symmtric_M\]](#lemma:symmtric_M){reference-type="ref"
reference="lemma:symmtric_M"} proves the result. ◻
:::

This construction simplified the analysis because we can reduce
arbitrary strategy to a canonical one-*weak Shur sampling*. To see this,
we first cite the lemma in [@childs2007weak], according to the famous
Schur-Weyl duality.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:SW_dual label="lemma:SW_dual"} Given the symmetry group $S_k$
, use $\kappa \vdash k$ labels the conjugate classes $K(\kappa)$ and
$\lambda \vdash k$ label the irreducible representation with the
character function $\chi_{\lambda}(\cdot)$ and dimension
$\text{dim}~\lambda$. Define the projective measurements $P_\lambda$ and
the conjugate-class observables $O_{\kappa}$ as $$\begin{align}
         P_{\lambda} := (\text{dim}\lambda)({k!})^{-1} \sum_{\pi \in S_k} \chi_{\lambda}(\pi) \mathbb{P}_\pi^d,\quad O_{\kappa} := |K(\kappa)|^{-1} \sum_{\pi \in K(\kappa)}  \mathbb{P}_\pi^d.
\end{align}$$ If $\forall U \in \mathbb{C}^{k}$ and
$\forall \pi \in S_k$, the operator $M$ on the space
$(\mathbb{C}^d)^{\otimes k}$ satisfies $[M,U^{\otimes k}] =0$ and
$[M,\mathbb{P}_\pi^d]=0$, then $M$ can be decomposed as $$\begin{align}
         M &= \sum_{\lambda \vdash k} \alpha_{\lambda} P_\lambda,\quad M = \sum_{\kappa \vdash k} \beta_{\kappa} O_\kappa, \label{eq:M_decomp} \\
&\text{where~}O_{\kappa} = \sum_{\lambda}{(\text{dim}\lambda)^{-1}}\chi_{\lambda}(\kappa) P_{\lambda}. \label{eq:relation_PM}
\end{align}$$
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* The proof of this theorem is separated into three steps. First,
by Schur-Weyl duality, we know that $[M,U^{\otimes k}]=0$ iff $M$ is a
linear superposition of SWAP gates: $$\begin{align}
\label{eq:M_decomp_mid}
        M &= \sum_{g \in S_k} f(g) \cdot \text{SWAP}_g.
\end{align}$$

Then we show that linear combination of SWAP gates commute with all the
SWAP gates iff the superposition coefficient is a class function.
According to
Eq. [\[eq:M_decomp_mid\]](#eq:M_decomp_mid){reference-type="eqref"
reference="eq:M_decomp_mid"}, $M$ is the image of group algebra
$m = \sum_{g \in S_k} f(g) g$ under representation
$\rho(g) = \text{SWAP}_g$. Then $m$ must commute with arbitray element
in $S_k$. $\forall~ h \in S_k$, notice that: $$\begin{align}
        hmh^{-1} &= \sum_{g \in S_k} f(g) \cdot{hgh^{-1}} =\sum_{t \in S_k} f(h^{-1} t h) \cdot{t} =\sum_{g \in S_k} f(g) \cdot g = m
\end{align}$$ This then imply $f(g) = f(h^{-1} t h)$ for all $h \in S_k$
and $f$ is a class function. Last, given that character functions forms
a orthonormal basis for class function, we obtain
$f(g) = \sum_{\lambda}c_{\lambda} \chi_{\lambda}(g)$. Plug into
Eq. [\[eq:M_decomp_mid\]](#eq:M_decomp_mid){reference-type="eqref"
reference="eq:M_decomp_mid"} gives: $$\begin{align}
             M &=  \sum_{\lambda}c_{\lambda}  \sum_{g \in S_k}\chi_{\lambda}(g)\cdot \text{SWAP}_g =\sum_{\lambda} \alpha_{\lambda} \frac{\text{dim}(V_\lambda)}{k!} \sum_{\pi \in S_k} \chi_{\lambda}(\pi) \text{SWAP}_\pi = \sum_{\lambda} \alpha_{\lambda} P_\lambda
\end{align}$$ This is indeed a projector based on
Lemma [\[lemma:projector_in_lambda\]](#lemma:projector_in_lambda){reference-type="ref"
reference="lemma:projector_in_lambda"} proved before. To prove the
conclusion (ii), we first noted that $$\begin{align}
     \sum_{\lambda}\frac{1}{\text{dim~}\lambda}\chi_{\lambda}(\kappa) P_{\lambda} &=  \sum_{\pi \in S_k} ({k!})^{-1}\sum_{\lambda}\chi_{\lambda}(\kappa)  \chi_{\lambda}(\pi) \mathbb{P}^d_\pi\\
     &=|K(\kappa)|^{-1}\sum_{\pi \in K(\kappa)}  \mathbb{P}^d_\pi = O_{\kappa}
\end{align}$$ Here in the second line we use the second orthogonal
identity
$|G|^{-1}\sum_{p}\chi_{p}(\kappa_j)\chi_{p}(\kappa_k) = |K(\kappa_k)|^{-1}\delta_{jk}$.
Then plug in Eq. [\[eq:M_decomp\]](#eq:M_decomp){reference-type="eqref"
reference="eq:M_decomp"} we get $$\begin{align}
    \sum_{\kappa \vdash k} \beta_{\kappa} O_\kappa =\sum_{\lambda\vdash k}\frac{1}{\text{dim}~\lambda}\left[ \sum_{\kappa \vdash k} \beta_{\kappa} \chi_{\lambda}(\kappa)\right] P_{\lambda}= \sum_{\lambda \vdash k} \alpha_{\lambda} P_\lambda.
\end{align}$$ This implys the transformation
$(\text{dim}\lambda)\cdot \alpha_{\lambda} =  \sum_{\kappa \vdash k} \beta_{\kappa} \chi_{\lambda}(\kappa)$. ◻
:::

### Examples.

When $k = 2$, the group $S_2$ only has two conjugate class $(2,0)$ and
$(1,1)$. The corresponding projectors are
$P_{(2,0)} = 2^{-1}{(\mathbb{I} + \text{SWAP}_{(1,2)})},P_{(1,1)} = 2^{-1}{(\mathbb{I} - \text{SWAP}_{(1,2)})}$.
This is just the SWAP test of two identical states, which is widely used
for purity test. For larger $t$, the computation of those exact
projector is proved to be #P-hard [@hepler1996complexity]. Fortunately,
the realization of projective measurement $\{P_\lambda\}$ can be
implemented in time $\text{Poly}(k,\ln d)$ with generalized phase
estimation circuit [@bacon2006efficient], which is efficient for
$n$-qubits property testing with $d = 2^n$. This is called the *weak
Schur sampling* (**WSS**). Now we characterize the result of **WSS** by
polynomials of density matrix's spectrum.

::: {.callout-note icon="false"}
## Definition

[]{#def:poly label="def:poly"} Let $\mu,\lambda\vdash k$ be a partition
of the replica number $k$. Let $\mathcal{T}$ be the set of all
semi-standard Young tableaus with shape $\lambda$ and alphabet
$\{1,\cdots,d\}$. Let $\#(T,i)$ be the number of times that the
character $i$ occurs in the semi-standard Young tableau $T$. Two
rank-$k$ symmetric polynomials of $d$ variables
$\mathbf{x}=(x_1,\cdots,x_d)$ can be defined below.

- *Schur polynomial* (**SP**) is a rank-$k$ symmetric polynomial that
  $s_{\lambda}(\mathbf x):= \sum_{T}\prod_{i=1}^d x_i^{\#(T,i)}$

- *Power sum polynomial* (**PSP**) is a rank-$k$ symmetric polynomial
  that
  $M_{\mu}(\mathbf{x}):=\prod_{i=1}^{l(\mu)} \sum_{j=1}^d x_j^{\mu_i}$
:::

### Examples.

If we take $\lambda = (k,0,\cdots)$, we get the $\sum_{j = 1}^d x_j^k$.
**SP** and **PSP** can decompose each other, as shown in
Lemma [\[lemma:sym_poly_decomp\]](#lemma:sym_poly_decomp){reference-type="ref"
reference="lemma:sym_poly_decomp"} below.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:sym_poly_decomp label="lemma:sym_poly_decomp"} Any rank-$k$
power sum polynomial can be decomposed with the rank-$k$ symmetric Schur
polynomial through
$M_{\mu}(\mathbf{x}) = \sum_{\lambda \vdash k}\chi_{\lambda}(\mu)s_{\lambda}(\mathbf{x})$.
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* ◻
:::

Refer to [@o2015quantum], the distribution of
$\text{tr}(P_{\lambda} \rho^{\otimes k})$ only relates to the spectrum
$\eta$ of $\rho$, as proved in
Lemma [\[lemma:WSS_res\]](#lemma:WSS_res){reference-type="ref"
reference="lemma:WSS_res"} below. Thus, we use
$\text{SW}_{\rho}^k(\lambda)$ to denote the weak Schur sampling
probability $\text{tr}(P_\lambda \rho^{\otimes k})$ where $\lambda$ is
the eigenvalue of the density matrix $\rho$.

::: {.callout-important icon="false"}
## Lemma

[]{#lemma:WSS_res label="lemma:WSS_res"} Defined $\text{dim}(\lambda)$
as the number of standard Young tableaus of shape $\lambda \vdash k$ and
alphabet $[k]$. Then
$\text{SW}_{\rho}^k(\lambda)= \text{dim}(\lambda) \cdot s_\lambda (\eta_1,\cdots,\eta_d)$
with $\eta$ the spectrum of $\rho$. Specifically, we have
$\text{SW}_{d^{-1}\mathbb{I}}^k(\lambda) = {(\text{dim} (\lambda))^2}{(k!)^{-1}} {d^{\uparrow \lambda}}({d^k})^{-1}$,
where denots
$d^{\uparrow \lambda}: = \prod_{(i,j) \in [\lambda]} (d + j - i)$ with
$i,j$ labeling the position of all the lattices in Young tableaus of
shape $\lambda \vdash n$,
:::

::: {.callout-note collapse="true"}
## Proof (Click to expand)

*Proof.* $$\begin{align}
\label{eq:Schur_prob}
        \text{tr}(P_\lambda \rho^{\otimes k}) = (\text{dim}\lambda)({k!})^{-1}\sum_{\pi \in S_k} \chi_{\lambda}(\pi) \text{tr}( \text{SWAP}_\pi \rho^{\otimes k}).
\end{align}$$ If $\pi$ has $l$ cycles with cycle length
$\kappa_1\cdots\kappa_l$ and $\rho$ has eigenvalues
$\eta_1,\cdots,\eta_{d}$, we noted that $$\begin{align}
        \text{tr}( \text{SWAP}_\pi \rho^{\otimes k}) = \text{tr}(\rho^{\kappa_1})\times \cdots\times\text{tr}(\rho^{\kappa_l}) = M_{\kappa}(\eta).
\end{align}$$ Plug into
Eq. [\[eq:Schur_prob\]](#eq:Schur_prob){reference-type="eqref"
reference="eq:Schur_prob"} gives $$\begin{align}
        \text{tr}(P_\lambda \rho^{\otimes k}) &= (\text{dim}\lambda)({k!})^{-1}\sum_{\pi \in S_k} \chi_{\lambda}(\pi) M_{\kappa}(\eta)\\
        &=(\text{dim}\lambda)({k!})^{-1}\sum_{\pi \in S_k} \chi_{\lambda}(\pi) \sum_{\omega \vdash k}\chi_{\omega}(\pi)s_{\omega}(\eta)\\
        &=(\text{dim}\lambda) \cdot s_{\lambda}(\eta).
\end{align}$$ Here in the second equality, we use
Lemma [\[lemma:sym_poly_decomp\]](#lemma:sym_poly_decomp){reference-type="ref"
reference="lemma:sym_poly_decomp"}. In the third equality, we use the
orthorgonal equation of group characters
$|G|^{-1} \sum_{g \in G} \chi_{p}^*(g)\chi_{q}(g) = \delta_{pq}$. ◻
:::

### The Clifford case $U(G) = \text{Clifford}(n)$
