export type QmdEditableBlockKind =
  | "heading"
  | "paragraph"
  | "list-item"
  | "blockquote"
  | "inline-math"
  | "display-math"
  | "theorem-block"
  | "rich-block";

/**
 * One plain-text region that can be mapped losslessly between QMD and HTML.
 *
 * `source`, `start`, and `end` remain in privileged plugin code so a Draft can
 * never choose the filesystem range that Visual Edit overwrites.
 */
export interface QmdEditableBlock {
  id: string;
  kind: QmdEditableBlockKind;
  text: string;
  source: string;
  start: number;
  end: number;
  /** HTML id generated by Quarto for a thm/lem/def fenced div. */
  domId?: string;
  /** Rendered HTML block kind and source-order index for complex Markdown. */
  domKind?: "heading" | "paragraph" | "list-item" | "blockquote";
  ordinal?: number;
}

export type QmdVisualBlockKind =
  | "frontmatter"
  | "heading"
  | "paragraph"
  | "list"
  | "blockquote"
  | "display-math"
  | "code"
  | "theorem"
  | "callout"
  | "raw";

/** A non-overlapping, source-authoritative region used by Visual Edit. */
export interface QmdVisualBlock {
  id: string;
  kind: QmdVisualBlockKind;
  source: string;
  start: number;
  end: number;
  level?: number;
  semantic?: string;
  title?: string;
}

export interface QmdMathSpan {
  source: string;
  latex: string;
  start: number;
  end: number;
  display: boolean;
  opening: "$" | "$$" | "\\(" | "\\[";
}

interface SourceLine {
  text: string;
  start: number;
  end: number;
}

const PROTECTED_INLINE = new Set(["\\", "`", "*", "_", "{", "}", "[", "]", "<", ">", "|", "^", "~", "@", "$", "#"]);

function sourceLines(source: string): SourceLine[] {
  const lines: SourceLine[] = [];
  let start = 0;
  while (start < source.length) {
    const newline = source.indexOf("\n", start);
    const end = newline < 0 ? source.length : newline;
    lines.push({
      text: source.slice(start, end).replace(/\r$/, ""),
      start,
      end,
    });
    if (newline < 0) break;
    start = newline + 1;
  }
  return lines;
}

function normalizedText(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

/** Plain Markdown plus explicit escapes, or null when rendering changes it. */
function renderedPlainText(source: string): string | null {
  let result = "";
  for (let index = 0; index < source.length; index += 1) {
    const character = source[index]!;
    if (character === "\\") {
      const next = source[index + 1];
      if (!next || !PROTECTED_INLINE.has(next)) return null;
      result += next;
      index += 1;
      continue;
    }
    if (PROTECTED_INLINE.has(character)) return null;
    result += character;
  }
  const normalized = normalizedText(result);
  return normalized || null;
}

function blockId(kind: QmdEditableBlockKind, source: string): string {
  let hash = 0x811c9dc5;
  for (const character of `${kind}\u0000${source}`) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return `${kind}-${hash.toString(16).padStart(8, "0")}`;
}

function block(
  kind: QmdEditableBlockKind,
  source: string,
  start: number,
  end: number,
): QmdEditableBlock | null {
  const text = renderedPlainText(source);
  if (!text) return null;
  return { id: blockId(kind, source), kind, text, source, start, end };
}

function richBlock(
  domKind: "heading" | "paragraph" | "list-item" | "blockquote",
  source: string,
  start: number,
  end: number,
  ordinal: number,
): QmdEditableBlock | null {
  if (!source.trim()) return null;
  return {
    id: blockId("rich-block", `${domKind}\u0000${source}`),
    kind: "rich-block",
    text: source,
    source,
    start,
    end,
    domKind,
    ordinal,
  };
}

function formulaBlock(
  kind: "inline-math" | "display-math",
  source: string,
  start: number,
  end: number,
): QmdEditableBlock | null {
  const text = source.trim();
  if (!text) return null;
  return { id: blockId(kind, source), kind, text, source, start, end };
}

function escapedAt(value: string, index: number): boolean {
  let slashes = 0;
  for (let cursor = index - 1; cursor >= 0 && value[cursor] === "\\"; cursor -= 1) slashes += 1;
  return slashes % 2 === 1;
}

function formulaBlocks(source: string, lines: SourceLine[], frontmatterEnd: number): QmdEditableBlock[] {
  const formulas: QmdEditableBlock[] = [];
  let fenced = "";
  let displayStart = -1;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
    const line = lines[lineIndex]!;
    if (lineIndex <= frontmatterEnd) continue;
    const trimmed = line.text.trim();
    const fence = /^(?<fence>`{3,}|~{3,})/.exec(trimmed)?.groups?.fence ?? "";
    if (fence) {
      if (!fenced) fenced = fence[0]!;
      else if (fence[0] === fenced) fenced = "";
      continue;
    }
    if (fenced) continue;

    let cursor = 0;
    while (cursor < line.text.length) {
      const dollar = line.text.indexOf("$", cursor);
      if (dollar < 0) break;
      if (escapedAt(line.text, dollar)) {
        cursor = dollar + 1;
        continue;
      }
      const absolute = line.start + dollar;
      if (line.text[dollar + 1] === "$") {
        if (displayStart < 0) {
          displayStart = absolute + 2;
        }
        else {
          const candidate = formulaBlock(
            "display-math",
            source.slice(displayStart, absolute),
            displayStart,
            absolute,
          );
          if (candidate) formulas.push(candidate);
          displayStart = -1;
        }
        cursor = dollar + 2;
        continue;
      }
      if (displayStart >= 0) {
        cursor = dollar + 1;
        continue;
      }
      let close = dollar + 1;
      while (close < line.text.length) {
        close = line.text.indexOf("$", close);
        if (close < 0 || !escapedAt(line.text, close)) break;
        close += 1;
      }
      if (close < 0) break;
      const start = absolute + 1;
      const candidate = formulaBlock(
        "inline-math",
        source.slice(start, line.start + close),
        start,
        line.start + close,
      );
      if (candidate) formulas.push(candidate);
      cursor = close + 1;
    }
  }
  return formulas;
}

function theoremBlocks(source: string, lines: SourceLine[], frontmatterEnd: number): QmdEditableBlock[] {
  const blocks: QmdEditableBlock[] = [];
  for (let index = frontmatterEnd + 1; index < lines.length; index += 1) {
    const opening = /^\s*:{3,}\s*\{(?<attributes>[^}]*)\}\s*$/.exec(lines[index]!.text);
    const domId = /(?:^|\s)#(?<id>(?:thm|lem|def)[-_][A-Za-z0-9_.:-]+)/i
      .exec(opening?.groups?.attributes ?? "")?.groups?.id;
    if (!opening || !domId) continue;
    let depth = 1;
    let closing = index + 1;
    for (; closing < lines.length; closing += 1) {
      const trimmed = lines[closing]!.text.trim();
      if (/^:{3,}\s*\{[^}]*\}\s*$/.test(trimmed)) depth += 1;
      else if (/^:{3,}\s*$/.test(trimmed)) depth -= 1;
      if (depth === 0) break;
    }
    if (depth !== 0 || closing >= lines.length) continue;
    const start = lines[index]!.start;
    const end = lines[closing]!.end;
    const raw = source.slice(start, end);
    blocks.push({
      id: blockId("theorem-block", raw),
      kind: "theorem-block",
      text: raw,
      source: raw,
      start,
      end,
      domId,
    });
    index = closing;
  }
  return blocks;
}

function structuralLine(value: string): boolean {
  const trimmed = value.trim();
  return !trimmed
    || /^(?:```|~~~|:::+|\$\$|\\\[|\\\]|[-*_]{3,})/.test(trimmed)
    || /^#{1,6}\s+/.test(trimmed)
    || /^(?:[-+*]|\d+[.)])\s+/.test(trimmed)
    || /^>\s?/.test(trimmed)
    || /^\{[^}]*\}$/.test(trimmed)
    || /^: \S/.test(trimmed);
}

/**
 * Finds blocks that can be mapped back to one rendered DOM region. Plain text
 * edits directly; rich Markdown temporarily exposes the source for that one
 * block. Duplicate visible text is excluded because the HTML side could not
 * identify it without guessing.
 */
export function editableQmdBlocks(source: string): QmdEditableBlock[] {
  const lines = sourceLines(source);
  const found: QmdEditableBlock[] = [];
  let frontmatterEnd = -1;
  if (lines[0]?.text.trim() === "---") {
    for (let index = 1; index < lines.length; index += 1) {
      if (/^(?:---|\.\.\.)\s*$/.test(lines[index]!.text)) {
        frontmatterEnd = index;
        break;
      }
    }
  }

  const theorem = theoremBlocks(source, lines, frontmatterEnd);
  const insideTheorem = (offset: number) => theorem.some((candidate) =>
    offset >= candidate.start && offset < candidate.end);
  const ordinals = new Map<QmdEditableBlock["domKind"], number>();
  const nextOrdinal = (kind: NonNullable<QmdEditableBlock["domKind"]>): number => {
    const ordinal = ordinals.get(kind) ?? 0;
    ordinals.set(kind, ordinal + 1);
    return ordinal;
  };
  let fenced = "";
  let displayMath = false;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]!;
    if (index <= frontmatterEnd) continue;
    if (insideTheorem(line.start)) continue;
    const trimmed = line.text.trim();
    const fence = /^(?<fence>`{3,}|~{3,})/.exec(trimmed)?.groups?.fence ?? "";
    if (fence) {
      if (!fenced) fenced = fence[0]!;
      else if (fence[0] === fenced) fenced = "";
      continue;
    }
    if (fenced) continue;
    if (trimmed === "$$" || trimmed === "\\[" || trimmed === "\\]") {
      displayMath = !displayMath;
      continue;
    }
    if (displayMath || !trimmed || /^:::+/.test(trimmed) || /^\{[^}]*\}$/.test(trimmed)) continue;
    if (/^ {4}|^\t/.test(line.text)) continue;

    const heading = /^(\s*#{1,6}\s+)(.*?)(\s+\{[^}]*\})?\s*$/.exec(line.text);
    if (heading) {
      const content = heading[2]!;
      const start = line.start + heading[1]!.length;
      const ordinal = nextOrdinal("heading");
      const candidate = block("heading", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("heading", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    const listItem = /^(\s*(?:[-+*]|\d+[.)])\s+)(.+?)\s*$/.exec(line.text);
    if (listItem) {
      const content = listItem[2]!;
      const start = line.start + listItem[1]!.length;
      const ordinal = nextOrdinal("list-item");
      const candidate = block("list-item", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("list-item", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    const quote = /^(\s*>\s?)(.+?)\s*$/.exec(line.text);
    if (quote) {
      const content = quote[2]!;
      const start = line.start + quote[1]!.length;
      const ordinal = nextOrdinal("blockquote");
      const candidate = block("blockquote", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("blockquote", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    if (structuralLine(line.text)) continue;
    const paragraphStart = index;
    let paragraphEnd = index;
    while (paragraphEnd + 1 < lines.length && !structuralLine(lines[paragraphEnd + 1]!.text)) {
      const next = lines[paragraphEnd + 1]!;
      if (/^ {4}|^\t/.test(next.text)) break;
      paragraphEnd += 1;
    }
    const start = lines[paragraphStart]!.start;
    const end = lines[paragraphEnd]!.end;
    const sourceBlock = source.slice(start, end);
    const ordinal = nextOrdinal("paragraph");
    const candidate = block("paragraph", sourceBlock, start, end);
    if (candidate) found.push(candidate);
    else {
      const rich = richBlock("paragraph", sourceBlock, start, end, ordinal);
      if (rich) found.push(rich);
    }
    index = paragraphEnd;
  }

  const counts = new Map<string, number>();
  for (const candidate of found) counts.set(candidate.text, (counts.get(candidate.text) ?? 0) + 1);
  return [
    ...found.filter((candidate) => counts.get(candidate.text) === 1),
    ...formulaBlocks(source, lines, frontmatterEnd)
      .filter((candidate) => !insideTheorem(candidate.start)),
    ...theorem,
  ].sort((left, right) => left.start - right.start);
}

function escapedPlainText(value: string, kind: QmdEditableBlockKind): string {
  if (kind === "inline-math" || kind === "display-math") {
    const latex = kind === "inline-math" ? value.replace(/\s+/g, " ").trim() : value.trim();
    if (!latex) throw new Error("A formula cannot be empty");
    return latex;
  }
  if (kind === "theorem-block") {
    const qmd = value.trim();
    if (!/^:{3,}\s*\{[^}]*#(?:thm|lem|def)[-_]/im.test(qmd)
        || !/\n:{3,}\s*$/.test(qmd)) {
      throw new Error("A theorem, lemma, or definition must keep its fenced QMD block");
    }
    return qmd;
  }
  if (kind === "rich-block") {
    const qmd = value.trim();
    if (!qmd) throw new Error("A QMD block cannot be empty");
    return qmd;
  }
  const normalized = normalizedText(value);
  if (!normalized && kind !== "paragraph") {
    throw new Error("A heading or list label cannot be empty");
  }
  let escaped = normalized.replace(/[\\`*_{}\[\]<>|^~@$#]/g, (character) => `\\${character}`);
  if (kind === "paragraph") {
    escaped = escaped
      .replace(/^([+-])\s/, "\\$1 ")
      .replace(/^(\d+)([.)])\s/, "$1\\$2 ");
  }
  return escaped;
}

/** Applies a human preview edit only if its original source is still unique. */
export function applyQmdEditableBlock(
  source: string,
  selected: QmdEditableBlock,
  nextText: string,
): { source: string; changed: boolean } {
  let start = selected.start;
  let end = selected.end;
  if (source.slice(start, end) !== selected.source) {
    start = source.indexOf(selected.source);
    if (start < 0 || source.indexOf(selected.source, start + selected.source.length) >= 0) {
      throw new Error("This QMD block changed before this edit could be saved");
    }
    end = start + selected.source.length;
  }
  let replacement = escapedPlainText(nextText, selected.kind);
  if (selected.kind === "inline-math" || selected.kind === "display-math") {
    const leading = /^\s*/.exec(selected.source)?.[0] ?? "";
    const trailing = /\s*$/.exec(selected.source)?.[0] ?? "";
    replacement = `${leading}${replacement}${trailing}`;
  }
  if (replacement === selected.source) return { source, changed: false };
  return {
    source: `${source.slice(0, start)}${replacement}${source.slice(end)}`,
    changed: true,
  };
}

function visualBlock(
  kind: QmdVisualBlockKind,
  source: string,
  start: number,
  end: number,
  extra: Partial<Pick<QmdVisualBlock, "level" | "semantic" | "title">> = {},
): QmdVisualBlock {
  return { id: blockId("rich-block", `${kind}\u0000${source}`), kind, source, start, end, ...extra };
}

function visualFenceEnd(lines: SourceLine[], openingIndex: number): number {
  const opening = /^\s*(?<marks>:{3,})/.exec(lines[openingIndex]?.text || "")?.groups?.marks;
  if (!opening) return openingIndex;
  let depth = 1;
  for (let index = openingIndex + 1; index < lines.length; index += 1) {
    const trimmed = lines[index]!.text.trim();
    if (/^:{3,}\s*\{[^}]*\}\s*$/.test(trimmed)) depth += 1;
    else if (/^:{3,}\s*$/.test(trimmed)) depth -= 1;
    if (depth === 0) return index;
  }
  return openingIndex;
}

function semanticFence(attributes: string): string {
  const id = /(?:^|\s)#(?<kind>thm|lem|def|prp|cor|exm|proof)[-_]/i.exec(attributes)?.groups?.kind;
  if (id) return id.toLowerCase();
  const className = /(?:^|\s)\.(?<kind>theorem|lemma|definition|proposition|corollary|example|proof)(?:\s|$)/i
    .exec(attributes)?.groups?.kind;
  const names: Record<string, string> = {
    theorem: "thm", lemma: "lem", definition: "def", proposition: "prp",
    corollary: "cor", example: "exm", proof: "proof",
  };
  return className ? names[className.toLowerCase()] || "" : "";
}

function fenceTitle(source: string): string | undefined {
  const body = source.split(/\r?\n/).slice(1, -1);
  for (const line of body) {
    const heading = /^#{1,6}\s+(.+?)(?:\s+\{[^}]*\})?\s*$/.exec(line.trim());
    if (heading?.[1]) return heading[1].trim();
    if (line.trim()) break;
  }
  return undefined;
}

/**
 * Splits a QMD document into non-overlapping visual regions. Unknown syntax is
 * deliberately retained as a raw source block; Visual Edit must be lossless
 * before it is clever.
 */
export function visualQmdBlocks(source: string): QmdVisualBlock[] {
  const lines = sourceLines(source);
  const result: QmdVisualBlock[] = [];
  let index = 0;
  if (lines[0]?.text.trim() === "---") {
    let endIndex = 0;
    for (let cursor = 1; cursor < lines.length; cursor += 1) {
      if (/^(?:---|\.\.\.)\s*$/.test(lines[cursor]!.text)) { endIndex = cursor; break; }
    }
    if (endIndex > 0) {
      const start = lines[0]!.start;
      const end = lines[endIndex]!.end;
      result.push(visualBlock("frontmatter", source.slice(start, end), start, end));
      index = endIndex + 1;
    }
  }

  while (index < lines.length) {
    const line = lines[index]!;
    const trimmed = line.text.trim();
    if (!trimmed) { index += 1; continue; }

    const div = /^\s*:{3,}\s*\{(?<attributes>[^}]*)\}\s*$/.exec(line.text);
    if (div) {
      const closing = visualFenceEnd(lines, index);
      if (closing > index) {
        const start = line.start;
        const end = lines[closing]!.end;
        const raw = source.slice(start, end);
        const semantic = semanticFence(div.groups?.attributes || "");
        result.push(visualBlock(semantic ? "theorem" : "callout", raw, start, end, {
          semantic: semantic || undefined,
          title: fenceTitle(raw),
        }));
        index = closing + 1;
        continue;
      }
    }

    const codeOpening = /^\s*(?<fence>`{3,}|~{3,})/.exec(line.text)?.groups?.fence;
    if (codeOpening) {
      let closing = index + 1;
      while (closing < lines.length && !new RegExp(`^\\s*${codeOpening[0]}{${codeOpening.length},}\\s*$`).test(lines[closing]!.text)) closing += 1;
      if (closing >= lines.length) closing = lines.length - 1;
      const start = line.start;
      const end = lines[closing]!.end;
      result.push(visualBlock("code", source.slice(start, end), start, end));
      index = closing + 1;
      continue;
    }

    if (trimmed.startsWith("$$") || trimmed.startsWith("\\[")) {
      const closingToken = trimmed.startsWith("$$") ? "$$" : "\\]";
      let closing = index;
      const remainder = trimmed.slice(2);
      if (!remainder.endsWith(closingToken) || remainder.length <= closingToken.length) {
        closing += 1;
        while (closing < lines.length && !lines[closing]!.text.trimEnd().endsWith(closingToken)) closing += 1;
        if (closing >= lines.length) closing = lines.length - 1;
      }
      const start = line.start;
      const end = lines[closing]!.end;
      result.push(visualBlock("display-math", source.slice(start, end), start, end));
      index = closing + 1;
      continue;
    }

    const heading = /^(?<marks>#{1,6})\s+/.exec(trimmed);
    if (heading) {
      result.push(visualBlock("heading", line.text, line.start, line.end, { level: heading.groups?.marks?.length ?? 1 }));
      index += 1;
      continue;
    }

    const list = /^\s*(?:[-+*]|\d+[.)])\s+/.test(line.text);
    if (list) {
      let closing = index;
      while (closing + 1 < lines.length && (/^\s*(?:[-+*]|\d+[.)])\s+/.test(lines[closing + 1]!.text)
        || /^\s{2,}\S/.test(lines[closing + 1]!.text))) closing += 1;
      const start = line.start;
      const end = lines[closing]!.end;
      result.push(visualBlock("list", source.slice(start, end), start, end));
      index = closing + 1;
      continue;
    }

    if (/^\s*>/.test(line.text)) {
      let closing = index;
      while (closing + 1 < lines.length && /^\s*>/.test(lines[closing + 1]!.text)) closing += 1;
      const start = line.start;
      const end = lines[closing]!.end;
      result.push(visualBlock("blockquote", source.slice(start, end), start, end));
      index = closing + 1;
      continue;
    }

    if (/^(?:<|\||:::+|\{[^}]*\}\s*$)/.test(trimmed)) {
      result.push(visualBlock("raw", line.text, line.start, line.end));
      index += 1;
      continue;
    }

    let closing = index;
    while (closing + 1 < lines.length) {
      const next = lines[closing + 1]!.text;
      const nextTrimmed = next.trim();
      if (!nextTrimmed || /^\s*:{3,}\s*\{|^\s*(?:`{3,}|~{3,})|^#{1,6}\s+|^\s*(?:[-+*]|\d+[.)])\s+|^\s*>|^(?:\$\$|\\\[)/.test(next)) break;
      closing += 1;
    }
    const start = line.start;
    const end = lines[closing]!.end;
    result.push(visualBlock("paragraph", source.slice(start, end), start, end));
    index = closing + 1;
  }
  return result;
}

/** Applies one visual block edit with optimistic conflict detection. */
export function applyQmdVisualBlock(
  source: string,
  selected: QmdVisualBlock,
  replacement: string,
): { source: string; changed: boolean } {
  let start = selected.start;
  let end = selected.end;
  if (source.slice(start, end) !== selected.source) {
    start = source.indexOf(selected.source);
    if (start < 0 || source.indexOf(selected.source, start + selected.source.length) >= 0) {
      throw new Error("This QMD block changed before this edit could be saved");
    }
    end = start + selected.source.length;
  }
  const next = replacement.replace(/\r\n?/g, "\n");
  if (next === selected.source) return { source, changed: false };
  return { source: `${source.slice(0, start)}${next}${source.slice(end)}`, changed: true };
}

/** Finds math within one visual block so formulas can edit without flattening its card. */
export function qmdMathSpans(source: string): QmdMathSpan[] {
  const spans: QmdMathSpan[] = [];
  const patterns: Array<{ re: RegExp; display: boolean; opening: QmdMathSpan["opening"]; trim: number }> = [
    { re: /\$\$([\s\S]+?)\$\$/g, display: true, opening: "$$", trim: 2 },
    { re: /\\\[([\s\S]+?)\\\]/g, display: true, opening: "\\[", trim: 2 },
    { re: /\\\((.+?)\\\)/g, display: false, opening: "\\(", trim: 2 },
    { re: /(?<!\\)(?<!\$)\$(?!\$)([^\n$]+?)(?<!\\)\$(?!\$)/g, display: false, opening: "$", trim: 1 },
  ];
  const occupied: Array<[number, number]> = [];
  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern.re)) {
      const start = match.index ?? -1;
      if (start < 0) continue;
      const end = start + match[0].length;
      if (occupied.some(([left, right]) => start < right && end > left)) continue;
      occupied.push([start, end]);
      const latex = match[1] || "";
      const latexStart = start + pattern.trim;
      spans.push({
        source: match[0], latex,
        start: latexStart,
        end: latexStart + latex.length,
        display: pattern.display,
        opening: pattern.opening,
      });
    }
  }
  return spans.sort((left, right) => left.start - right.start);
}
