export const QMD_INLINE_READY_TOPIC = "ResearchLoop:QmdInlineReady";
export const QMD_INLINE_CONFIGURE_TOPIC = "ResearchLoop:QmdInlineConfigure";
export const QMD_INLINE_CONFIGURED_TOPIC = "ResearchLoop:QmdInlineConfigured";
export const QMD_INLINE_EDIT_TOPIC = "ResearchLoop:QmdInlineEdit";
export const QMD_INLINE_RESULT_TOPIC = "ResearchLoop:QmdInlineResult";

export type QmdEditableBlockKind =
  | "heading"
  | "paragraph"
  | "list-item"
  | "blockquote"
  | "inline-math"
  | "display-math"
  | "theorem-block"
  | "rich-block";

/**
 * One plain-text region that can be mapped losslessly between QMD and HTML.
 *
 * `source`, `start`, and `end` stay in privileged plugin code. The content
 * frame receives only `id`, `kind`, and rendered `text`, so an untrusted Draft
 * page cannot choose a filesystem range to overwrite.
 */
export interface QmdEditableBlock {
  id: string;
  kind: QmdEditableBlockKind;
  text: string;
  source: string;
  start: number;
  end: number;
  /** HTML id generated by Quarto for a thm/lem/def fenced div. */
  domId?: string;
  /** Rendered HTML block kind and source-order index for complex Markdown. */
  domKind?: "heading" | "paragraph" | "list-item" | "blockquote";
  ordinal?: number;
}

export interface QmdInlinePublicBlock {
  id: string;
  kind: QmdEditableBlockKind;
  text: string;
  domId?: string;
  domKind?: "heading" | "paragraph" | "list-item" | "blockquote";
  ordinal?: number;
}

export interface QmdInlineConfigureMessage {
  enabled: boolean;
  blocks: QmdInlinePublicBlock[];
}

export interface QmdInlineEditMessage {
  id: string;
  text: string;
}

export interface QmdInlineConfiguredMessage {
  enabled: boolean;
  mapped: number;
  total: number;
}

export interface QmdInlineResultMessage {
  id: string;
  ok: boolean;
  text?: string;
  error?: string;
}

interface SourceLine {
  text: string;
  start: number;
  end: number;
}

const PROTECTED_INLINE = new Set(["\\", "`", "*", "_", "{", "}", "[", "]", "<", ">", "|", "^", "~", "@", "$", "#"]);

function sourceLines(source: string): SourceLine[] {
  const lines: SourceLine[] = [];
  let start = 0;
  while (start < source.length) {
    const newline = source.indexOf("\n", start);
    const end = newline < 0 ? source.length : newline;
    lines.push({
      text: source.slice(start, end).replace(/\r$/, ""),
      start,
      end,
    });
    if (newline < 0) break;
    start = newline + 1;
  }
  return lines;
}

function normalizedText(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

/** Plain Markdown plus explicit escapes, or null when rendering changes it. */
function renderedPlainText(source: string): string | null {
  let result = "";
  for (let index = 0; index < source.length; index += 1) {
    const character = source[index]!;
    if (character === "\\") {
      const next = source[index + 1];
      if (!next || !PROTECTED_INLINE.has(next)) return null;
      result += next;
      index += 1;
      continue;
    }
    if (PROTECTED_INLINE.has(character)) return null;
    result += character;
  }
  const normalized = normalizedText(result);
  return normalized || null;
}

function blockId(kind: QmdEditableBlockKind, source: string): string {
  let hash = 0x811c9dc5;
  for (const character of `${kind}\u0000${source}`) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return `${kind}-${hash.toString(16).padStart(8, "0")}`;
}

function block(
  kind: QmdEditableBlockKind,
  source: string,
  start: number,
  end: number,
): QmdEditableBlock | null {
  const text = renderedPlainText(source);
  if (!text) return null;
  return { id: blockId(kind, source), kind, text, source, start, end };
}

function richBlock(
  domKind: "heading" | "paragraph" | "list-item" | "blockquote",
  source: string,
  start: number,
  end: number,
  ordinal: number,
): QmdEditableBlock | null {
  if (!source.trim()) return null;
  return {
    id: blockId("rich-block", `${domKind}\u0000${source}`),
    kind: "rich-block",
    text: source,
    source,
    start,
    end,
    domKind,
    ordinal,
  };
}

function formulaBlock(
  kind: "inline-math" | "display-math",
  source: string,
  start: number,
  end: number,
): QmdEditableBlock | null {
  const text = source.trim();
  if (!text) return null;
  return { id: blockId(kind, source), kind, text, source, start, end };
}

function escapedAt(value: string, index: number): boolean {
  let slashes = 0;
  for (let cursor = index - 1; cursor >= 0 && value[cursor] === "\\"; cursor -= 1) slashes += 1;
  return slashes % 2 === 1;
}

function formulaBlocks(source: string, lines: SourceLine[], frontmatterEnd: number): QmdEditableBlock[] {
  const formulas: QmdEditableBlock[] = [];
  let fenced = "";
  let displayStart = -1;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
    const line = lines[lineIndex]!;
    if (lineIndex <= frontmatterEnd) continue;
    const trimmed = line.text.trim();
    const fence = /^(?<fence>`{3,}|~{3,})/.exec(trimmed)?.groups?.fence ?? "";
    if (fence) {
      if (!fenced) fenced = fence[0]!;
      else if (fence[0] === fenced) fenced = "";
      continue;
    }
    if (fenced) continue;

    let cursor = 0;
    while (cursor < line.text.length) {
      const dollar = line.text.indexOf("$", cursor);
      if (dollar < 0) break;
      if (escapedAt(line.text, dollar)) {
        cursor = dollar + 1;
        continue;
      }
      const absolute = line.start + dollar;
      if (line.text[dollar + 1] === "$") {
        if (displayStart < 0) {
          displayStart = absolute + 2;
        }
        else {
          const candidate = formulaBlock(
            "display-math",
            source.slice(displayStart, absolute),
            displayStart,
            absolute,
          );
          if (candidate) formulas.push(candidate);
          displayStart = -1;
        }
        cursor = dollar + 2;
        continue;
      }
      if (displayStart >= 0) {
        cursor = dollar + 1;
        continue;
      }
      let close = dollar + 1;
      while (close < line.text.length) {
        close = line.text.indexOf("$", close);
        if (close < 0 || !escapedAt(line.text, close)) break;
        close += 1;
      }
      if (close < 0) break;
      const start = absolute + 1;
      const candidate = formulaBlock(
        "inline-math",
        source.slice(start, line.start + close),
        start,
        line.start + close,
      );
      if (candidate) formulas.push(candidate);
      cursor = close + 1;
    }
  }
  return formulas;
}

function theoremBlocks(source: string, lines: SourceLine[], frontmatterEnd: number): QmdEditableBlock[] {
  const blocks: QmdEditableBlock[] = [];
  for (let index = frontmatterEnd + 1; index < lines.length; index += 1) {
    const opening = /^\s*:{3,}\s*\{(?<attributes>[^}]*)\}\s*$/.exec(lines[index]!.text);
    const domId = /(?:^|\s)#(?<id>(?:thm|lem|def)[-_][A-Za-z0-9_.:-]+)/i
      .exec(opening?.groups?.attributes ?? "")?.groups?.id;
    if (!opening || !domId) continue;
    let depth = 1;
    let closing = index + 1;
    for (; closing < lines.length; closing += 1) {
      const trimmed = lines[closing]!.text.trim();
      if (/^:{3,}\s*\{[^}]*\}\s*$/.test(trimmed)) depth += 1;
      else if (/^:{3,}\s*$/.test(trimmed)) depth -= 1;
      if (depth === 0) break;
    }
    if (depth !== 0 || closing >= lines.length) continue;
    const start = lines[index]!.start;
    const end = lines[closing]!.end;
    const raw = source.slice(start, end);
    blocks.push({
      id: blockId("theorem-block", raw),
      kind: "theorem-block",
      text: raw,
      source: raw,
      start,
      end,
      domId,
    });
    index = closing;
  }
  return blocks;
}

function structuralLine(value: string): boolean {
  const trimmed = value.trim();
  return !trimmed
    || /^(?:```|~~~|:::+|\$\$|\\\[|\\\]|[-*_]{3,})/.test(trimmed)
    || /^#{1,6}\s+/.test(trimmed)
    || /^(?:[-+*]|\d+[.)])\s+/.test(trimmed)
    || /^>\s?/.test(trimmed)
    || /^\{[^}]*\}$/.test(trimmed)
    || /^: \S/.test(trimmed);
}

/**
 * Finds blocks that can be mapped back to one rendered DOM region. Plain text
 * edits directly; rich Markdown temporarily exposes the source for that one
 * block. Duplicate visible text is excluded because the HTML side could not
 * identify it without guessing.
 */
export function editableQmdBlocks(source: string): QmdEditableBlock[] {
  const lines = sourceLines(source);
  const found: QmdEditableBlock[] = [];
  let frontmatterEnd = -1;
  if (lines[0]?.text.trim() === "---") {
    for (let index = 1; index < lines.length; index += 1) {
      if (/^(?:---|\.\.\.)\s*$/.test(lines[index]!.text)) {
        frontmatterEnd = index;
        break;
      }
    }
  }

  const theorem = theoremBlocks(source, lines, frontmatterEnd);
  const insideTheorem = (offset: number) => theorem.some((candidate) =>
    offset >= candidate.start && offset < candidate.end);
  const ordinals = new Map<QmdEditableBlock["domKind"], number>();
  const nextOrdinal = (kind: NonNullable<QmdEditableBlock["domKind"]>): number => {
    const ordinal = ordinals.get(kind) ?? 0;
    ordinals.set(kind, ordinal + 1);
    return ordinal;
  };
  let fenced = "";
  let displayMath = false;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]!;
    if (index <= frontmatterEnd) continue;
    if (insideTheorem(line.start)) continue;
    const trimmed = line.text.trim();
    const fence = /^(?<fence>`{3,}|~{3,})/.exec(trimmed)?.groups?.fence ?? "";
    if (fence) {
      if (!fenced) fenced = fence[0]!;
      else if (fence[0] === fenced) fenced = "";
      continue;
    }
    if (fenced) continue;
    if (trimmed === "$$" || trimmed === "\\[" || trimmed === "\\]") {
      displayMath = !displayMath;
      continue;
    }
    if (displayMath || !trimmed || /^:::+/.test(trimmed) || /^\{[^}]*\}$/.test(trimmed)) continue;
    if (/^ {4}|^\t/.test(line.text)) continue;

    const heading = /^(\s*#{1,6}\s+)(.*?)(\s+\{[^}]*\})?\s*$/.exec(line.text);
    if (heading) {
      const content = heading[2]!;
      const start = line.start + heading[1]!.length;
      const ordinal = nextOrdinal("heading");
      const candidate = block("heading", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("heading", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    const listItem = /^(\s*(?:[-+*]|\d+[.)])\s+)(.+?)\s*$/.exec(line.text);
    if (listItem) {
      const content = listItem[2]!;
      const start = line.start + listItem[1]!.length;
      const ordinal = nextOrdinal("list-item");
      const candidate = block("list-item", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("list-item", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    const quote = /^(\s*>\s?)(.+?)\s*$/.exec(line.text);
    if (quote) {
      const content = quote[2]!;
      const start = line.start + quote[1]!.length;
      const ordinal = nextOrdinal("blockquote");
      const candidate = block("blockquote", content, start, start + content.length);
      if (candidate) found.push(candidate);
      else {
        const rich = richBlock("blockquote", content, start, start + content.length, ordinal);
        if (rich) found.push(rich);
      }
      continue;
    }

    if (structuralLine(line.text)) continue;
    const paragraphStart = index;
    let paragraphEnd = index;
    while (paragraphEnd + 1 < lines.length && !structuralLine(lines[paragraphEnd + 1]!.text)) {
      const next = lines[paragraphEnd + 1]!;
      if (/^ {4}|^\t/.test(next.text)) break;
      paragraphEnd += 1;
    }
    const start = lines[paragraphStart]!.start;
    const end = lines[paragraphEnd]!.end;
    const sourceBlock = source.slice(start, end);
    const ordinal = nextOrdinal("paragraph");
    const candidate = block("paragraph", sourceBlock, start, end);
    if (candidate) found.push(candidate);
    else {
      const rich = richBlock("paragraph", sourceBlock, start, end, ordinal);
      if (rich) found.push(rich);
    }
    index = paragraphEnd;
  }

  const counts = new Map<string, number>();
  for (const candidate of found) counts.set(candidate.text, (counts.get(candidate.text) ?? 0) + 1);
  return [
    ...found.filter((candidate) => counts.get(candidate.text) === 1),
    ...formulaBlocks(source, lines, frontmatterEnd)
      .filter((candidate) => !insideTheorem(candidate.start)),
    ...theorem,
  ].sort((left, right) => left.start - right.start);
}

function escapedPlainText(value: string, kind: QmdEditableBlockKind): string {
  if (kind === "inline-math" || kind === "display-math") {
    const latex = kind === "inline-math" ? value.replace(/\s+/g, " ").trim() : value.trim();
    if (!latex) throw new Error("A formula cannot be empty");
    return latex;
  }
  if (kind === "theorem-block") {
    const qmd = value.trim();
    if (!/^:{3,}\s*\{[^}]*#(?:thm|lem|def)[-_]/im.test(qmd)
        || !/\n:{3,}\s*$/.test(qmd)) {
      throw new Error("A theorem, lemma, or definition must keep its fenced QMD block");
    }
    return qmd;
  }
  if (kind === "rich-block") {
    const qmd = value.trim();
    if (!qmd) throw new Error("A QMD block cannot be empty");
    return qmd;
  }
  const normalized = normalizedText(value);
  if (!normalized && kind !== "paragraph") {
    throw new Error("A heading or list label cannot be empty");
  }
  let escaped = normalized.replace(/[\\`*_{}\[\]<>|^~@$#]/g, (character) => `\\${character}`);
  if (kind === "paragraph") {
    escaped = escaped
      .replace(/^([+-])\s/, "\\$1 ")
      .replace(/^(\d+)([.)])\s/, "$1\\$2 ");
  }
  return escaped;
}

/** Applies a human preview edit only if its original source is still unique. */
export function applyQmdEditableBlock(
  source: string,
  selected: QmdEditableBlock,
  nextText: string,
): { source: string; changed: boolean } {
  let start = selected.start;
  let end = selected.end;
  if (source.slice(start, end) !== selected.source) {
    start = source.indexOf(selected.source);
    if (start < 0 || source.indexOf(selected.source, start + selected.source.length) >= 0) {
      throw new Error("This QMD block changed before this edit could be saved");
    }
    end = start + selected.source.length;
  }
  let replacement = escapedPlainText(nextText, selected.kind);
  if (selected.kind === "inline-math" || selected.kind === "display-math") {
    const leading = /^\s*/.exec(selected.source)?.[0] ?? "";
    const trailing = /\s*$/.exec(selected.source)?.[0] ?? "";
    replacement = `${leading}${replacement}${trailing}`;
  }
  if (replacement === selected.source) return { source, changed: false };
  return {
    source: `${source.slice(0, start)}${replacement}${source.slice(end)}`,
    changed: true,
  };
}

/**
 * A delayed frame script for the remote Zotero browser. It edits only the
 * blocks selected by privileged code and reports plain text back through the
 * browser message manager. The preview remains a remote content process.
 */
export function qmdInlineFrameScript(): string {
  return String.raw`(() => {
    if (globalThis.__researchLoopQmdInlineEdit) return;
    globalThis.__researchLoopQmdInlineEdit = true;
    const READY = ${JSON.stringify(QMD_INLINE_READY_TOPIC)};
    const CONFIGURE = ${JSON.stringify(QMD_INLINE_CONFIGURE_TOPIC)};
    const CONFIGURED = ${JSON.stringify(QMD_INLINE_CONFIGURED_TOPIC)};
    const EDIT = ${JSON.stringify(QMD_INLINE_EDIT_TOPIC)};
    const RESULT = ${JSON.stringify(QMD_INLINE_RESULT_TOPIC)};
    const normalize = (value) => String(value || "").replace(/\s+/g, " ").trim();
    const original = new WeakMap();
    const metadata = new WeakMap();
    const rendered = new WeakMap();

    function kindOf(element) {
      if (element.matches("span.math.inline")) return "inline-math";
      if (element.matches("span.math.display")) return "display-math";
      if (element.matches(".callout[id^='thm-'],.callout[id^='lem-'],.callout[id^='def-']")) return "theorem-block";
      if (element.matches(".callout-title-container")) return "heading";
      if (/^H[1-6]$/.test(element.tagName)) return "heading";
      if (element.tagName === "LI") return "list-item";
      if (element.tagName === "BLOCKQUOTE" || element.closest("blockquote")) return "blockquote";
      return "paragraph";
    }

    function candidates() {
      const document = content.document;
      const root = document.querySelector("main.content, #quarto-content main, main") || document.body;
      if (!root) return [];
      return [...root.querySelectorAll(".callout[id^='thm-'],.callout[id^='lem-'],.callout[id^='def-'],.callout-title-container,h1,h2,h3,h4,h5,h6,p,li:not(:has(p)),blockquote:not(:has(p)),span.math.inline,span.math.display")]
        .filter((element) => !element.closest("nav,.sidebar,.toc,.quarto-title-meta,pre,script,style"))
        .filter((element) => {
          const theorem = element.closest(".callout[id^='thm-'],.callout[id^='lem-'],.callout[id^='def-']");
          return !theorem || theorem === element;
        })
        .filter((element) => element.matches("span.math") || !element.closest("span.math"))
        .map((element) => ({ element, kind: kindOf(element), text: normalize(element.textContent), used: false }));
    }

    function clear() {
      for (const element of content.document.querySelectorAll("[data-qlab-qmd-block]")) {
        const kind = metadata.get(element)?.kind;
        if (kind === "theorem-block" || kind === "rich-block") restoreStructured(element);
        else if (kind?.endsWith("math") && element.querySelector(".qlab-qmd-latex")) {
          renderMath(element, original.get(element) || "", kind);
        }
        else if (!kind?.endsWith("math")) element.textContent = original.get(element) || element.textContent;
        element.removeAttribute("contenteditable");
        element.removeAttribute("data-qlab-qmd-block");
        element.removeAttribute("data-qlab-qmd-state");
        element.removeAttribute("title");
        element.spellcheck = false;
      }
    }

    function ensureStyle() {
      const document = content.document;
      if (document.getElementById("qlab-qmd-inline-style")) return;
      const style = document.createElement("style");
      style.id = "qlab-qmd-inline-style";
      style.textContent = [
        '[data-qlab-qmd-block] { cursor: text; border-radius: 4px; transition: background-color .15s, box-shadow .15s; }',
        '[data-qlab-qmd-block]:hover { background: color-mix(in srgb, #0a84ff 7%, transparent); box-shadow: 0 0 0 3px color-mix(in srgb, #0a84ff 7%, transparent); }',
        '[data-qlab-qmd-block]:focus { outline: 2px solid color-mix(in srgb, #0a84ff 72%, transparent); outline-offset: 4px; background: color-mix(in srgb, #0a84ff 5%, transparent); }',
        'span.math[data-qlab-qmd-block] { display: inline-block; min-width: 1.2em; }',
        'span.math.display[data-qlab-qmd-block] { display: block; }',
        '[data-qlab-qmd-block] > .qlab-qmd-latex { width: max(9em, 100%); min-width: 9em; padding: 3px 6px; border: 1px solid #0a84ff; border-radius: 4px; color: inherit; background: color-mix(in srgb, Canvas 94%, #0a84ff 6%); font: .9em/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }',
        'span.math.display[data-qlab-qmd-block] > .qlab-qmd-latex { display: block; min-height: 5.5em; margin: .45em auto; resize: vertical; }',
        '[data-qlab-qmd-block] > .qlab-qmd-block-source { display: block; box-sizing: border-box; width: 100%; min-height: 7em; padding: 10px 12px; border: 1px solid #0a84ff; border-radius: 5px; color: #1f2933; background: #f7fbff; resize: vertical; font: 13px/1.55 ui-monospace, SFMono-Regular, Menlo, monospace; tab-size: 2; }',
        '.callout[data-qlab-qmd-block] > .qlab-qmd-block-source { min-height: 15em; border: 0; border-radius: inherit; padding: 12px 14px; }',
        '[data-qlab-qmd-state="saving"] { outline-color: #d79b00; }',
        '[data-qlab-qmd-state="saved"] { animation: qlab-qmd-saved .7s ease-out; }',
        '[data-qlab-qmd-state="error"] { outline: 2px solid #d70022; outline-offset: 4px; }',
        '@keyframes qlab-qmd-saved { from { box-shadow: 0 0 0 5px rgba(34,160,107,.2); } to { box-shadow: none; } }',
      ].join('');
      document.head?.appendChild(style);
    }

    function configure(data) {
      clear();
      if (!data || !data.enabled || !Array.isArray(data.blocks)) {
        sendAsyncMessage(CONFIGURED, { enabled: false, mapped: 0, total: 0 });
        return;
      }
      ensureStyle();
      const available = candidates();
      let mapped = 0;
      for (const block of data.blocks) {
        const formula = block.kind === "inline-math" || block.kind === "display-math";
        const theorem = block.kind === "theorem-block";
        const rich = block.kind === "rich-block";
        const wanted = normalize(block.text);
        let selected;
        if (rich) {
          const ordinal = Number(block.ordinal);
          selected = Number.isInteger(ordinal)
            ? available.filter((candidate) => candidate.kind === block.domKind)[ordinal]
            : undefined;
          if (!selected || selected.used) continue;
        }
        else {
          const matches = available.filter((candidate) => {
            if (candidate.used || candidate.kind !== block.kind) return false;
            if (formula) return true;
            if (theorem) return candidate.element.id === block.domId;
            if (candidate.text === wanted) return true;
            return block.kind === "heading"
              && candidate.element.matches(".callout-title-container")
              && candidate.text.endsWith(wanted);
          });
          if (formula ? matches.length < 1 : matches.length !== 1) continue;
          selected = matches[0];
        }
        selected.used = true;
        let element = selected.element;
        if (!formula && !theorem && block.kind === "heading"
            && element.matches(".callout-title-container")
            && selected.text !== wanted) {
          const prefix = selected.text.slice(0, selected.text.length - wanted.length);
          const editable = content.document.createElement("span");
          editable.textContent = block.text;
          element.replaceChildren(content.document.createTextNode(prefix), editable);
          element = editable;
        }
        element.setAttribute("data-qlab-qmd-block", block.id);
        mapped += 1;
        metadata.set(element, { kind: block.kind });
        original.set(element, block.text);
        if (theorem || rich) {
          rendered.set(element, element.innerHTML);
          element.setAttribute(
            "title",
            theorem ? "Edit this theorem block as QMD" : "Edit this rich block as QMD",
          );
        }
        else if (formula) {
          element.setAttribute("title", "Edit LaTeX");
        }
        else {
          element.setAttribute("contenteditable", "plaintext-only");
          element.setAttribute("title", "Edit this Draft text · Enter saves · Esc cancels");
          element.spellcheck = true;
        }
      }
      sendAsyncMessage(CONFIGURED, { enabled: true, mapped, total: data.blocks.length });
    }

    function renderMath(element, latex, kind) {
      const source = kind === "inline-math"
        ? "\\\\(" + latex + "\\\\)"
        : "\\\\[\n" + latex + "\n\\\\]";
      const mathJax = content.MathJax;
      try { mathJax?.typesetClear?.([element]); } catch {}
      element.textContent = source;
      try { void mathJax?.typesetPromise?.([element]); } catch {}
    }

    function restoreStructured(element) {
      const html = rendered.get(element);
      if (typeof html === "string") element.innerHTML = html;
    }

    content.addEventListener("click", (event) => {
      const formula = event.target?.closest?.("span.math[data-qlab-qmd-block]");
      if (formula && !formula.querySelector(".qlab-qmd-latex")) {
        event.preventDefault();
        event.stopPropagation();
        const kind = metadata.get(formula)?.kind;
        const editor = content.document.createElement(kind === "display-math" ? "textarea" : "input");
        editor.className = "qlab-qmd-latex";
        editor.value = original.get(formula) || "";
        editor.setAttribute("aria-label", kind === "display-math" ? "Edit display LaTeX" : "Edit inline LaTeX");
        formula.replaceChildren(editor);
        editor.focus();
        editor.select();
        return;
      }
      const structured = event.target?.closest?.(
        '.callout[data-qlab-qmd-block],[data-qlab-qmd-block]:not([contenteditable]):not(.math)',
      );
      const kind = structured ? metadata.get(structured)?.kind : "";
      if (structured && (kind === "theorem-block" || kind === "rich-block")
          && !structured.querySelector(".qlab-qmd-block-source")) {
        event.preventDefault();
        event.stopPropagation();
        const editor = content.document.createElement("textarea");
        editor.className = "qlab-qmd-block-source";
        editor.value = original.get(structured) || "";
        editor.setAttribute(
          "aria-label",
          kind === "theorem-block"
            ? "Edit theorem, lemma, or definition QMD source"
            : "Edit this QMD block source",
        );
        structured.replaceChildren(editor);
        editor.focus();
        return;
      }
    }, true);

    content.addEventListener("focusin", (event) => {
      const element = event.target?.closest?.("[data-qlab-qmd-block]");
      if (element && !metadata.get(element)?.kind?.endsWith("math")
          && metadata.get(element)?.kind !== "theorem-block"
          && metadata.get(element)?.kind !== "rich-block") {
        original.set(element, normalize(element.textContent));
      }
    }, true);
    content.addEventListener("keydown", (event) => {
      const element = event.target?.closest?.("[data-qlab-qmd-block]");
      if (!element) return;
      const kind = metadata.get(element)?.kind;
      const structured = kind === "theorem-block" || kind === "rich-block";
      if (event.key === "Escape") {
        event.preventDefault();
        if (structured) restoreStructured(element);
        else if (kind?.endsWith("math")) {
          renderMath(element, original.get(element) || "", kind);
        }
        else element.textContent = original.get(element) || "";
        event.target.blur();
      }
      else if (event.key === "Enter"
          && !structured
          && (kind !== "display-math" || event.metaKey || event.ctrlKey)) {
        event.preventDefault();
        event.target.blur();
      }
    }, true);
    content.addEventListener("paste", (event) => {
      const element = event.target?.closest?.("[data-qlab-qmd-block]");
      if (!element) return;
      if (metadata.get(element)?.kind?.endsWith("math")
          || metadata.get(element)?.kind === "theorem-block"
          || metadata.get(element)?.kind === "rich-block") return;
      event.preventDefault();
      content.document.execCommand("insertText", false, event.clipboardData?.getData("text/plain") || "");
    }, true);
    content.addEventListener("focusout", (event) => {
      const element = event.target?.closest?.("[data-qlab-qmd-block]");
      if (!element) return;
      const kind = metadata.get(element)?.kind;
      const formula = kind === "inline-math" || kind === "display-math";
      const structured = kind === "theorem-block" || kind === "rich-block";
      if (formula && !event.target?.matches?.(".qlab-qmd-latex")) return;
      if (structured && !event.target?.matches?.(".qlab-qmd-block-source")) return;
      const before = original.get(element) || "";
      const text = structured
        ? event.target.value.trim()
        : formula
          ? (kind === "display-math" ? event.target.value.trim() : normalize(event.target.value))
          : normalize(element.textContent);
      if (text === before) {
        if (structured) restoreStructured(element);
        else if (formula) renderMath(element, before, kind);
        return;
      }
      element.setAttribute("data-qlab-qmd-state", "saving");
      if (structured) restoreStructured(element);
      else if (formula) renderMath(element, text, kind);
      sendAsyncMessage(EDIT, { id: element.getAttribute("data-qlab-qmd-block"), text });
    }, true);

    addMessageListener(CONFIGURE, (message) => configure(message.data));
    addMessageListener(RESULT, (message) => {
      const data = message.data || {};
      const element = [...content.document.querySelectorAll("[data-qlab-qmd-block]")]
        .find((candidate) => candidate.getAttribute("data-qlab-qmd-block") === data.id);
      if (!element) return;
      if (data.ok) {
        element.setAttribute("data-qlab-qmd-state", "saved");
        const kind = metadata.get(element)?.kind;
        original.set(
          element,
          kind === "theorem-block" || kind === "rich-block" || kind?.endsWith("math")
            ? String(data.text || "")
            : normalize(data.text ?? element.textContent),
        );
        setTimeout(() => element.removeAttribute("data-qlab-qmd-state"), 800);
      }
      else {
        const kind = metadata.get(element)?.kind;
        if (kind === "theorem-block" || kind === "rich-block") restoreStructured(element);
        else if (kind?.endsWith("math")) renderMath(element, data.text || original.get(element) || "", kind);
        else element.textContent = data.text || original.get(element) || "";
        element.setAttribute("data-qlab-qmd-state", "error");
        element.setAttribute("title", data.error || "This edit could not be saved");
      }
    });

    const ready = () => sendAsyncMessage(READY, { url: content.location.href });
    content.addEventListener("DOMContentLoaded", ready, true);
    content.addEventListener("pageshow", ready, true);
    if (content.document?.readyState !== "loading") ready();
  })();`;
}
