---
title: "Research Workspace"
subtitle: "Collaborative Environment & Internal Discussion Boards"
toc: false
---
Welcome to the internal collaboration hub. This area is designated for asynchronous discussion, peer review of mathematical proofs, and experimental design planning!

## Idea Pockets

1. Is there a multi-copy assisted robust strategy to manifest large scale square magic game/ Bell inequality?
2. The package [NCTSSoS.jl](https://github.com/QuantumSOS/NCTSSoS.jl) is a newly developed method for solving sparse noncommutative polynomial optimization problems. Could it be used to solve:
    - Find optimal shadow strategy on a give non-commuting Pauli operators?
    - Find new square magic problem.


## Project Boards

Please navigate to the appropriate board based on the research domain:

::: {.grid}

::: {.g-col-12}
### Better Decoder for qLDPC code.
<i class="bi bi-house"></i> [**Progress Page**](Multi-shadow/index.qmd) |
<i class="bi bi-envelope"></i> [**Overleaf**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |
<i class="bi bi-github"></i> [**Github Board**](https://github.com/TensorBFS/BPDecoderPlus) |

**Scope:** Quantum error correction
:::

::: {.g-col-12}
### Multi-copy Shadow Tomography
<i class="bi bi-house"></i> [**Progress Page**](Multi-shadow/index.qmd) |
<i class="bi bi-envelope"></i> [**Overleaf**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |
<i class="bi bi-github"></i> [**Github Board**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |

**Scope:** Analysis of sample complexity, classical shadows, and variance bounds for multi-copy measurements.
:::

::: {.g-col-12}
### Early-stage Neutral atoms array
<i class="bi bi-house"></i> [**Progress Page**](./Early-stage-NA/index.qmd) |
<i class="bi bi-envelope"></i> [**Overleaf**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |
<i class="bi bi-github"></i> [**Github Board**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |
<!-- <i class="bi bi-envelope"></i> [**Overleaf**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) |
<i class="bi bi-github"></i> [**Github Board**](https://github.com/yourusername/your-private-repo/discussions/categories/shadow-tomography) | -->

**Scope:** 
:::

:::

---

